import type { ProgramEdge } from "./edge";
import { buildConnectionSentinel } from "./edge";
import type { ProgramOption } from "./option";
import type { ProgramProcess } from "./process";
import type { Program } from "./program";
import { DEFAULT_SCHEDULER } from "./program";

// The edits of a program, as plain functions that take a program and return
// the edited one without changing their input. They depend on nothing but the
// model, so the editor and any other client of the model (a tool that edits a
// program outside the browser) share one implementation. Ids are generated by
// the caller, never here, so that an edit gives the same result each time it
// is applied.
//
// What an edit does not do: keep the references of the connected options in
// step with the connections, which normalizeProgram does after every edit, and
// ask the user before an edit frees a group of processes added with another
// program, which is up to the caller (see dissolveGroups).

/**
 * Makes each option's `value` reflect its incoming edge (if any): connected
 * options get the "[process;option]" reference, others are cleared of any
 * stale one. Self-heals programs whose edges/values fell out of sync, e.g.
 * a file saved before this syncing existed, or a hand-edited JSON file.
 */
function normalizeConnectedOptionValues(source: Program): Program {

  const connectedValueByOptionKey = new Map<string, string>();

  for (const edge of source.edges) {

    const sourceProcess = source.processes.find(
      process => process.id === edge.sourceProcessId
    );

    const sourceOption = sourceProcess?.options.find(
      o => o.id === edge.sourceOptionId
    );

    if (sourceProcess && sourceOption) {
      connectedValueByOptionKey.set(
        `${edge.targetProcessId}:${edge.targetOptionId}`,
        buildConnectionSentinel(sourceProcess.name, sourceOption.label)
      );
    }

  }

  return {

    ...source,

    processes: source.processes.map(process => ({

      ...process,

      options: process.options.map(option => {

        // A "shared_dir" option's value is always its declared
        // directory name, independent of any connection, a connection
        // into/out of it exists purely to document the multi-writer
        // dependency in the canvas (see isValidProgramConnection), not
        // to supply its value the way a "none"-channel connection does.
        if (option.channel === "shared_dir") {
          return option;
        }

        const connectedValue =
          connectedValueByOptionKey.get(`${process.id}:${option.id}`);

        if (connectedValue !== undefined) {
          return option.value === connectedValue
            ? option
            : { ...option, value: connectedValue };
        }

        return option.value.startsWith("[") && option.value.endsWith("]")
          ? { ...option, value: "" }
          : option;

      }),

    })),

  };

}

/**
 * Re-derives every connected option's "[process;option]" value from the
 * current edges and names, so renaming a process or a connected option's
 * label can't leave a stale reference behind in what gets saved/generated.
 * Also self-heals a falsy executionOptions.scheduler (e.g. a file saved
 * while it was blank, see ExecutionOptionsEditor, whose dropdown defaults
 * its *displayed* value to "BUILTIN" without ever correcting a genuinely
 * empty stored one, since Cancel is a no-op) back to a valid default.
 * Without this, debasher_exec/debasher_status get "--sched ''" and fail
 * with "Error: is not a valid scheduler" even though the UI appears to
 * show "BUILTIN" selected.
 */
export function normalizeProgram(source: Program): Program {

  const normalized = normalizeConnectedOptionValues(source);

  return normalized.executionOptions.scheduler
    ? normalized
    : {
        ...normalized,
        executionOptions: {
          ...normalized.executionOptions,
          scheduler: DEFAULT_SCHEDULER,
        },
      };

}

/**
 * Strips groupSource from every process and sequential process of the given
 * groups, which are then generated one by one. A process added with another
 * program ("Add program") is re-declared, unmodified, by add_debasher_program
 * from its source module, so an edit of its definition, or of an edge that
 * targets it, would be overwritten once generated: the caller frees its whole
 * group first.
 */
export function dissolveGroups(source: Program, groupIds: Set<string>): Program {

  if (groupIds.size === 0) {
    return source;
  }

  const inGroup = (groupId?: string) => groupId !== undefined && groupIds.has(groupId);

  return {
    ...source,
    processes: source.processes.map(process =>
      inGroup(process.groupSource?.groupId) ? { ...process, groupSource: undefined } : process
    ),
    seqProcesses: (source.seqProcesses ?? []).map(seqProcess =>
      inGroup(seqProcess.groupSource?.groupId) ? { ...seqProcess, groupSource: undefined } : seqProcess
    ),
  };

}

// The fields of the program itself that an edit sets as a whole.
export type ProgramFields = Partial<Pick<
  Program,
  "name" | "description" | "preamble" | "sharedDirs" | "outputDir" | "executionOptions" | "programOptions"
>>;

export function setProgramFields(program: Program, changes: ProgramFields): Program {
  return { ...program, ...changes };
}

export function setEnvVar(program: Program, name: string, value: string): Program {
  return { ...program, envVars: { ...program.envVars, [name]: value } };
}

export function addProcess(program: Program, process: ProgramProcess): Program {
  return { ...program, processes: [...program.processes, process] };
}

// Removes the process with the edges left dangling by it.
export function removeProcess(program: Program, processId: string): Program {
  return {
    ...program,
    processes: program.processes.filter(process => process.id !== processId),
    edges: program.edges.filter(
      edge => edge.sourceProcessId !== processId && edge.targetProcessId !== processId
    ),
  };
}

function mapProcess(
  program: Program,
  processId: string,
  edit: (process: ProgramProcess) => ProgramProcess
): Program {
  return {
    ...program,
    processes: program.processes.map(process =>
      process.id === processId ? edit(process) : process
    ),
  };
}

export type ProcessChanges = Partial<Omit<ProgramProcess, "id">>;

export function updateProcess(program: Program, processId: string, changes: ProcessChanges): Program {
  return mapProcess(program, processId, process => ({ ...process, ...changes }));
}

export function addOption(program: Program, processId: string, option: ProgramOption): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: [...process.options, option],
  }));
}

export type OptionChanges = Partial<Omit<ProgramOption, "id">>;

export function updateOption(
  program: Program,
  processId: string,
  optionId: string,
  changes: OptionChanges
): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: process.options.map(option =>
      option.id === optionId ? { ...option, ...changes } : option
    ),
  }));
}

export function removeOption(program: Program, processId: string, optionId: string): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: process.options.filter(option => option.id !== optionId),
  }));
}

/**
 * Adds the edge and gives its target option the reference to its source.
 * A "shared_dir" source's channel/value already fully determines its
 * resolved path, so connecting it into a plain target promotes that target
 * into a matching "shared_dir" option too, instead of the usual
 * "[proc;option]" sentinel, so a second connection from another writer of
 * the same directory validates against an already-tagged, matching target
 * (see isValidProgramConnection) and both keep generating the same compact
 * get_absolute_shdirname-based code (see script_generation.py's shared_dir
 * branch) rather than one becoming a define_opt_from_proc_out reference to
 * this specific source.
 */
export function connect(program: Program, edge: ProgramEdge): Program {

  const sourceProcess = program.processes.find(
    process => process.id === edge.sourceProcessId
  );

  const sourceOption = sourceProcess?.options.find(
    o => o.id === edge.sourceOptionId
  );

  const connected = sourceProcess && sourceOption
    ? updateOption(
        program,
        edge.targetProcessId,
        edge.targetOptionId,
        sourceOption.channel === "shared_dir"
          ? { channel: "shared_dir", value: sourceOption.value }
          : { value: buildConnectionSentinel(sourceProcess.name, sourceOption.label) }
      )
    : program;

  return { ...connected, edges: [...connected.edges, edge] };

}

/**
 * Removes the edge and clears the value of its target option, except for a
 * "shared_dir" target, whose declared directory name is independent of any
 * connection.
 */
export function disconnect(program: Program, edgeId: string): Program {

  const removedEdge = program.edges.find(e => e.id === edgeId);

  const targetOption = removedEdge && program.processes
    .find(process => process.id === removedEdge.targetProcessId)
    ?.options.find(o => o.id === removedEdge.targetOptionId);

  const disconnected = removedEdge && targetOption?.channel !== "shared_dir"
    ? updateOption(program, removedEdge.targetProcessId, removedEdge.targetOptionId, { value: "" })
    : program;

  return { ...disconnected, edges: disconnected.edges.filter(e => e.id !== edgeId) };

}
