import type { ProgramEdge } from "./edge";
import { buildConnectionSentinel } from "./edge";
import { hasSupervisor } from "./node";
import type { ProgramOption } from "./option";
import type { Position } from "./position";
import type { GroupSource, ProgramProcess } from "./process";
import type { Program } from "./program";
import { DEFAULT_SCHEDULER } from "./program";
import type { SeqProcess } from "./seqProcess";

// The edits of a program, as plain functions that take a program and return
// the edited one without changing their input. They depend on nothing but the
// model, so the editor and any other client of the model (a tool that edits a
// program outside the browser) share one implementation. Ids are generated by
// the caller, never here, so that an edit gives the same result each time it
// is applied.
//
// What an edit does not do: keep the references of the connected options in
// step with the connections, which normalizeProgram does after every edit, and
// ask the user before an edit frees a group of processes added with another
// program, which is up to the caller (see dissolveGroups).

/**
 * Makes each option's `value` reflect its incoming edge (if any): connected
 * options get the "[process;option]" reference, others are cleared of any
 * stale one. Self-heals programs whose edges/values fell out of sync, e.g.
 * a file saved before this syncing existed, or a hand-edited JSON file.
 */
function normalizeConnectedOptionValues(source: Program): Program {

  const connectedValueByOptionKey = new Map<string, string>();

  for (const edge of source.edges) {

    const sourceProcess = source.processes.find(
      process => process.id === edge.sourceProcessId
    );

    const sourceOption = sourceProcess?.options.find(
      o => o.id === edge.sourceOptionId
    );

    if (sourceProcess && sourceOption) {
      connectedValueByOptionKey.set(
        `${edge.targetProcessId}:${edge.targetOptionId}`,
        buildConnectionSentinel(sourceProcess.name, sourceOption.label)
      );
    }

  }

  return {

    ...source,

    processes: source.processes.map(process => ({

      ...process,

      options: process.options.map(option => {

        // A "shared_dir" option's value is always its declared
        // directory name, independent of any connection, a connection
        // into/out of it exists purely to document the multi-writer
        // dependency in the canvas (see isValidEdge), not
        // to supply its value the way a "none"-channel connection does.
        if (option.channel === "shared_dir") {
          return option;
        }

        const connectedValue =
          connectedValueByOptionKey.get(`${process.id}:${option.id}`);

        if (connectedValue !== undefined) {
          return option.value === connectedValue
            ? option
            : { ...option, value: connectedValue };
        }

        return option.value.startsWith("[") && option.value.endsWith("]")
          ? { ...option, value: "" }
          : option;

      }),

    })),

  };

}

/**
 * Re-derives every connected option's "[process;option]" value from the
 * current edges and names, so renaming a process or a connected option's
 * label can't leave a stale reference behind in what gets saved/generated.
 * Also self-heals a falsy executionOptions.scheduler (e.g. a file saved
 * while it was blank, see ExecutionOptionsEditor, whose dropdown defaults
 * its *displayed* value to "BUILTIN" without ever correcting a genuinely
 * empty stored one, since Cancel is a no-op) back to a valid default.
 * Without this, debasher_exec/debasher_status get "--sched ''" and fail
 * with "Error: is not a valid scheduler" even though the UI appears to
 * show "BUILTIN" selected.
 */
export function normalizeProgram(source: Program): Program {

  const normalized = normalizeConnectedOptionValues(source);

  return normalized.executionOptions.scheduler
    ? normalized
    : {
        ...normalized,
        executionOptions: {
          ...normalized.executionOptions,
          scheduler: DEFAULT_SCHEDULER,
        },
      };

}

/**
 * Strips groupSource from every process and sequential process of the given
 * groups, which are then generated one by one. A process added with another
 * program ("Add program") is re-declared, unmodified, by add_debasher_program
 * from its source module, so an edit of its definition, or of an edge that
 * targets it, would be overwritten once generated: the caller frees its whole
 * group first.
 */
export function dissolveGroups(source: Program, groupIds: Set<string>): Program {

  if (groupIds.size === 0) {
    return source;
  }

  const inGroup = (groupId?: string) => groupId !== undefined && groupIds.has(groupId);

  return {
    ...source,
    processes: source.processes.map(process =>
      inGroup(process.groupSource?.groupId) ? { ...process, groupSource: undefined } : process
    ),
    seqProcesses: (source.seqProcesses ?? []).map(seqProcess =>
      inGroup(seqProcess.groupSource?.groupId) ? { ...seqProcess, groupSource: undefined } : seqProcess
    ),
  };

}

// The groups that an edit would dissolve, by groupId, each with the name of
// the program it was added from.
export type TouchedGroups = Map<string, string>;

/**
 * The groups of the given processes: those that an edit of their
 * definition, or of an edge that targets one of them, dissolves. Moving a
 * process touches no group, nor does connecting an output of a grouped
 * process to a process outside the group, since that connection lives in
 * the target's own generated function.
 */
function groupsOfProcesses(program: Program, processIds: Iterable<string>): TouchedGroups {

  const ids = new Set(processIds);
  const groups: TouchedGroups = new Map();

  for (const process of program.processes) {
    if (ids.has(process.id) && process.groupSource) {
      groups.set(process.groupSource.groupId, process.groupSource.programName);
    }
  }

  return groups;

}

// The groups of the edges' targets (see groupsOfProcesses).
function groupsOfEdgeTargets(program: Program, edgeIds: Iterable<string>): TouchedGroups {
  const ids = new Set(edgeIds);
  return groupsOfProcesses(
    program,
    program.edges.filter(edge => ids.has(edge.id)).map(edge => edge.targetProcessId)
  );
}

/**
 * The groups that replacing the sequential processes with the given ones
 * dissolves: those of a grouped sequential process that the replacement
 * changes or leaves out.
 */
function groupsOfChangedSeqProcesses(program: Program, seqProcesses: SeqProcess[]): TouchedGroups {

  const newById = new Map(seqProcesses.map(seqProcess => [seqProcess.id, seqProcess]));
  const groups: TouchedGroups = new Map();

  for (const old of program.seqProcesses) {
    if (!old.groupSource) {
      continue;
    }
    const changed = newById.get(old.id);
    if (!changed || JSON.stringify(changed) !== JSON.stringify(old)) {
      groups.set(old.groupSource.groupId, old.groupSource.programName);
    }
  }

  return groups;

}

// The fields of the program itself that an edit sets as a whole.
export type ProgramFields = Partial<Pick<
  Program,
  "name" | "description" | "preamble" | "sharedDirs" | "outputDir" | "executionOptions" | "programOptions"
>>;

export function setProgramFields(program: Program, changes: ProgramFields): Program {
  return { ...program, ...changes };
}

export function setEnvVar(program: Program, name: string, value: string): Program {
  return { ...program, envVars: { ...program.envVars, [name]: value } };
}

export function addProcess(program: Program, process: ProgramProcess): Program {
  return { ...program, processes: [...program.processes, process] };
}

// Removes the process with the edges left dangling by it.
export function removeProcess(program: Program, processId: string): Program {
  return {
    ...program,
    processes: program.processes.filter(process => process.id !== processId),
    edges: program.edges.filter(
      edge => edge.sourceProcessId !== processId && edge.targetProcessId !== processId
    ),
  };
}

function mapProcess(
  program: Program,
  processId: string,
  edit: (process: ProgramProcess) => ProgramProcess
): Program {
  return {
    ...program,
    processes: program.processes.map(process =>
      process.id === processId ? edit(process) : process
    ),
  };
}

export type ProcessChanges = Partial<Omit<ProgramProcess, "id">>;

export function updateProcess(program: Program, processId: string, changes: ProcessChanges): Program {
  return mapProcess(program, processId, process => ({ ...process, ...changes }));
}

export function addOption(program: Program, processId: string, option: ProgramOption): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: [...process.options, option],
  }));
}

export type OptionChanges = Partial<Omit<ProgramOption, "id">>;

export function updateOption(
  program: Program,
  processId: string,
  optionId: string,
  changes: OptionChanges
): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: process.options.map(option =>
      option.id === optionId ? { ...option, ...changes } : option
    ),
  }));
}

export function removeOption(program: Program, processId: string, optionId: string): Program {
  return mapProcess(program, processId, process => ({
    ...process,
    options: process.options.filter(option => option.id !== optionId),
  }));
}

/**
 * Adds the edge and gives its target option the reference to its source.
 * A "shared_dir" source's channel/value already fully determines its
 * resolved path, so connecting it into a plain target promotes that target
 * into a matching "shared_dir" option too, instead of the usual
 * "[proc;option]" sentinel, so a second connection from another writer of
 * the same directory validates against an already-tagged, matching target
 * (see isValidEdge) and both keep generating the same compact
 * get_absolute_shdirname-based code (see script_generation.py's shared_dir
 * branch) rather than one becoming a define_opt_from_proc_out reference to
 * this specific source.
 */
export function connect(program: Program, edge: ProgramEdge): Program {

  const sourceProcess = program.processes.find(
    process => process.id === edge.sourceProcessId
  );

  const sourceOption = sourceProcess?.options.find(
    o => o.id === edge.sourceOptionId
  );

  const connected = sourceProcess && sourceOption
    ? updateOption(
        program,
        edge.targetProcessId,
        edge.targetOptionId,
        sourceOption.channel === "shared_dir"
          ? { channel: "shared_dir", value: sourceOption.value }
          : { value: buildConnectionSentinel(sourceProcess.name, sourceOption.label) }
      )
    : program;

  return { ...connected, edges: [...connected.edges, edge] };

}

/**
 * Removes the edge and clears the value of its target option, except for a
 * "shared_dir" target, whose declared directory name is independent of any
 * connection.
 */
export function disconnect(program: Program, edgeId: string): Program {

  const removedEdge = program.edges.find(e => e.id === edgeId);

  const targetOption = removedEdge && program.processes
    .find(process => process.id === removedEdge.targetProcessId)
    ?.options.find(o => o.id === removedEdge.targetOptionId);

  const disconnected = removedEdge && targetOption?.channel !== "shared_dir"
    ? updateOption(program, removedEdge.targetProcessId, removedEdge.targetOptionId, { value: "" })
    : program;

  return { ...disconnected, edges: disconnected.edges.filter(e => e.id !== edgeId) };

}

// Matches engine/debasher_lib.sh's DEBASHER_MOD_DIR_SEP.
const MOD_DIR_SEP = ":";

/**
 * Why "Add program" cannot bring `loaded` into `program`, or null if it can.
 * Only a program of the same type is added, a program has at most one
 * Supervisor, and no process or sequential process of `loaded` may have the
 * name of one of `program` (a process and a sequential process share one set
 * of names, in the engine as here): the names can't be deduped by renaming,
 * since add_debasher_program only knows the source module's own original
 * names.
 */
export function mergeRefusal(program: Program, loaded: Program): string | null {

  if (loaded.programType !== program.programType) {
    return (
      `Cannot add program "${loaded.name}": it is a ${loaded.programType} ` +
      `program, and this one is a ${program.programType} program. "Add ` +
      `program" brings in only a program of the same type.`
    );
  }

  if (
    program.programType === "resident" &&
    hasSupervisor(program.processes) &&
    hasSupervisor(loaded.processes)
  ) {
    return (
      `Cannot add program "${loaded.name}": it has a Supervisor, and this ` +
      `program already has one. A program has at most one Supervisor.`
    );
  }

  const existingNames = new Set(
    [...program.processes, ...program.seqProcesses].map(member => member.name.toLowerCase())
  );
  const collisionName = [...loaded.processes, ...(loaded.seqProcesses ?? [])].find(member =>
    existingNames.has(member.name.toLowerCase())
  )?.name;

  if (collisionName) {
    return (
      `Cannot add program "${loaded.name}": it has a process or sequential ` +
      `process named "${collisionName}", whose name already exists in this ` +
      `program. Rename the conflicting one (in either program) and try again.`
    );
  }

  return null;

}

// What "Add program" brings into a program (see prepareMerge and addGroup).
export interface MergedGroup {

  processes: ProgramProcess[];

  seqProcesses: SeqProcess[];

  edges: ProgramEdge[];

  // The directory to add to DEBASHER_MOD_DIR, so that the engine finds the
  // module of the group, or null when nothing is loaded from it.
  modDir: string | null;

}

/**
 * The copies of the processes, sequential processes and edges of `loaded`
 * that "Add program" brings into `program`, from the directory `sourceDir`,
 * with new ids from `newId`. In a general program they all form one group,
 * tagged with the same GroupSource, so that script generation emits a single
 * add_debasher_program call for them while the group stays intact. A
 * resident program is merged process by process, never as a group, and
 * loads nothing from where they came from: a module added with
 * add_debasher_program would carry its own Supervisor wiring, while the
 * wiring of the whole program has to be derived again with the new nodes.
 * Names are kept exactly as in `loaded` (see mergeRefusal).
 */
export function prepareMerge(
  program: Program,
  loaded: Program,
  sourceDir: string,
  newId: () => string
): MergedGroup {

  const isResident = program.programType === "resident";
  const loadedSeqProcesses = loaded.seqProcesses ?? [];

  const groupSource: GroupSource | undefined = isResident
    ? undefined
    : {
        programName: loaded.name,
        groupId: newId(),
        groupSize: loaded.processes.length + loadedSeqProcesses.length,
        sourceDir,
      };

  // Places the merged batch to the right of whatever's already on the
  // canvas, preserving the relative layout its processes had in `loaded`:
  // there's no bounding-box UI to keep in sync (see ProcessNode's per-group
  // color instead), just a one-off offset at merge time.
  const currentMaxX = program.processes.reduce(
    (max, process) => Math.max(max, process.position.x),
    0
  );

  const loadedMinX = loaded.processes.reduce(
    (min, process) => Math.min(min, process.position.x),
    Infinity
  );

  const offsetX = loadedMinX === Infinity ? 0 : currentMaxX + 250 - loadedMinX;

  const idMap = new Map<string, string>();

  const processes = loaded.processes.map(process => {
    const id = newId();
    idMap.set(process.id, id);
    return {
      ...process,
      id,
      position: { x: process.position.x + offsetX, y: process.position.y },
      groupSource,
    };
  });

  // A resident program has no sequential processes.
  const seqProcesses = loadedSeqProcesses.map(seqProcess => ({
    ...seqProcess,
    id: newId(),
    groupSource,
  }));

  const edges = loaded.edges.map(edge => ({
    ...edge,
    id: newId(),
    sourceProcessId: idMap.get(edge.sourceProcessId) ?? edge.sourceProcessId,
    targetProcessId: idMap.get(edge.targetProcessId) ?? edge.targetProcessId,
  }));

  return { processes, seqProcesses, edges, modDir: isResident ? null : sourceDir };

}

// Adds what prepareMerge made, and its directory to DEBASHER_MOD_DIR unless
// it is there already.
export function addGroup(program: Program, group: MergedGroup): Program {

  const modDirEntries = (program.envVars.DEBASHER_MOD_DIR ?? "")
    .split(MOD_DIR_SEP)
    .map(entry => entry.trim())
    .filter(Boolean);

  const envVars = group.modDir === null || modDirEntries.includes(group.modDir)
    ? program.envVars
    : {
        ...program.envVars,
        DEBASHER_MOD_DIR: [...modDirEntries, group.modDir].join(MOD_DIR_SEP),
      };

  return {
    ...program,
    processes: [...program.processes, ...group.processes],
    seqProcesses: [...program.seqProcesses, ...group.seqProcesses],
    edges: [...program.edges, ...group.edges],
    envVars,
  };

}

// One edit of a program as plain data, so that an edit can be built in one
// place and applied in another (the editor, a tool that edits a program
// outside the browser, a proposal shown before it is accepted), and that a
// list of them can be applied as one. Everything an edit needs is in it,
// the ids of new elements included.
export type EditOp =
  | { op: "setProgramFields"; changes: ProgramFields }
  | { op: "setEnvVar"; name: string; value: string }
  | { op: "addProcess"; process: ProgramProcess }
  | { op: "removeProcess"; processId: string }
  | { op: "moveProcess"; processId: string; position: Position }
  | { op: "updateProcess"; processId: string; changes: ProcessChanges }
  | { op: "addOption"; processId: string; option: ProgramOption }
  | { op: "updateOption"; processId: string; optionId: string; changes: OptionChanges }
  | { op: "removeOption"; processId: string; optionId: string }
  | { op: "connect"; edge: ProgramEdge }
  | { op: "disconnect"; edgeId: string }
  | { op: "setSeqProcesses"; seqProcesses: SeqProcess[] }
  | { op: "addGroup"; group: MergedGroup };

// Applies one edit, without normalizeProgram (see applyEdits).
export function applyEdit(program: Program, edit: EditOp): Program {
  switch (edit.op) {
    case "setProgramFields":
      return setProgramFields(program, edit.changes);
    case "setEnvVar":
      return setEnvVar(program, edit.name, edit.value);
    case "addProcess":
      return addProcess(program, edit.process);
    case "removeProcess":
      return removeProcess(program, edit.processId);
    case "moveProcess":
      return updateProcess(program, edit.processId, { position: edit.position });
    case "updateProcess":
      return updateProcess(program, edit.processId, edit.changes);
    case "addOption":
      return addOption(program, edit.processId, edit.option);
    case "updateOption":
      return updateOption(program, edit.processId, edit.optionId, edit.changes);
    case "removeOption":
      return removeOption(program, edit.processId, edit.optionId);
    case "connect":
      return connect(program, edit.edge);
    case "disconnect":
      return disconnect(program, edit.edgeId);
    case "setSeqProcesses":
      return { ...program, seqProcesses: edit.seqProcesses };
    case "addGroup":
      return addGroup(program, edit.group);
  }
}

// Applies the edits one after another, then normalizeProgram once. This
// does not dissolve the groups they touch (see groupsTouchedBy).
export function applyEdits(program: Program, edits: EditOp[]): Program {
  return normalizeProgram(edits.reduce((edited, edit) => applyEdit(edited, edit), program));
}

/**
 * The groups that the edits touch in `program`, which have to be dissolved
 * (see dissolveGroups) before they are applied. An edit touches the group of
 * a process whose definition it changes, of a process it removes, and of the
 * target of an edge it adds or removes, since a connected option's
 * define_opt_from_proc_out call lives in the target's own generated function
 * (see api/script_generation.py's _option_definition_line). Replacing the
 * sequential processes touches the groups of those it changes or leaves out.
 * Moving a process, editing the program's own fields and adding processes or
 * a group touch none.
 */
export function groupsTouchedBy(program: Program, edits: EditOp[]): TouchedGroups {

  const groups: TouchedGroups = new Map();

  for (const edit of edits) {

    const touched = (() => {
      switch (edit.op) {
        case "removeProcess":
        case "updateProcess":
        case "addOption":
        case "updateOption":
        case "removeOption":
          return groupsOfProcesses(program, [edit.processId]);
        case "connect":
          return groupsOfProcesses(program, [edit.edge.targetProcessId]);
        case "disconnect":
          return groupsOfEdgeTargets(program, [edit.edgeId]);
        case "setSeqProcesses":
          return groupsOfChangedSeqProcesses(program, edit.seqProcesses);
        case "setProgramFields":
        case "setEnvVar":
        case "addProcess":
        case "moveProcess":
        case "addGroup":
          return new Map<string, string>();
      }
    })();

    touched.forEach((programName, groupId) => groups.set(groupId, programName));

  }

  return groups;

}
