"""
debasher_compare_opts.py

Compare two workflow options files (as produced by the workflow
manager before execution) and report, per process, whether it is new,
removed, changed (parameters differ) or unchanged.

Options file format, one process per line:

    PROCESS: <name> ; OPTIONS: <flag> <value> [<flag> <value> ...]

Array processes give one set of options per array element, separated
by "|||":

    PROCESS: <name> ; OPTIONS: <opts elem 0> ||| <opts elem 1> ||| ...

Design notes (see accompanying discussion):
  - All options are compared as-is (no distinction between "user"
    parameters and I/O paths generated by the framework).
  - Comparison is done on parsed flag -> value dictionaries, not on
    raw strings, so whitespace and flag ordering do not matter.
  - Array processes are compared as a whole: any difference in the
    number of elements, or in any single element, marks the whole
    process as changed (no per-element granularity).
  - Array elements are matched by the "-id" flag when present in all
    elements, falling back to positional order otherwise.

Output is designed to be easily consumed from bash: by default each
selected category is printed as one process name per line, with no
extra decoration. Use --human for a readable summary instead.
"""

import argparse
import sys
from typing import Dict, List

Instance = Dict[str, str]
Opts = Dict[str, List[Instance]]


class OptsParseError(Exception):
    pass


def parse_options(options_str: str) -> Instance:
    """Parse a string of '-flag value -flag value ...' into a dict.

    A flag with no following value (or followed by another flag) is
    stored with an empty string value. Note: this simple tokenizer
    assumes option values never start with '-' (e.g. negative numbers
    are not supported as values); that is a known limitation.
    """
    tokens = options_str.split()
    result: Instance = {}
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if not tok.startswith("-"):
            raise OptsParseError(f"unexpected token '{tok}', expected a flag starting with '-'")
        if i + 1 < len(tokens) and not tokens[i + 1].startswith("-"):
            result[tok] = tokens[i + 1]
            i += 2
        else:
            result[tok] = ""
            i += 1
    return result


def parse_opts_file(path: str) -> Opts:
    """Parse a whole options file into {process_name: [instance, ...]}."""
    opts: Opts = {}
    with open(path, "r", encoding="utf-8") as f:
        for lineno, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line:
                continue
            if "PROCESS:" not in line or "OPTIONS:" not in line:
                raise OptsParseError(
                    f"{path}:{lineno}: malformed line, expected 'PROCESS: ... ; OPTIONS: ...'"
                )
            process_part, _, options_part = line.partition(";")
            process_part = process_part.strip()
            options_part = options_part.strip()
            if not process_part.startswith("PROCESS:"):
                raise OptsParseError(f"{path}:{lineno}: missing 'PROCESS:' before ';'")
            if not options_part.startswith("OPTIONS:"):
                raise OptsParseError(f"{path}:{lineno}: missing 'OPTIONS:' after ';'")

            name = process_part[len("PROCESS:"):].strip()
            if not name:
                raise OptsParseError(f"{path}:{lineno}: empty process name")
            if name in opts:
                raise OptsParseError(f"{path}:{lineno}: duplicate process '{name}'")

            options_str = options_part[len("OPTIONS:"):].strip()
            element_strs = [chunk.strip() for chunk in options_str.split("|||")]
            instances = [parse_options(chunk) for chunk in element_strs]
            opts[name] = instances
    return opts


def instance_key(instance: Instance, index: int) -> str:
    """Stable key used to match array elements across two options files."""
    return instance.get("-id", f"__pos{index}__")


def instances_differ(old_instances: List[Instance], new_instances: List[Instance]) -> bool:
    """Return True if a process's set of instances differs between the two
    options files.

    Works uniformly for scalar processes (a single instance) and array
    processes (multiple instances): any difference in element count or
    in any matched element's content marks the whole process as changed.
    """
    if len(old_instances) != len(new_instances):
        return True

    old_map = {instance_key(inst, i): inst for i, inst in enumerate(old_instances)}
    new_map = {instance_key(inst, i): inst for i, inst in enumerate(new_instances)}

    if set(old_map.keys()) != set(new_map.keys()):
        return True

    return any(old_map[key] != new_map[key] for key in old_map)


def compare_opts(old_opts: Opts, new_opts: Opts):
    old_names = set(old_opts.keys())
    new_names = set(new_opts.keys())

    new_procs = sorted(new_names - old_names)
    removed_procs = sorted(old_names - new_names)
    common_procs = sorted(old_names & new_names)

    changed_procs = []
    unchanged_procs = []
    for name in common_procs:
        if instances_differ(old_opts[name], new_opts[name]):
            changed_procs.append(name)
        else:
            unchanged_procs.append(name)

    return {
        "new": new_procs,
        "removed": removed_procs,
        "changed": changed_procs,
        "unchanged": unchanged_procs,
    }


def print_plain(names: List[str]) -> None:
    for name in names:
        print(name)


def print_human_report(result) -> None:
    def section(title, items):
        if not items:
            return
        print(f"{title} ({len(items)}):")
        for item in items:
            print(f"  - {item}")
        print()

    section("Changed processes (parameters modified)", result["changed"])
    section("New processes", result["new"])
    section("Removed processes", result["removed"])
    section("Unchanged processes", result["unchanged"])


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Compare two workflow options files and report process-level differences."
    )
    parser.add_argument("old_opts", help="path to the previous options file")
    parser.add_argument("new_opts", help="path to the new options file")

    parser.add_argument("--changed", action="store_true", help="list processes with modified parameters")
    parser.add_argument("--new", action="store_true", dest="show_new", help="list new processes")
    parser.add_argument("--removed", action="store_true", help="list removed processes")
    parser.add_argument("--unchanged", action="store_true", help="list unchanged processes")
    parser.add_argument(
        "--to-rerun",
        action="store_true",
        help="list processes to rerun (new + changed); default when no other category flag is given",
    )
    parser.add_argument("--human", action="store_true", help="print a human-readable summary instead")

    return parser


def main() -> int:
    args = build_arg_parser().parse_args()

    try:
        old_opts = parse_opts_file(args.old_opts)
        new_opts = parse_opts_file(args.new_opts)
    except (OptsParseError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    result = compare_opts(old_opts, new_opts)

    category_flags_given = any(
        [args.changed, args.show_new, args.removed, args.unchanged, args.to_rerun]
    )
    if not category_flags_given:
        args.to_rerun = True

    if args.human:
        print_human_report(result)
    else:
        if args.changed:
            print_plain(result["changed"])
        if args.show_new:
            print_plain(result["new"])
        if args.removed:
            print_plain(result["removed"])
        if args.unchanged:
            print_plain(result["unchanged"])
        if args.to_rerun:
            to_rerun = sorted(set(result["new"]) | set(result["changed"]))
            print_plain(to_rerun)

    return 0


if __name__ == "__main__":
    sys.exit(main())
