# DeBasher package
# Copyright (C) 2019-2024 Daniel Ortiz-Mart\'inez
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

# *- bash -*

#############
# CONSTANTS #
#############

# STRING HANDLING
DEBASHER_NOFILE="_NONE_"
DEBASHER_ATTR_NOT_FOUND="_ATTR_NOT_FOUND_"
DEBASHER_OPT_NOT_FOUND="_OPT_NOT_FOUND_"
DEBASHER_DEP_NOT_FOUND="_DEP_NOT_FOUND_"
DEBASHER_FUNCT_NOT_FOUND="_FUNCT_NOT_FOUND_"
DEBASHER_VAR_NOT_FOUND="_VAR_NOT_FOUND_"
DEBASHER_VOID_VALUE="_VOID_VALUE_"
DEBASHER_GENERAL_OPT_CATEGORY="GENERAL"
DEBASHER_SPACE_SUBSTITUTE="__SPACE_SUBSTITUTE__"
DEBASHER_ARG_SEP="<_ARG_SEP_>"
DEBASHER_ARRAY_TASK_SEP=" ||| "
DEBASHER_PROCESSDEPS_SPEC="processdeps"
DEBASHER_ATTEMPT_SEP=","
DEBASHER_PROCESS_PLUS_DEPTYPE_SEP=":"
DEBASHER_PROCESSDEPS_SEP_COMMA=","
DEBASHER_PROCESSDEPS_SEP_INTERR="?"
DEBASHER_ASSOC_ARRAY_ELEM_SEP="__ELEMSEP__"
DEBASHER_ASSOC_ARRAY_KEY_LEN="__LEN__"
DEBASHER_ASSOC_ARRAY_PROC_SEP="__PROCSEP__"
DEBASHER_DEBASHER_MOD_DIR_SEP=":"
DEBASHER_DEBASHER_YML_DIR_SEP=":"
DEBASHER_PROCESS_METHOD_SEP="_"
DEBASHER_MODULE_METHOD_SEP="_"
DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP="|||"
DEBASHER_LEGACY_PROCSPECS_SEP=" "
DEBASHER_PROCSPECS_SEP=";"
DEBASHER_VALUE_DESCRIPTOR_NAME_PREFIX=".__VAL_DESCRIPTOR__"
DEBASHER_PROC_OUT_OPT_DESCRIPTOR_NAME_PREFIX="__PROC_OUT_OPT_DESCRIPTOR__"
DEBASHER_SCHED_OPTS_DIRNAME=".sched_opts"
DEBASHER_SCHED_OPTS_FNAME_FOR_PROCESS_PREFIX="sched_opts_"
DEBASHER_SHDIR_MODULE_OWNER="__SHDIR_MODULE_OWNER__"
DEBASHER_OPTLIST_VARNAME_SUFFIX="optlist"

# PROCESS TYPES
DEBASHER_REGULAR_PROCESS_TYPE=1
DEBASHER_HEREDOC_PROCESS_TYPE=2
DEBASHER_ALIAS_PROCESS_TYPE=3
DEBASHER_EXT_ALIAS_PROCESS_TYPE=4

# HEREDOC PROCESSES RELATED VARIABLES
DEBASHER_PY_VARNAME_SUFFIX="py"
DEBASHER_PY_END_OF_OPTIONS_MARKER=""
DEBASHER_R_VARNAME_SUFFIX="r"
DEBASHER_R_END_OF_OPTIONS_MARKER="--"
DEBASHER_PL_VARNAME_SUFFIX="perl"
DEBASHER_PL_END_OF_OPTIONS_MARKER="--"
DEBASHER_GROOVY_VARNAME_SUFFIX="groovy"
DEBASHER_GROOVY_END_OF_OPTIONS_MARKER="--"
DEBASHER_HEREDOC_SUFFIXES=(
    "${DEBASHER_PY_VARNAME_SUFFIX}"
    "${DEBASHER_R_VARNAME_SUFFIX}"
    "${DEBASHER_PL_VARNAME_SUFFIX}"
    "${DEBASHER_GROOVY_VARNAME_SUFFIX}"
)

# INVALID IDENTIFIERS
DEBASHER_INVALID_SID="_INVALID_SID_"
DEBASHER_INVALID_JID="_INVALID_JID_"
DEBASHER_INVALID_PID="_INVALID_PID_"
DEBASHER_INVALID_ARRAY_TID="_INVALID_ARRAY_TID_"

# PROCESS STATUSES AND EXIT CODES
DEBASHER_FINISHED_PROCESS_STATUS="FINISHED"
DEBASHER_FINISHED_PROCESS_EXIT_CODE=0
DEBASHER_INPROGRESS_PROCESS_STATUS="IN-PROGRESS"
DEBASHER_INPROGRESS_PROCESS_EXIT_CODE=1
DEBASHER_UNFINISHED_BUT_RUNNABLE_PROCESS_STATUS="UNFINISHED_BUT_RUNNABLE"
DEBASHER_UNFINISHED_BUT_RUNNABLE_PROCESS_EXIT_CODE=2
DEBASHER_UNFINISHED_PROCESS_STATUS="UNFINISHED"
DEBASHER_UNFINISHED_PROCESS_EXIT_CODE=3
DEBASHER_TODO_PROCESS_STATUS="TO-DO"
DEBASHER_TODO_PROCESS_EXIT_CODE=4

# PROCESS METHOD NAMES
DEBASHER_PROCESS_METHOD_NAME_DOCUMENT="${DEBASHER_PROCESS_METHOD_SEP}document"
DEBASHER_PROCESS_METHOD_NAME_RESET_OUTFILES="${DEBASHER_PROCESS_METHOD_SEP}reset_outfiles"
DEBASHER_PROCESS_METHOD_NAME_EXEC=""
DEBASHER_PROCESS_METHOD_NAME_POST="${DEBASHER_PROCESS_METHOD_SEP}post"
DEBASHER_PROCESS_METHOD_NAME_OUTDIR="${DEBASHER_PROCESS_METHOD_SEP}outdir_basename"
DEBASHER_PROCESS_METHOD_NAME_EXPLAIN_CMDLINE_OPTS="${DEBASHER_PROCESS_METHOD_SEP}explain_cmdline_opts"
DEBASHER_PROCESS_METHOD_NAME_DEFINE_OPTS="${DEBASHER_PROCESS_METHOD_SEP}define_opts"
DEBASHER_PROCESS_METHOD_NAME_DEFINE_OPT_DEPS="${DEBASHER_PROCESS_METHOD_SEP}define_opt_deps"
DEBASHER_PROCESS_METHOD_NAME_GENERATE_OPTS_SIZE="${DEBASHER_PROCESS_METHOD_SEP}generate_opts_size"
DEBASHER_PROCESS_METHOD_NAME_GENERATE_OPTS="${DEBASHER_PROCESS_METHOD_SEP}generate_opts"
DEBASHER_PROCESS_METHOD_NAME_SKIP="${DEBASHER_PROCESS_METHOD_SEP}skip"
DEBASHER_PROCESS_METHOD_NAME_CONDA_ENVS="${DEBASHER_PROCESS_METHOD_SEP}conda_envs"
DEBASHER_PROCESS_METHOD_NAME_DOCKER_IMGS="${DEBASHER_PROCESS_METHOD_SEP}docker_imgs"

# ARRAY OF ALL METHOD NAMES
DEBASHER_PROCESS_METHODS=(
    "${DEBASHER_PROCESS_METHOD_NAME_DOCUMENT}"
    "${DEBASHER_PROCESS_METHOD_NAME_RESET_OUTFILES}"
    "${DEBASHER_PROCESS_METHOD_NAME_EXEC}"
    "${DEBASHER_PROCESS_METHOD_NAME_POST}"
    "${DEBASHER_PROCESS_METHOD_NAME_OUTDIR}"
    "${DEBASHER_PROCESS_METHOD_NAME_EXPLAIN_CMDLINE_OPTS}"
    "${DEBASHER_PROCESS_METHOD_NAME_DEFINE_OPTS}"
    "${DEBASHER_PROCESS_METHOD_NAME_DEFINE_OPT_DEPS}"
    "${DEBASHER_PROCESS_METHOD_NAME_GENERATE_OPTS_SIZE}"
    "${DEBASHER_PROCESS_METHOD_NAME_GENERATE_OPTS}"
    "${DEBASHER_PROCESS_METHOD_NAME_SKIP}"
    "${DEBASHER_PROCESS_METHOD_NAME_CONDA_ENVS}"
    "${DEBASHER_PROCESS_METHOD_NAME_DOCKER_IMGS}"
)

# PROCESS VAR NAMES
DEBASHER_PROCESS_VARNAME_PYEXEC="${DEBASHER_PROCESS_METHOD_SEP}${DEBASHER_PY_VARNAME_SUFFIX}"
DEBASHER_PROCESS_VARNAME_REXEC="${DEBASHER_PROCESS_METHOD_SEP}${DEBASHER_R_VARNAME_SUFFIX}"
DEBASHER_PROCESS_VARNAME_PERLEXEC="${DEBASHER_PROCESS_METHOD_SEP}${DEBASHER_PL_VARNAME_SUFFIX}"
DEBASHER_PROCESS_VARNAME_GROOVYEXEC="${DEBASHER_PROCESS_METHOD_SEP}${DEBASHER_GROOVY_VARNAME_SUFFIX}"

# MODULE METHOD NAMES
DEBASHER_MODULE_METHOD_NAME_DOCUMENT="${DEBASHER_MODULE_METHOD_SEP}document"
DEBASHER_MODULE_METHOD_NAME_SHRDIRS="${DEBASHER_MODULE_METHOD_SEP}shared_dirs"
DEBASHER_MODULE_METHOD_NAME_PROGRAM="${DEBASHER_MODULE_METHOD_SEP}program"

# FIFO-RELATED CONSTANTS
DEBASHER_EXTERNAL_FIFO_USER="__EXTERNAL__${DEBASHER_ASSOC_ARRAY_ELEM_SEP}0"

# FLOW-BASED PROGRAMMING CONSTANTS
DEBASHER_SHUTDOWN_TOKEN="__SHUTDOWN_TOKEN__"

# REEXEC REASONS
DEBASHER_FIFO_REEXEC_REASON="fifo"
DEBASHER_FORCED_REEXEC_REASON="forced"
DEBASHER_OUTDATED_CODE_REEXEC_REASON="outdated_code"
DEBASHER_DEPS_REEXEC_REASON="dependencies"

# PROCESS DEPENDENCIES
DEBASHER_NONE_PROCESSDEP_TYPE="none"
DEBASHER_AFTER_PROCESSDEP_TYPE="after"
DEBASHER_AFTEROK_PROCESSDEP_TYPE="afterok"
DEBASHER_AFTERNOTOK_PROCESSDEP_TYPE="afternotok"
DEBASHER_AFTERANY_PROCESSDEP_TYPE="afterany"
DEBASHER_AFTERCORR_PROCESSDEP_TYPE="aftercorr"

# OPTION RELATED CONSTANTS
DEBASHER_OPT_FILE_LINES_PER_BLOCK=10000

# ASSOCIATIVE ARRAY TO STORE PRIORITY OF PROCESS DEPENDENCIES
declare -A DEBASHER_PROCESSDEP_PRIORITY
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_NONE_PROCESSDEP_TYPE}]=0
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_AFTERCORR_PROCESSDEP_TYPE}]=1
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_AFTER_PROCESSDEP_TYPE}]=2
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_AFTERANY_PROCESSDEP_TYPE}]=3
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_AFTEROK_PROCESSDEP_TYPE}]=4
DEBASHER_PROCESSDEP_PRIORITY[${DEBASHER_AFTERNOTOK_PROCESSDEP_TYPE}]=4

# PROCESS STATISTICS
DEBASHER_UNKNOWN_ELAPSED_TIME_FOR_PROCESS="UNKNOWN"

# PROGRAM STATUSES
#
# NOTE: exit code 1 is reserved for general errors when executing
# pipe_status
DEBASHER_PROGRAM_FINISHED_EXIT_CODE=0
DEBASHER_PROGRAM_IN_PROGRESS_EXIT_CODE=2
DEBASHER_PROGRAM_UNFINISHED_EXIT_CODE=3

# DEBASHER STATUS
DEBASHER_DEBASHER_SCHEDULER=""
DEBASHER_BUILTIN_SCHEDULER="BUILTIN"
DEBASHER_SLURM_SCHEDULER="SLURM"

# SLURM-RELATED CONSTANTS
DEBASHER_FIRST_SLURM_VERSION_WITH_AFTERCORR="16.05"

# FILE EXTENSIONS
DEBASHER_STDOUT_FEXT="stdout"
DEBASHER_SCHED_LOG_FEXT="sched_out"
DEBASHER_FINISHED_PROCESS_FEXT="finished"
DEBASHER_PROCESSID_FEXT="id"
DEBASHER_ARRAY_TASKID_FEXT="id"
DEBASHER_SLURM_EXEC_ATTEMPT_FEXT_STRING="__attempt"
DEBASHER_PROCSPEC_FEXT="procspec"
DEBASHER_PRGOPTS_FEXT="opts"
DEBASHER_PRGOPTS_EXHAUSTIVE_FEXT="opts_exh"
DEBASHER_FIFOS_FEXT="fifos"
DEBASHER_GRAPHS_FEXT="dot"
DEBASHER_SCHED_SCRIPT_INPUT_FEXT="opts"
DEBASHER_BASH_FEXT="sh"
DEBASHER_PYTHON_FEXT="py"
DEBASHER_PERL_FEXT="pl"
DEBASHER_R_FEXT="R"
DEBASHER_GROOVY_FEXT="groovy"

# FILE NAMES
DEBASHER_PPEXEC_INITIAL_PROCSPEC_BASENAME=".initial_program.${DEBASHER_PROCSPEC_FEXT}"
DEBASHER_PPEXEC_PRG_PREF="program"
DEBASHER_PRG_COMMAND_LINE_BASENAME="command_line.sh"
DEBASHER_DEBLIB_VARS_AND_FUNCS_BASENAME=".deblib_vars_and_funcs.sh"
DEBASHER_MOD_VARS_AND_FUNCS_BASENAME=".mod_vars_and_funcs.sh"

# DIR_NAMES
DEBASHER_DEBASHER_EXEC_DIRNAME="__exec__"
DEBASHER_DEBASHER_GRAPHS_DIRNAME="__graphs__"
DEBASHER_DEBASHER_FIFOS_DIRNAME="__fifos__"
DEBASHER_DEBASHER_CONDA_DIRNAME=".conda"

# LOGGING CONSTANTS
DEBASHER_DEBASHER_LOG_ERROR_MSG_START="Error:"
DEBASHER_DEBASHER_LOG_WARNING_MSG_START="Warning:"
DEBASHER_DEBASHER_REEXEC_PROCESSES_WARNING="Warning: there are processes to be re-executed!"

####################
# GLOBAL VARIABLES #
####################

# Declare associative arrays to store help about program options
declare -A DEBASHER_PROGRAM_OPT_DESC
declare -A DEBASHER_PROGRAM_OPT_TYPE
declare -A DEBASHER_PROGRAM_OPT_REQ
declare -A DEBASHER_PROGRAM_OPT_CATEG
declare -A DEBASHER_PROGRAM_CATEG_MAP
declare -A DEBASHER_PROGRAM_OPT_PROCESS

# Declare array to store deserialized arguments
declare -a DEBASHER_DESERIALIZED_ARGS

# Declare associative array to memoize command line options
declare -A DEBASHER_MEMOIZED_OPTS

# Declare string variable to store last processed command line when
# memoizing options
declare DEBASHER_LAST_PROC_LINE_MEMOPTS=""

# Declare string used to indicate current process during option
# definition
declare DEBASHER_DEFINE_OPTS_CURRENT_PROCESS=""

# Declare array to save option lists for current process (an array is
# needed to support multiple process executions)
declare -a DEBASHER_CURRENT_PROCESS_OPT_LIST

# Declare associative array used to save lengths of option lists for all
# processes
declare -A DEBASHER_PROCESS_OPT_LIST_LEN

# Declare associative array used to store initial process specification
declare -A DEBASHER_INITIAL_PROCESS_SPEC

# Declare associative array used to map output values to processes
declare -A DEBASHER_OUT_VALUE_TO_PROCESSES

# Declare associative array used to store process dependencies
declare -A DEBASHER_PROCESS_DEPENDENCIES

# Declare variable storing whether all process dependencies where
# pre-specified in initial process specification
declare DEBASHER_ALL_PROCESS_DEPS_PRE_SPECIFIED

# Declare variable to store name of output directory
declare DEBASHER_PROGRAM_OUTDIR

# Declare array to store file names of loaded modules
declare -a DEBASHER_PROGRAM_MODULES

# Declare array to store a stack for the program files for each program
# function that is invoked
declare -a DEBASHER_PROGRAM_FUNC_FOR_MODULE_PFILE_STACK

# Declare associative array to store processes added to a program
declare -A DEBASHER_PROGRAM_PROCESSES

# Declare associative arrays to store name of shared directories
declare -A DEBASHER_PROGRAM_SHDIRS

# Declare associative arrays to store names of fifos
declare -A DEBASHER_PROGRAM_FIFOS

# Declare associative array to store users of fifos (The process
# defining the FIFO with debasher::define_fifo_opt becomes the owner)
declare -A DEBASHER_FIFO_USERS

# Declare general scheduler-related variables
declare DEBASHER_DEBASHER_SCHEDULER
declare -A DEBASHER_DEBASHER_REEXEC_PROCESSES
declare DEBASHER_DEBASHER_DEFAULT_NODES
declare DEBASHER_DEBASHER_ARRAY_TASK_NOTHROTTLE=0
declare DEBASHER_DEBASHER_DEFAULT_ARRAY_TASK_THROTTLE=${DEBASHER_DEBASHER_ARRAY_TASK_NOTHROTTLE}

# Declare SLURM scheduler-related variables
declare DEBASHER_AFTERCORR_PROCESSDEP_TYPE_AVAILABLE_IN_SLURM=0

# Declare associative array to store exit code for processes
declare -A DEBASHER_EXIT_CODE

######################
# INCLUDE BASH FILES #
######################

. "${debasher_libexecdir}"/debasher_lib_utils
. "${debasher_libexecdir}"/debasher_lib_programs
. "${debasher_libexecdir}"/debasher_lib_modules
. "${debasher_libexecdir}"/debasher_lib_process_spec
. "${debasher_libexecdir}"/debasher_lib_processes
. "${debasher_libexecdir}"/debasher_lib_opts
. "${debasher_libexecdir}"/debasher_lib_sched
. "${debasher_libexecdir}"/debasher_lib_conda
. "${debasher_libexecdir}"/debasher_lib_docker
