#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_sched_slurm.sh, the Slurm backend of
# the scheduler, run against the artifacts generated by engine/
# Makefile.am's suffix rule (not the .sh sources). sbatch and scontrol are
# replaced by fake commands, so no Slurm is needed.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    RM="$(command -v rm)"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # debasher_lib.sh declares these with a bare declare, local to setup()
    declare -g DEBASHER_ARRAY_TASK_NOTHROTTLE=0
    declare -g DEBASHER_SLURM_EXEC_ATTEMPT_FEXT_STRING="__attempt"
    declare -g DEBASHER_UNKNOWN_ELAPSED_TIME_FOR_PROCESS="UNKNOWN"
    declare -g DEBASHER_NOFILE="${DEBASHER_NOFILE:-_NOFILE_}"

    OUTDIR="${BATS_TEST_TMPDIR}/out"
    EXECDIR="${OUTDIR}/__exec__/proc"
    mkdir -p "${EXECDIR}"

    # Fake Slurm commands: sbatch prints a job id, scontrol prints what
    # FAKE_SCONTROL_OUTPUT holds and succeeds
    local bindir="${BATS_TEST_TMPDIR}/bin"
    mkdir -p "${bindir}"
    printf '#!/bin/bash\necho 123\n' > "${bindir}/sbatch"
    printf '#!/bin/bash\necho -n "${FAKE_SCONTROL_OUTPUT}"\n' > "${bindir}/scontrol"
    chmod +x "${bindir}/sbatch" "${bindir}/scontrol"
    SBATCH="${bindir}/sbatch"
    SCONTROL="${bindir}/scontrol"
}

# --- launching the jobs of a process ---------------------------------------

@test "_slurm_launch_preverif_job ignores what scontrol release prints" {
    export FAKE_SCONTROL_OUTPUT="scontrol: note: job released"
    local spec="proc cpus=1 mem=32 time=00:01:00"

    run debasher::_slurm_launch_preverif_job "${OUTDIR}" proc 1 "0" "${spec}" "100"
    [ "${status}" -eq 0 ]
    [ "${output}" = "123" ]
}

@test "_slurm_launch_verif_job reports why setting the per-task dependencies failed" {
    local spec="proc cpus=1 mem=32 time=00:01:00"
    debasher::_set_slurm_jobcorr_like_deps() {
        return 1
    }

    run debasher::_slurm_launch_verif_job "${OUTDIR}" proc 2 "0-1" "${spec}" "100"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"Error while launching verification job for process proc (debasher::_set_slurm_jobcorr_like_deps)"* ]]
}

# --- logs of the attempts ---------------------------------------------------

@test "_get_last_attempt_logf_slurm gives the log of the last attempt that ran" {
    local logf="${EXECDIR}/proc.sched_out"
    run debasher::_get_last_attempt_logf_slurm "${logf}"
    [ "${output}" = "${DEBASHER_NOFILE}" ]

    touch "${logf}"
    run debasher::_get_last_attempt_logf_slurm "${logf}"
    [ "${output}" = "${logf}" ]

    touch "${logf}__attempt2" "${logf}__attempt3"
    run debasher::_get_last_attempt_logf_slurm "${logf}"
    [ "${output}" = "${logf}__attempt3" ]
}

@test "_clean_process_files_slurm removes the logs of every attempt of a process" {
    touch "${EXECDIR}/proc.sched_out" "${EXECDIR}/proc.sched_out__attempt2" "${EXECDIR}/proc.id"

    debasher::_clean_process_files_slurm "${OUTDIR}" proc 1

    [ ! -e "${EXECDIR}/proc.sched_out" ]
    [ ! -e "${EXECDIR}/proc.sched_out__attempt2" ]
}

@test "_clean_process_files_slurm removes the logs of every attempt of a pending task of an array" {
    touch "${EXECDIR}/proc_1.sched_out" "${EXECDIR}/proc_1.sched_out__attempt2"
    touch "${EXECDIR}/proc_0.sched_out"
    debasher::_get_list_of_pending_tasks_in_array() {
        echo "1"
    }

    debasher::_clean_process_files_slurm "${OUTDIR}" proc 2

    [ ! -e "${EXECDIR}/proc_1.sched_out" ]
    [ ! -e "${EXECDIR}/proc_1.sched_out__attempt2" ]
    [ -e "${EXECDIR}/proc_0.sched_out" ]
}

# --- elapsed time -----------------------------------------------------------

@test "_elapsed_time_to_ms converts seconds with milliseconds and refuses anything else" {
    run debasher::_elapsed_time_to_ms "12.034"
    [ "${output}" = "12034" ]
    run debasher::_elapsed_time_to_ms "UNKNOWN"
    [ "${status}" -ne 0 ]
}

@test "_get_elapsed_time_for_array_process sums the times of the tasks" {
    debasher::_get_finished_array_task_indices() {
        echo "0 1"
    }
    fake_task_logf() {
        echo "log$3"
    }
    debasher::_get_elapsed_time_from_logfile() {
        case "$1" in
            log0) echo "1.500" ;;
            log1) echo "0.750" ;;
        esac
    }

    run debasher::_get_elapsed_time_for_array_process "${OUTDIR}" proc fake_task_logf
    [ "${status}" -eq 0 ]
    [ "${output}" = "2.250 : 0->1.500 ; 1->0.750 ;" ]
}

@test "_get_elapsed_time_for_array_process gives an unknown total when a task time is unknown" {
    debasher::_get_finished_array_task_indices() {
        echo "0 1"
    }
    fake_task_logf() {
        echo "log$3"
    }
    debasher::_get_elapsed_time_from_logfile() {
        case "$1" in
            log0) echo "1.500" ;;
            log1) echo "UNKNOWN" ;;
        esac
    }

    run debasher::_get_elapsed_time_for_array_process "${OUTDIR}" proc fake_task_logf
    [ "${output}" = "UNKNOWN : 0->1.500 ; 1->UNKNOWN ;" ]
}

@test "_get_elapsed_time_for_process_slurm computes the time of an array, whose markers carry the task index" {
    AWK="$(command -v awk)"
    declare -g DEBASHER_FINISHED_PROCESS_FEXT="${DEBASHER_FINISHED_PROCESS_FEXT:-finished}"
    echo "Finished task idx: 0 ; Total: 2" > "${EXECDIR}/proc_0.${DEBASHER_FINISHED_PROCESS_FEXT}"
    echo "Finished task idx: 1 ; Total: 2" > "${EXECDIR}/proc_1.${DEBASHER_FINISHED_PROCESS_FEXT}"
    debasher::_get_elapsed_time_for_array_process() {
        echo "array time of $2"
    }

    run debasher::_get_elapsed_time_for_process_slurm "${OUTDIR}" proc
    [ "${status}" -eq 0 ]
    [ "${output}" = "array time of proc" ]
}
