#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_opts.sh, run against the artifact
# generated by engine/Makefile.am's suffix rule (not the .sh source), so
# they exercise what actually ships. They cover the shared subdirectories
# that define_opt_from_shared_dir --subdir asks for: how the option is
# defined, and how a run creates them and removes from a subdivided shared
# directory what no option asks for.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # debasher_lib.sh declares its associative arrays at the top level of
    # a script; inside setup() a bare "declare" would be local to it, so
    # the ones these tests use are made global here. Their values are set
    # by init_program, from the test itself, since the local ones still
    # hide the global ones until setup() returns
    declare -gA DEBASHER_PROGRAM_SHDIRS DEBASHER_PROGRAM_SHSUBDIRS
    declare -gA DEBASHER_PROGRAM_PROCESSES DEBASHER_PROCESS_OPT_LIST_LEN
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES
    declare -g DEBASHER_PROGRAM_OUTDIR
}

# Makes the output directory of the run, with the shared directory "data"
# that a module declares
init_program() {
    MKDIR="$(command -v mkdir)"; RM="$(command -v rm)"
    FIND="$(command -v find)"; BASENAME="$(command -v basename)"
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${DEBASHER_PROGRAM_OUTDIR}/data"
    DEBASHER_PROGRAM_SHDIRS["data"]=${DEBASHER_SHDIR_MODULE_OWNER}
}

# Defines the options of an array process "writer" with one task for each
# subpath given, each with -outd in the shared subdirectory of "data"
# named by that subpath
define_writer_opts() {
    writer_define_opts()
    {
        local subpath
        for subpath in "$@"; do
            local optlist=""
            define_opt_from_shared_dir "-outd" "data" optlist --subdir "${subpath}" || return 1
            save_opt_list optlist
        done
    }
    # save_opt_list relies on lookups that return 1 in the ordinary case,
    # which bats's errexit would treat as a failure
    set +e
    writer_define_opts "$@"
    local status=$?
    set -e
    return "${status}"
}

# --- debasher::define_opt_from_shared_dir --------------------------------

@test "define_opt_from_shared_dir gives the path of the shared directory without --subdir, and registers nothing" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-datadir" "data" optlist
    [[ "${optlist}" == *"${DEBASHER_PROGRAM_OUTDIR}/data"* ]]
    [ "${#DEBASHER_PROGRAM_SHSUBDIRS[@]}" -eq 0 ]
}

@test "define_opt_from_shared_dir --subdir gives the path of the shared subdirectory and registers it, without creating it" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-outd" "data" optlist --subdir "sample1/bam"
    [[ "${optlist}" == *"${DEBASHER_PROGRAM_OUTDIR}/data/sample1/bam"* ]]
    [ "${DEBASHER_PROGRAM_SHSUBDIRS["data/sample1/bam"]}" = "data" ]
    [ ! -e "${DEBASHER_PROGRAM_OUTDIR}/data/sample1" ]
}

@test "define_opt_from_shared_dir --subdir refuses a subpath that does not stay below its shared directory" {
    init_program
    local subpath
    for subpath in "" "/abs" "a//b" "a/" "." "a/./b" ".." "a/../b"; do
        run debasher::define_opt_from_shared_dir "-outd" "data" optlist --subdir "${subpath}"
        [ "${status}" -ne 0 ]
    done
    [ "${#DEBASHER_PROGRAM_SHSUBDIRS[@]}" -eq 0 ]
}

@test "define_opt_from_shared_dir refuses an unknown flag and a --subdir with no subpath" {
    init_program
    run debasher::define_opt_from_shared_dir "-outd" "data" optlist --mirror
    [ "${status}" -ne 0 ]
    run debasher::define_opt_from_shared_dir "-outd" "data" optlist --subdir
    [ "${status}" -ne 0 ]
}

# --- debasher::_prepare_shared_subdirs -----------------------------------

@test "_prepare_shared_subdirs does nothing when no option asks for a shared subdirectory" {
    init_program
    touch "${DEBASHER_PROGRAM_OUTDIR}/data/keep.txt"
    debasher::_prepare_shared_subdirs 0
    [ -f "${DEBASHER_PROGRAM_OUTDIR}/data/keep.txt" ]
}

@test "_prepare_shared_subdirs creates the shared subdirectories and removes what no option asks for" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    # What an earlier run with three tasks left, a file in a shared
    # subdirectory that stays, and a file left at the top
    mkdir -p "${data}/0" "${data}/1" "${data}/2/deep"
    touch "${data}/0/kept.txt" "${data}/2/deep/old.txt" "${data}/stray.txt" "${data}/.hidden"
    define_writer_opts 0 1

    debasher::_prepare_shared_subdirs 0

    [ -f "${data}/0/kept.txt" ]
    [ -d "${data}/1" ]
    [ ! -e "${data}/2" ]
    [ ! -e "${data}/stray.txt" ]
    [ ! -e "${data}/.hidden" ]
}

@test "_prepare_shared_subdirs looks inside a directory on the way to a shared subdirectory" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/sample1/bam" "${data}/sample1/old" "${data}/sample2/bam"
    touch "${data}/sample1/bam/a.bam" "${data}/sample1/stray.txt"
    define_writer_opts "sample1/bam"

    debasher::_prepare_shared_subdirs 0

    [ -f "${data}/sample1/bam/a.bam" ]
    [ ! -e "${data}/sample1/old" ]
    [ ! -e "${data}/sample1/stray.txt" ]
    [ ! -e "${data}/sample2" ]
}

@test "_prepare_shared_subdirs keeps everything below a shared subdirectory that holds another one" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/a/other"
    define_writer_opts "a" "a/b"

    debasher::_prepare_shared_subdirs 0

    [ -d "${data}/a/b" ]
    [ -d "${data}/a/other" ]
}

@test "_prepare_shared_subdirs only names, in a validation, what a run would remove, and creates nothing" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/2"
    define_writer_opts 0

    run debasher::_prepare_shared_subdirs 1

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"would remove ${data}/2"* ]]
    [ -d "${data}/2" ]
    [ ! -e "${data}/0" ]
}

@test "_prepare_shared_subdirs removes a symbolic link without following it" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    local outside="${BATS_TEST_TMPDIR}/outside"
    mkdir -p "${outside}"
    touch "${outside}/precious.txt"
    ln -s "${outside}" "${data}/link"
    define_writer_opts 0

    debasher::_prepare_shared_subdirs 0

    [ ! -e "${data}/link" ] && [ ! -L "${data}/link" ]
    [ -f "${outside}/precious.txt" ]
}

@test "_prepare_shared_subdirs follows a shared directory that is itself a symbolic link" {
    init_program
    local target="${BATS_TEST_TMPDIR}/elsewhere"
    mkdir -p "${target}/2"
    rmdir "${DEBASHER_PROGRAM_OUTDIR}/data"
    ln -s "${target}" "${DEBASHER_PROGRAM_OUTDIR}/data"
    define_writer_opts 0

    debasher::_prepare_shared_subdirs 0

    [ -d "${target}/0" ]
    [ ! -e "${target}/2" ]
}

@test "_prepare_shared_subdirs refuses a shared subdirectory whose subpath goes through a symbolic link" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    local outside="${BATS_TEST_TMPDIR}/outside"
    mkdir -p "${outside}"
    ln -s "${outside}" "${data}/sample1"
    define_writer_opts "sample1/bam"

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"symbolic link"* ]]
    [ ! -e "${outside}/bam" ]
}

@test "_prepare_shared_subdirs refuses a shared subdirectory of a shared directory that no module declares" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-outd" "undeclared" optlist --subdir "0"

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"undeclared"* ]]
}

@test "_prepare_shared_subdirs refuses an output option that holds a subdivided shared directory" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    touch "${data}/report.txt"
    define_writer_opts 0
    report_define_opts()
    {
        local optlist=""
        define_opt_from_shared_dir "-outd" "data" optlist || return 1
        save_opt_list optlist
    }
    set +e
    report_define_opts
    set -e

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"output option of report:0 holds the shared directory data"* ]]
    [ -f "${data}/report.txt" ]
}

@test "_prepare_shared_subdirs allows an input option that holds a subdivided shared directory" {
    init_program
    define_writer_opts 0
    merge_define_opts()
    {
        local optlist=""
        define_opt_from_shared_dir "-ind" "data" optlist || return 1
        save_opt_list optlist
    }
    set +e
    merge_define_opts
    set -e

    debasher::_prepare_shared_subdirs 0

    [ -d "${DEBASHER_PROGRAM_OUTDIR}/data/0" ]
}

@test "_prepare_shared_subdirs refuses to remove anything while a process that left the program is still running" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/2"
    define_writer_opts 0
    DEBASHER_PROGRAM_PROCESSES["writer"]=1
    mkdir -p "$(debasher::get_prg_exec_dir_given_basedir "${DEBASHER_PROGRAM_OUTDIR}")/gone"
    debasher::_process_is_in_progress() { [ "$2" = "gone" ]; }

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"gone"* ]]
    [ -d "${data}/2" ]
}
