#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_opts.sh, run against the artifact
# generated by engine/Makefile.am's suffix rule (not the .sh source), so
# they exercise what actually ships. They cover the shared subdirectories
# that define_opt_from_shared_dir --subdir asks for and the task
# subdirectories that define_opt_from_process_outdir --subdir asks for:
# how the options are defined, how the engine creates, empties and cleans
# the directories, and how the define functions know the task whose
# options they define, inside an option generator too.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # debasher_lib.sh declares its associative arrays at the top level of
    # a script; inside setup() a bare "declare" would be local to it, so
    # the ones these tests use are made global here. Their values are set
    # by init_program, from the test itself, since the local ones still
    # hide the global ones until setup() returns
    declare -gA DEBASHER_PROGRAM_SHDIRS DEBASHER_PROGRAM_SHSUBDIRS
    declare -gA DEBASHER_PROGRAM_PROCESSES DEBASHER_PROCESS_OPT_LIST_LEN
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES DEBASHER_PROCESS_TASK_SUBDIRS
    declare -g DEBASHER_PROGRAM_OUTDIR
}

# Makes the output directory of the run, with the shared directory "data"
# that a module declares
init_program() {
    MKDIR="$(command -v mkdir)"; RM="$(command -v rm)"
    FIND="$(command -v find)"; BASENAME="$(command -v basename)"
    GREP="$(command -v grep)"
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${DEBASHER_PROGRAM_OUTDIR}/data"
    DEBASHER_PROGRAM_SHDIRS["data"]=${DEBASHER_SHDIR_MODULE_OWNER}
}

# Defines the options of an array process "writer" with one task for each
# subpath given, each with -outd in the shared subdirectory of "data"
# named by that subpath
define_writer_opts() {
    writer_define_opts()
    {
        local subpath
        for subpath in "$@"; do
            local optlist=""
            define_opt_from_shared_dir "-outd" "data" optlist --subdir "${subpath}" || return 1
            save_opt_list optlist
        done
    }
    # save_opt_list relies on lookups that return 1 in the ordinary case,
    # which bats's errexit would treat as a failure
    set +e
    writer_define_opts "$@"
    local status=$?
    set -e
    return "${status}"
}

# --- debasher::define_opt_from_shared_dir --------------------------------

@test "define_opt_from_shared_dir gives the path of the shared directory without --subdir, and registers nothing" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-datadir" "data" optlist
    [[ "${optlist}" == *"${DEBASHER_PROGRAM_OUTDIR}/data"* ]]
    [ "${#DEBASHER_PROGRAM_SHSUBDIRS[@]}" -eq 0 ]
}

@test "define_opt_from_shared_dir --subdir gives the path of the shared subdirectory and registers it, without creating it" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-outd" "data" optlist --subdir "sample1/bam"
    [[ "${optlist}" == *"${DEBASHER_PROGRAM_OUTDIR}/data/sample1/bam"* ]]
    [ "${DEBASHER_PROGRAM_SHSUBDIRS["data/sample1/bam"]}" = "data" ]
    [ ! -e "${DEBASHER_PROGRAM_OUTDIR}/data/sample1" ]
}

@test "define_opt_from_shared_dir --subdir refuses a subpath that does not stay below its shared directory" {
    init_program
    local subpath
    for subpath in "" "/abs" "a//b" "a/" "." "a/./b" ".." "a/../b"; do
        run debasher::define_opt_from_shared_dir "-outd" "data" optlist --subdir "${subpath}"
        [ "${status}" -ne 0 ]
    done
    [ "${#DEBASHER_PROGRAM_SHSUBDIRS[@]}" -eq 0 ]
}

@test "define_opt_from_shared_dir refuses an unknown flag and a --subdir with no subpath" {
    init_program
    run debasher::define_opt_from_shared_dir "-outd" "data" optlist --mirror
    [ "${status}" -ne 0 ]
    run debasher::define_opt_from_shared_dir "-outd" "data" optlist --subdir
    [ "${status}" -ne 0 ]
}

# --- debasher::_prepare_shared_subdirs -----------------------------------

@test "_prepare_shared_subdirs does nothing when no option asks for a shared subdirectory" {
    init_program
    touch "${DEBASHER_PROGRAM_OUTDIR}/data/keep.txt"
    debasher::_prepare_shared_subdirs 0
    [ -f "${DEBASHER_PROGRAM_OUTDIR}/data/keep.txt" ]
}

@test "_prepare_shared_subdirs creates the shared subdirectories and removes what no option asks for" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    # What an earlier run with three tasks left, a file in a shared
    # subdirectory that stays, and a file left at the top
    mkdir -p "${data}/0" "${data}/1" "${data}/2/deep"
    touch "${data}/0/kept.txt" "${data}/2/deep/old.txt" "${data}/stray.txt" "${data}/.hidden"
    define_writer_opts 0 1

    debasher::_prepare_shared_subdirs 0

    [ -f "${data}/0/kept.txt" ]
    [ -d "${data}/1" ]
    [ ! -e "${data}/2" ]
    [ ! -e "${data}/stray.txt" ]
    [ ! -e "${data}/.hidden" ]
}

@test "_prepare_shared_subdirs looks inside a directory on the way to a shared subdirectory" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/sample1/bam" "${data}/sample1/old" "${data}/sample2/bam"
    touch "${data}/sample1/bam/a.bam" "${data}/sample1/stray.txt"
    define_writer_opts "sample1/bam"

    debasher::_prepare_shared_subdirs 0

    [ -f "${data}/sample1/bam/a.bam" ]
    [ ! -e "${data}/sample1/old" ]
    [ ! -e "${data}/sample1/stray.txt" ]
    [ ! -e "${data}/sample2" ]
}

@test "_prepare_shared_subdirs keeps everything below a shared subdirectory that holds another one" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/a/other"
    define_writer_opts "a" "a/b"

    debasher::_prepare_shared_subdirs 0

    [ -d "${data}/a/b" ]
    [ -d "${data}/a/other" ]
}

@test "_prepare_shared_subdirs only names, in a validation, what a run would remove, and creates nothing" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/2"
    define_writer_opts 0

    run debasher::_prepare_shared_subdirs 1

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"would remove ${data}/2"* ]]
    [ -d "${data}/2" ]
    [ ! -e "${data}/0" ]
}

@test "_prepare_shared_subdirs removes a symbolic link without following it" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    local outside="${BATS_TEST_TMPDIR}/outside"
    mkdir -p "${outside}"
    touch "${outside}/precious.txt"
    ln -s "${outside}" "${data}/link"
    define_writer_opts 0

    debasher::_prepare_shared_subdirs 0

    [ ! -e "${data}/link" ] && [ ! -L "${data}/link" ]
    [ -f "${outside}/precious.txt" ]
}

@test "_prepare_shared_subdirs follows a shared directory that is itself a symbolic link" {
    init_program
    local target="${BATS_TEST_TMPDIR}/elsewhere"
    mkdir -p "${target}/2"
    rmdir "${DEBASHER_PROGRAM_OUTDIR}/data"
    ln -s "${target}" "${DEBASHER_PROGRAM_OUTDIR}/data"
    define_writer_opts 0

    debasher::_prepare_shared_subdirs 0

    [ -d "${target}/0" ]
    [ ! -e "${target}/2" ]
}

@test "_prepare_shared_subdirs refuses a shared subdirectory whose subpath goes through a symbolic link" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    local outside="${BATS_TEST_TMPDIR}/outside"
    mkdir -p "${outside}"
    ln -s "${outside}" "${data}/sample1"
    define_writer_opts "sample1/bam"

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"symbolic link"* ]]
    [ ! -e "${outside}/bam" ]
}

@test "_prepare_shared_subdirs refuses a shared subdirectory of a shared directory that no module declares" {
    init_program
    local optlist=""
    define_opt_from_shared_dir "-outd" "undeclared" optlist --subdir "0"

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"undeclared"* ]]
}

@test "_prepare_shared_subdirs refuses an output option that holds a subdivided shared directory" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    touch "${data}/report.txt"
    define_writer_opts 0
    report_define_opts()
    {
        local optlist=""
        define_opt_from_shared_dir "-outd" "data" optlist || return 1
        save_opt_list optlist
    }
    set +e
    report_define_opts
    set -e

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"output option of report:0 holds the shared directory data"* ]]
    [ -f "${data}/report.txt" ]
}

@test "_prepare_shared_subdirs allows an input option that holds a subdivided shared directory" {
    init_program
    define_writer_opts 0
    merge_define_opts()
    {
        local optlist=""
        define_opt_from_shared_dir "-ind" "data" optlist || return 1
        save_opt_list optlist
    }
    set +e
    merge_define_opts
    set -e

    debasher::_prepare_shared_subdirs 0

    [ -d "${DEBASHER_PROGRAM_OUTDIR}/data/0" ]
}

@test "_prepare_shared_subdirs refuses to remove anything while a process that left the program is still running" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/2"
    define_writer_opts 0
    DEBASHER_PROGRAM_PROCESSES["writer"]=1
    mkdir -p "$(debasher::get_prg_exec_dir_given_basedir "${DEBASHER_PROGRAM_OUTDIR}")/gone"
    debasher::_process_is_in_progress() { [ "$2" = "gone" ]; }

    run debasher::_prepare_shared_subdirs 0

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"gone"* ]]
    [ -d "${data}/2" ]
}

# --- The task whose options are being defined ------------------------------

@test "define_value_desc_opt names the value descriptor after the task of an array" {
    init_program
    valproc_define_opts()
    {
        local idx
        for idx in 0 1; do
            local optlist=""
            define_value_desc_opt "-outv" optlist || return 1
            save_opt_list optlist
        done
    }
    set +e
    valproc_define_opts
    set -e

    local outd="${DEBASHER_PROGRAM_OUTDIR}/valproc"
    [[ -v DEBASHER_OUT_VALUE_TO_PROCESSES["${outd}/.__VAL_DESCRIPTOR__-outv_0"] ]]
    [[ -v DEBASHER_OUT_VALUE_TO_PROCESSES["${outd}/.__VAL_DESCRIPTOR__-outv_1"] ]]
}

@test "inside an option generator, the define functions take the task index from the engine" {
    init_program
    declare -gA DEBASHER_PROGRAM_FIFOS DEBASHER_FIFO_READERS DEBASHER_FIFO_MIRRORED
    declare -gA DEBASHER_FIFO_KINDS DEBASHER_FIFO_OWNER_OPTS
    declare -g genproc_optlist
    genproc_generate_opts()
    {
        local task_idx=$5
        local optlist=""
        define_fifo_opt "-outf" "genproc_out_${task_idx}" optlist || return 1
        define_value_desc_opt "-outv" optlist || return 1
        define_opt_from_process_outdir "-outd" optlist --subdir "part${task_idx}" || return 1
        genproc_optlist=${optlist}
    }

    debasher::_call_generate_opts genproc_generate_opts "" "" "genproc" "" 1

    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROGRAM_FIFOS["genproc/genproc_out_1"]}" = "genproc${sep}1" ]
    [[ "${genproc_optlist}" == *".__VAL_DESCRIPTOR__-outv_1"* ]]
    [ "${DEBASHER_PROCESS_TASK_SUBDIRS["genproc${sep}1"]}" = "part1" ]
    # Once the generator returns, the engine no longer keeps the index
    [ -z "${DEBASHER_GENERATING_TASK_IDX:-}" ]
}

@test "define_fifo_opt_generator is define_fifo_opt, and ignores the task index it is given" {
    init_program
    declare -gA DEBASHER_PROGRAM_FIFOS DEBASHER_FIFO_READERS DEBASHER_FIFO_MIRRORED
    declare -gA DEBASHER_FIFO_KINDS DEBASHER_FIFO_OWNER_OPTS
    oldgen_generate_opts()
    {
        local optlist=""
        define_fifo_opt_generator "-outf" "oldgen_out" 7 optlist || return 1
    }

    debasher::_call_generate_opts oldgen_generate_opts "" "" "oldgen" "" 2

    [ "${DEBASHER_PROGRAM_FIFOS["oldgen/oldgen_out"]}" = "oldgen${DEBASHER_ASSOC_ARRAY_ELEM_SEP}2" ]
}

# --- debasher::define_opt_from_process_outdir -----------------------------

# Defines the options of an array process "worker" with one task for each
# subpath given, each with -outd in the task subdirectory named by that
# subpath
define_worker_opts() {
    worker_define_opts()
    {
        local subpath
        for subpath in "$@"; do
            local optlist=""
            define_opt_from_process_outdir "-outd" optlist --subdir "${subpath}" || return 1
            save_opt_list optlist
        done
    }
    set +e
    worker_define_opts "$@"
    local status=$?
    set -e
    return "${status}"
}

@test "define_opt_from_process_outdir gives the process output directory, or a task subdirectory that it records under its task" {
    init_program
    local optlist=""
    plain_define_opts() { define_opt_from_process_outdir "-outd" optlist; }
    plain_define_opts
    [[ "${optlist}" == *"${DEBASHER_PROGRAM_OUTDIR}/plain"* ]]
    [ "${#DEBASHER_PROCESS_TASK_SUBDIRS[@]}" -eq 0 ]

    define_worker_opts 0 1
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROCESS_TASK_SUBDIRS["worker${sep}0"]}" = "0" ]
    [ "${DEBASHER_PROCESS_TASK_SUBDIRS["worker${sep}1"]}" = "1" ]
    [[ -v DEBASHER_OUT_VALUE_TO_PROCESSES["${DEBASHER_PROGRAM_OUTDIR}/worker/1"] ]]
    [ ! -e "${DEBASHER_PROGRAM_OUTDIR}/worker" ]
}

@test "_check_task_subdirs accepts a task subdirectory for each task" {
    init_program
    define_worker_opts 0 1 2
    debasher::_check_task_subdirs
}

@test "_check_task_subdirs refuses two tasks that ask for the same task subdirectory" {
    init_program
    define_worker_opts same same
    run debasher::_check_task_subdirs
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"ask for the same task subdirectory same"* ]]
}

@test "_check_task_subdirs refuses a task subdirectory below another one of the same process" {
    init_program
    define_worker_opts a a/b
    run debasher::_check_task_subdirs
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"a/b of process worker is below another one, a"* ]]
}

@test "_check_task_subdirs refuses an output option that holds a subdivided process output directory" {
    init_program
    define_worker_opts 0
    worker_define_opts()
    {
        local optlist=""
        define_opt_from_process_outdir "-outdir" optlist || return 1
        save_opt_list optlist
    }
    set +e
    worker_define_opts
    set -e

    run debasher::_check_task_subdirs
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"holds the output directory of process worker"* ]]
}

# --- Preparing and emptying task subdirectories ----------------------------

@test "_prepare_task_subdirs_for_process removes what no option names and creates the task subdirectories" {
    init_program
    local outd="${DEBASHER_PROGRAM_OUTDIR}/worker"
    # What an earlier run with three tasks left, and a file that a task
    # wrote outside its task subdirectory
    mkdir -p "${outd}/0" "${outd}/2"
    touch "${outd}/0/kept.txt" "${outd}/stray.txt" "${outd}/named.txt"
    define_worker_opts 0 1
    worker_define_opts()
    {
        local optlist=""
        define_opt "-outf" "${DEBASHER_PROGRAM_OUTDIR}/worker/named.txt" optlist
        save_opt_list optlist
    }
    set +e
    worker_define_opts
    set -e

    debasher::_prepare_task_subdirs_for_process "${DEBASHER_PROGRAM_OUTDIR}" worker

    [ -f "${outd}/0/kept.txt" ]
    [ -d "${outd}/1" ]
    [ ! -e "${outd}/2" ]
    [ ! -e "${outd}/stray.txt" ]
    [ -f "${outd}/named.txt" ]
}

@test "_prepare_task_subdirs_for_process removes nothing from a process with a _reset_outfiles method" {
    init_program
    local outd="${DEBASHER_PROGRAM_OUTDIR}/worker"
    mkdir -p "${outd}/2"
    define_worker_opts 0
    worker_reset_outfiles() { :; }

    debasher::_prepare_task_subdirs_for_process "${DEBASHER_PROGRAM_OUTDIR}" worker

    [ -d "${outd}/0" ]
    [ -d "${outd}/2" ]
}

@test "_prepare_task_subdirs_for_process refuses a task subdirectory whose subpath goes through a symbolic link" {
    init_program
    local outd="${DEBASHER_PROGRAM_OUTDIR}/worker"
    local outside="${BATS_TEST_TMPDIR}/outside"
    mkdir -p "${outd}" "${outside}"
    ln -s "${outside}" "${outd}/sample1"
    define_worker_opts "sample1/bam"

    run debasher::_prepare_task_subdirs_for_process "${DEBASHER_PROGRAM_OUTDIR}" worker

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"symbolic link"* ]]
    [ ! -e "${outside}/bam" ]
}

@test "_reset_task_subdirs empties the task subdirectories of its task only, entries whose name starts with a dot included" {
    init_program
    local outd="${DEBASHER_PROGRAM_OUTDIR}/worker"
    mkdir -p "${outd}/0" "${outd}/1"
    touch "${outd}/0/old.txt" "${outd}/0/.hidden" "${outd}/1/other.txt"
    define_worker_opts 0 1

    debasher::_reset_task_subdirs "${DEBASHER_PROGRAM_OUTDIR}" worker 0

    [ -d "${outd}/0" ]
    [ -z "$(ls -A "${outd}/0")" ]
    [ -f "${outd}/1/other.txt" ]
}

@test "the default reset of a process with a single task removes the entries whose name starts with a dot too" {
    init_program
    local outd="${DEBASHER_PROGRAM_OUTDIR}/single"
    mkdir -p "${outd}/sub"
    touch "${outd}/out.txt" "${outd}/.__VAL_DESCRIPTOR__-outv_0"

    debasher::_default_reset_outfiles_for_process "${DEBASHER_PROGRAM_OUTDIR}" single

    [ -d "${outd}" ]
    [ -z "$(ls -A "${outd}")" ]
}

# --- Shared subdirectories and output options ------------------------------

@test "_prepare_shared_subdirs keeps a path that an output option names" {
    init_program
    local data="${DEBASHER_PROGRAM_OUTDIR}/data"
    mkdir -p "${data}/reports"
    touch "${data}/reports/report.txt" "${data}/stray.txt"
    define_writer_opts 0
    report_define_opts()
    {
        local optlist=""
        define_opt "-outf" "${DEBASHER_PROGRAM_OUTDIR}/data/reports/report.txt" optlist
        save_opt_list optlist
    }
    set +e
    report_define_opts
    set -e

    debasher::_prepare_shared_subdirs 0

    [ -f "${data}/reports/report.txt" ]
    [ ! -e "${data}/stray.txt" ]
}
