#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_sched.sh, run against the artifacts
# generated by engine/Makefile.am's suffix rule (not the .sh sources).

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
}

# Writes the context from a bash that has loaded the engine and a small
# module, with an environment of its own, into ${BATS_TEST_TMPDIR}/ctx.sh.
# Every bash here is the one that runs the tests, ${BASH}, not the first
# one of a bare PATH, which may be older than the engine needs (that of
# macOS is); in it, BASH names that bash, as the preamble of a built
# script names the one that configure found
write_context() {
    local module="${BATS_TEST_TMPDIR}/mod.sh"
    cat > "${module}" <<'EOM'
MODULE_VALUE="from the module"
declare -A MODULE_MAP=([a key]="a value")
declare -A MODULE_EMPTY_MAP
declare MODULE_EMPTY_SCALAR
module_func() { echo "module function"; }
EOM
    env -i PATH="/usr/bin:/bin" HOME=/tmp FOREIGN_VAR=foreign DEBASHER_EXPORTED=kept \
        ENGINE_BUILDDIR="${ENGINE_BUILDDIR}" MODULE="${module}" CTX="${BATS_TEST_TMPDIR}/ctx.sh" \
        "${BASH}" -c '
            debasher_pkglibdir="${ENGINE_BUILDDIR}"
            CAT="$(command -v cat)"
            source "${ENGINE_BUILDDIR}/debasher_lib.sh"
            source "${MODULE}"
            exported_func() { :; }
            export -f exported_func
            declare -gA DEBASHER_OPT_LIST_proc_0=([-x]=1)
            debasher::_write_exec_context "${CTX}"
        '
}

@test "_write_exec_context writes the variables and functions of the module and the engine" {
    write_context

    grep -q '^declare -- MODULE_VALUE="from the module"$' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^module_func ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^debasher::_write_exec_context ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -x PATH=' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -x DEBASHER_EXPORTED="kept"$' "${BATS_TEST_TMPDIR}/ctx.sh"
}

@test "_write_exec_context leaves out bash's own, read-only and exported variables, and the options of each task" {
    write_context

    ! grep -q ' FOREIGN_VAR=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' HOME=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' UID=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' BASH_VERSINFO=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' RANDOM=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q 'DEBASHER_OPT_LIST_proc_0' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q '^exported_func ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q '^declare -[-a-zA-Z]* _ctx_' "${BATS_TEST_TMPDIR}/ctx.sh"
}

@test "_write_exec_context writes a context that a clean bash loads without errors" {
    write_context

    run env -i "${BASH}" -c "source '${BATS_TEST_TMPDIR}/ctx.sh' && echo \"\${MODULE_MAP[a key]}\" && module_func"
    [ "${status}" -eq 0 ]
    [ "${output}" = "$(printf 'a value\nmodule function')" ]
}

@test "_write_exec_context declares the variables that have no value yet, keeping the type of an associative array" {
    write_context

    grep -q '^declare -A MODULE_EMPTY_MAP$' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -- MODULE_EMPTY_SCALAR$' "${BATS_TEST_TMPDIR}/ctx.sh"
    # A key with a dot, as the name of a namespaced process has, reads as
    # an associative key, not as arithmetic
    run env -i "${BASH}" -c "source '${BATS_TEST_TMPDIR}/ctx.sh' && echo \"[\${MODULE_EMPTY_MAP[ns.proc]:-}]\""
    [ "${status}" -eq 0 ]
    [ "${output}" = "[]" ]
}
