#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_processes.sh's process-implementation
# recovery helpers, run against the artifact generated by engine/
# Makefile.am's suffix rule (not the .sh source), so they exercise what
# actually ships. These pin down the exact false-positive/false-negative
# shapes found while debugging the frontend's "import program" feature
# (see debasher::_collect_func_deps's own comments): a same-script helper
# a process's exec function really calls must be pulled in, while a mere
# identifier collision -- a local variable, or a word inside a string or
# an embedded other-language script -- must not.
#
# The explain_opts-vs-actual-opts helpers further down (see
# debasher::_check_opt_names_vs_explain's own comments) reach into
# explain_opt/define_opt/save_opt_list and friends from
# debasher_lib_opts.sh, so setup() sources the whole engine/
# dependency chain (still entirely from ENGINE_BUILDDIR, via
# debasher_lib.sh's own include section) rather than just
# debasher_lib_processes on its own.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # bats runs setup() as a function body, and debasher_lib.sh's own
    # top-level "declare -A ..." lines are written assuming they run
    # at a real script's top level (as they do in production, where
    # debasher_exec.sh sources debasher_lib outside of any function):
    # a bare "declare" inside a function is local to that function, so
    # without this, DEBASHER_PROGRAM_OPT_TYPE & co would silently
    # vanish the moment setup() returns, before any @test body ran.
    # Force them global here instead.
    declare -gA DEBASHER_PROGRAM_OPT_DESC
    declare -gA DEBASHER_PROGRAM_OPT_TYPE
    declare -gA DEBASHER_PROGRAM_OPT_IS_CMDLINE
    declare -gA DEBASHER_PROGRAM_OPT_IS_MANDATORY
    declare -gA DEBASHER_PROGRAM_OPT_IS_TASK_OPT
    declare -gA DEBASHER_PROGRAM_OPT_IS_TASK_SHAPING
    declare -gA DEBASHER_MEMOIZED_OPTS
    declare -gA DEBASHER_PROGRAM_OPT_CATEG
    declare -gA DEBASHER_PROGRAM_CATEG_MAP
    declare -gA DEBASHER_INITIAL_PROCESS_SPEC
    declare -gA DEBASHER_PROGRAM_PROCESSES
    declare -g DEBASHER_PROGRAM_OUTDIR
}

# --- debasher::_blank_string_literals --------------------------------

@test "debasher::_blank_string_literals blanks a single-quoted span" {
    result=$(printf 'before %s after\n' "'count'" | debasher::_blank_string_literals)
    [ "${result}" = "before  after" ]
}

@test "debasher::_blank_string_literals blanks a single-quoted span spanning multiple lines" {
    result=$(printf 'before %s\nmiddle\n%s after\n' "'" "'" | debasher::_blank_string_literals)
    [ "${result}" = "before  after" ]
}

@test "debasher::_blank_string_literals blanks a double-quoted span with no dollar sign" {
    result=$(printf 'echo "no count here"\n' | debasher::_blank_string_literals)
    [ "${result}" = 'echo ' ]
}

@test "debasher::_blank_string_literals keeps a double-quoted span containing a dollar sign" {
    line='echo "value is $count here"'
    result=$(printf '%s\n' "${line}" | debasher::_blank_string_literals)
    [ "${result}" = "${line}" ]
}

# --- debasher::_declared_func_vars ------------------------------------

@test "debasher::_declared_func_vars lists local variable names, not their assigned values" {
    eval 'sample() { local numblocks=$(some_func "$1"); local i start_line count blockfile; count=$(( 1 + 2 )); }'

    run debasher::_declared_func_vars sample
    [ "${status}" -eq 0 ]
    [[ "${lines[*]}" == *"numblocks"* ]]
    [[ "${lines[*]}" == *"i"* ]]
    [[ "${lines[*]}" == *"count"* ]]
    [[ "${lines[*]}" == *"blockfile"* ]]
    # The call on the right-hand side of a declaration is a real
    # dependency, not a declared name -- it must not show up here.
    [[ "${lines[*]}" != *"some_func"* ]]
}

# --- debasher::_collect_func_deps -------------------------------------

# Sources $1 (a here-doc'd script written to a real file, since
# debasher::_collect_func_deps needs "declare -F" -- via extdebug -- to
# report a defining file on disk) and prints the space-joined set of
# dependencies debasher::_collect_func_deps collects for funcname $2,
# funcname itself excluded. Each fixture below has at most one real
# dependency, so this doesn't bother sorting the result.
collect_deps() {
    local scriptfile=$1
    local funcname=$2

    shopt -s extdebug
    source "${scriptfile}"
    local -A seen=()
    debasher::_collect_func_deps "${funcname}" "${scriptfile}" seen
    shopt -u extdebug

    local dep
    local -a deps=()
    for dep in "${!seen[@]}"; do
        [ "${dep}" = "${funcname}" ] && continue
        deps+=("${dep}")
    done
    echo "${deps[*]}"
}

@test "debasher::_collect_func_deps pulls in a helper the exec function actually calls" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
helper()
{
    :
}

main_proc()
{
    helper
}
EOF

    result=$(collect_deps "${scriptfile}" "main_proc")
    [ "${result}" = "helper" ]
}

@test "debasher::_collect_func_deps ignores a local variable that collides with a sibling process name" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
count()
{
    :
}

fragment()
{
    local i count
    count=$(( 1 + 1 ))
    echo "${count}"
}
EOF

    result=$(collect_deps "${scriptfile}" "fragment")
    [ -z "${result}" ]
}

@test "debasher::_collect_func_deps ignores a sibling process name that only appears in an embedded string/script" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
count()
{
    :
}

count_chars()
{
    awk '
        {
            count[$1]++
        }
        END {
            for (c in count) print c, count[c]
        }
    '
}

worker_task()
{
    count_chars "$1"
}
EOF

    result=$(collect_deps "${scriptfile}" "worker_task")
    [ "${result}" = "count_chars" ]
}

# --- debasher::_get_explained_opt_names --------------------------------

@test "debasher::_get_explained_opt_names collects names declared via explain_opt and explain_flag" {
    modernproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_flag "-f" "desc f"
    }

    local -A explained=()
    debasher::_get_explained_opt_names "modernproc" explained
    [ "${#explained[@]}" -eq 2 ]
    [[ -v explained["-a"] ]]
    [[ -v explained["-f"] ]]
}

@test "debasher::_get_explained_opt_names also collects names declared via the legacy explain_cmdline_opts" {
    legacyproc_explain_cmdline_opts()
    {
        explain_cmdline_opt "-x" "<string>" "desc x"
    }

    local -A explained=()
    debasher::_get_explained_opt_names "legacyproc" explained
    [ "${#explained[@]}" -eq 1 ]
    [[ -v explained["-x"] ]]
}

@test "debasher::_get_explained_opt_names keeps the command-line marks that identify_cmdline_opts set" {
    markedproc_explain_opts()
    {
        explain_opt "-n" "<int>" "desc n"
        explain_flag "-v" "desc v"
    }
    markedproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-n"
        opt_is_non_mandatory_cmdline "-v"
    }
    markedproc_explain_opts
    markedproc_identify_cmdline_opts

    local -A explained=()
    debasher::_get_explained_opt_names "markedproc" explained
    [ "${DEBASHER_PROGRAM_OPT_IS_CMDLINE["markedproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-n"]}" = 1 ]
    [ "${DEBASHER_PROGRAM_OPT_IS_CMDLINE["markedproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-v"]}" = 1 ]
}

@test "debasher::_get_explained_opt_names returns 1 and leaves the set empty when the process declares no explain function" {
    local -A explained=()
    ! debasher::_get_explained_opt_names "noexplainproc" explained || false
    [ "${#explained[@]}" -eq 0 ]
}

# --- debasher::_get_actual_opt_names_for_first_task ---------------------

@test "debasher::_get_actual_opt_names_for_first_task reads the per-task array already populated for a non-generator process" {
    declare -gA DEBASHER_OPT_LIST_readerproc_0=(["-a"]="1" ["-f"]="")

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "readerproc" actual
    [ "${#actual[@]}" -eq 2 ]
    [[ -v actual["-a"] ]]
    [[ -v actual["-f"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task leaves the set empty when no task was ever recorded for a non-generator process" {
    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "notaskproc" actual
    [ "${#actual[@]}" -eq 0 ]
}

@test "debasher::_get_actual_opt_names_for_first_task calls generate_opts once for a generator process and extracts its option names" {
    genproc_generate_opts_size()
    {
        echo 1
    }

    genproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist
        define_flag "-verbose" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc"]="genproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc" actual
    [ "${#actual[@]}" -eq 2 ]
    [[ -v actual["-id"] ]]
    [[ -v actual["-verbose"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task keeps each option's value, and none for a flag, for a generator process" {
    genvalproc_generate_opts_size()
    {
        echo 1
    }

    genvalproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-f" "a file with spaces" optlist
        define_flag "-verbose" optlist
        define_opt "-id" "${task_idx}" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genvalproc"]="genvalproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genvalproc" actual
    [ "${#actual[@]}" -eq 3 ]
    [ "${actual["-f"]}" = "a file with spaces" ]
    [ -z "${actual["-verbose"]}" ]
    [ "${actual["-id"]}" = "0" ]
}

@test "debasher::_get_actual_opt_names_for_first_task fails when generate_opts fails for a generator process" {
    genfailproc_generate_opts_size()
    {
        echo 1
    }

    genfailproc_generate_opts()
    {
        return 1
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genfailproc"]="genfailproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    ! debasher::_get_actual_opt_names_for_first_task "" "genfailproc" actual || false
}

@test "debasher::_get_actual_opt_names_for_first_task keeps generator option names that echo would take as its own flags" {
    genproc3_generate_opts_size()
    {
        echo 1
    }

    genproc3_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-n" "4" optlist
        define_opt "-e" "x" optlist
        define_flag "-E" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc3"]="genproc3"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc3" actual
    [ "${#actual[@]}" -eq 3 ]
    [[ -v actual["-n"] ]]
    [[ -v actual["-e"] ]]
    [[ -v actual["-E"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task's extra generate_opts call leaves no DEBASHER_OPT_LIST_* array behind" {
    genproc2_generate_opts_size()
    {
        echo 1
    }

    genproc2_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc2"]="genproc2"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc2" actual

    ! declare -p DEBASHER_OPT_LIST_genproc2_0 >/dev/null 2>&1 || false
}

# --- debasher::_check_opt_names_vs_explain -------------------------------

@test "debasher::_check_opt_names_vs_explain succeeds silently when defined and declared option names match" {
    cleanproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_flag "-f" "desc f"
    }
    declare -gA DEBASHER_OPT_LIST_cleanproc_0=(["-a"]="1" ["-f"]="")
    DEBASHER_PROGRAM_PROCESSES["cleanproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain aborts when a process defines an option its explain_opts never declared" {
    badproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
    }
    declare -gA DEBASHER_OPT_LIST_badproc_0=(["-a"]="1" ["-x"]="")
    DEBASHER_PROGRAM_PROCESSES["badproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process badproc defines option -x, which is not declared in its explain_opts"* ]]
}

@test "debasher::_check_opt_names_vs_explain only warns, and still succeeds, when a declared option is missing from the first task" {
    warnproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_opt "-b" "<int>" "desc b, only given via define_cmdline_opt_if_given"
    }
    declare -gA DEBASHER_OPT_LIST_warnproc_0=(["-a"]="1")
    DEBASHER_PROGRAM_PROCESSES["warnproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"Warning: process warnproc declares option -b in explain_opts, but it was not found among the options generated for its first task"* ]]
}

# --- debasher::_check_opt_names_vs_explain, "ith" option families -------
#
# A process whose number of "-foo0", "-foo1", ... "-foo<N-1>" options
# depends on a run-time value (N, e.g. a worker count) cannot
# explain_opt each instance by its literal name, so by convention it
# documents the whole family once, as "-foo-ith" (see
# dispatch_define_opts/aggregate_define_opts in
# debasher_dynamic_fanout.sh for the real pattern this mirrors).

@test "debasher::_check_opt_names_vs_explain does not error on an actual option that is a concrete instance of a declared ith family" {
    ithproc_explain_opts()
    {
        explain_opt "-outf-ith" "<file>" "desc, one per worker"
    }
    declare -gA DEBASHER_OPT_LIST_ithproc_0=(["-outf0"]="a" ["-outf1"]="b")
    DEBASHER_PROGRAM_PROCESSES["ithproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain does not warn about a declared ith family that has a concrete instance" {
    ithwarnproc_explain_opts()
    {
        explain_opt "-outf-ith" "<file>" "desc, one per worker"
    }
    declare -gA DEBASHER_OPT_LIST_ithwarnproc_0=(["-outf0"]="a")
    DEBASHER_PROGRAM_PROCESSES["ithwarnproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain takes an option ending in ith without the dash for an ordinary option, not a family" {
    noithproc_explain_opts()
    {
        explain_opt "-outfith" "<file>" "desc"
    }
    declare -gA DEBASHER_OPT_LIST_noithproc_0=(["-outf0"]="a")
    DEBASHER_PROGRAM_PROCESSES["noithproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process noithproc defines option -outf0, which is not declared in its explain_opts"* ]]
}

@test "debasher::_check_opt_names_vs_explain takes an option ending in ith that the tasks define for an ordinary one" {
    withproc_explain_opts()
    {
        explain_opt "-with" "<string>" "desc"
    }
    declare -gA DEBASHER_OPT_LIST_withproc_0=(["-with"]="x")
    DEBASHER_PROGRAM_PROCESSES["withproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain still errors on a numeric-suffixed option with no matching ith family declared" {
    notithproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
    }
    declare -gA DEBASHER_OPT_LIST_notithproc_0=(["-a"]="1" ["-x1"]="")
    DEBASHER_PROGRAM_PROCESSES["notithproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process notithproc defines option -x1, which is not declared in its explain_opts"* ]]
}

# --- define_fifo_opt in an array defined in a loop ---------------------

@test "debasher::define_fifo_opt registers each fifo of an array defined in a loop as owned by its own task" {
    declare -gA DEBASHER_PROGRAM_FIFOS DEBASHER_FIFO_READERS DEBASHER_FIFO_MIRRORED
    declare -gA DEBASHER_FIFO_KINDS DEBASHER_FIFO_OWNER_OPTS
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN DEBASHER_OUT_VALUE_TO_PROCESSES
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    loopfifoproc_define_opts()
    {
        local idx
        for (( idx = 0; idx < 3; idx++ )); do
            local optlist=""
            define_fifo_opt "-outf" "loopfifoproc_out_${idx}" optlist || return 1
            save_opt_list optlist
        done
    }
    # save_opt_list relies on lookups that return 1 in the ordinary case (no
    # option generator), which bats's errexit would treat as a failure.
    set +e
    loopfifoproc_define_opts "" "" "loopfifoproc" "${BATS_TEST_TMPDIR}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]

    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_0"]}" = "loopfifoproc${sep}0" ]
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_1"]}" = "loopfifoproc${sep}1" ]
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_2"]}" = "loopfifoproc${sep}2" ]
}

@test "debasher::_define_opts_for_process registers the fifos of a generator even when all process dependencies were given" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_FIFO_MIRRORED=()
    declare -gA DEBASHER_FIFO_KINDS=() DEBASHER_FIFO_OWNER_OPTS=()
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    genfifoproc_generate_opts_size()
    {
        echo 3
    }

    genfifoproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_fifo_opt_generator "-outf" "genfifoproc_out_${task_idx}" "${task_idx}" optlist || return 1
        save_opt_list optlist
    }

    local spec="genfifoproc cpus=1 mem=32 time=00:01:00 ${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP} processdeps=none"
    DEBASHER_INITIAL_PROCESS_SPEC["genfifoproc"]="${spec}"
    DEBASHER_PROGRAM_PROCESSES["genfifoproc"]=1

    set +e
    debasher::_define_opts_for_process "" "${spec}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]

    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["genfifoproc"]}" -eq 3 ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_0"]}" = "genfifoproc${sep}0" ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_1"]}" = "genfifoproc${sep}1" ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_2"]}" = "genfifoproc${sep}2" ]

    # The readers of each fifo are found through the output values of its
    # owner task, so those have to be recorded as well
    local fifo="$(debasher::_get_absolute_fifoname genfifoproc genfifoproc_out_1)"
    [ "${DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]}" = "genfifoproc${sep}1" ]
}

@test "debasher::_define_opts_for_process stops before the options are defined when a task shaping option is missing" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    shapegenproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }

    shapegenproc_generate_opts_size()
    {
        touch "${BATS_TEST_TMPDIR}/size_called"
        echo 2
    }

    shapegenproc_generate_opts()
    {
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist || return 1
        save_opt_list optlist
    }

    local spec="shapegenproc cpus=1 mem=32 time=00:01:00"
    DEBASHER_INITIAL_PROCESS_SPEC["shapegenproc"]="${spec}"
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-l" "200")

    run debasher::_define_opts_for_process "${cmdline}" "${spec}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process shapegenproc needs the task shaping option -w"* ]]
    [ ! -e "${BATS_TEST_TMPDIR}/size_called" ]
}

@test "debasher::_define_opts_for_process takes the process name from the given process spec, not from a variable of its caller" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    genonlyproc_generate_opts_size()
    {
        echo 2
    }

    genonlyproc_generate_opts()
    {
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist || return 1
        save_opt_list optlist
    }

    local spec="genonlyproc cpus=1 mem=32 time=00:01:00"
    DEBASHER_INITIAL_PROCESS_SPEC["genonlyproc"]="${spec}"

    # A caller whose own processname variable names another process, one
    # without a generator
    local processname="loopproc"
    set +e
    debasher::_define_opts_for_process "" "${spec}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["genonlyproc"]}" -eq 2 ]
    [ -z "${DEBASHER_PROCESS_OPT_LIST_LEN["loopproc"]+x}" ]
}

# --- readers of the fifos -----------------------------------------------

@test "debasher::_deserialized_args_idx_is_dep_candidate writes the option index into the caller's variable j" {
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES=(["/abs/fifo"]="fanin")
    DEBASHER_DESERIALIZED_ARGS=("-n" "3" "-from_fanin" "/abs/fifo")
    # The callers name their variable j, as here
    caller() {
        local j=""
        debasher::_deserialized_args_idx_is_dep_candidate 3 j || return 1
        echo "${j}"
    }

    run caller
    [ "${status}" -eq 0 ]
    [ "${output}" = "2" ]
}

@test "debasher::_register_fifos_read_by_process registers the reader of a fifo that its owner writes" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_READER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname fanin fanin_to_loop)"
    DEBASHER_PROGRAM_FIFOS["fanin/fanin_to_loop"]="fanin${sep}0"
    DEBASHER_FIFO_READERS["fanin/fanin_to_loop"]="${DEBASHER_EXTERNAL_FIFO_END}"
    # fanin writes it through its output option (-outloop, say)
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="fanin${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["loop"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-n${DEBASHER_ARG_SEP}3${DEBASHER_ARG_SEP}-from_fanin${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_read_by_process "" "loop"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_READERS["fanin/fanin_to_loop"]}" = "loop${sep}0" ]
    [ "${DEBASHER_FIFO_READER_OPTS["fanin/fanin_to_loop"]}" = "-from_fanin" ]
}

@test "debasher::_register_fifos_read_by_process registers another task of the same array as the reader" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_READER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname worker worker_out_0)"
    DEBASHER_PROGRAM_FIFOS["worker/worker_out_0"]="worker${sep}0"
    DEBASHER_FIFO_READERS["worker/worker_out_0"]="${DEBASHER_EXTERNAL_FIFO_END}"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="worker${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["worker"]=2
    # Task 0 writes the fifo, task 1 reads it.
    debasher::_get_opts_for_process_and_task() {
        if [ "$3" -eq 0 ]; then
            echo "-outnext${DEBASHER_ARG_SEP}${fifo}"
        else
            echo "-n${DEBASHER_ARG_SEP}3${DEBASHER_ARG_SEP}-from_prev${DEBASHER_ARG_SEP}${fifo}"
        fi
    }

    set +e
    debasher::_register_fifos_read_by_process "" "worker"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_READERS["worker/worker_out_0"]}" = "worker${sep}1" ]
    [ "${DEBASHER_FIFO_READER_OPTS["worker/worker_out_0"]}" = "-from_prev" ]
}

@test "debasher::_register_fifos_read_by_process registers the owner that reads its own fifo through another option (a self-loop)" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_READER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname counter counter_self)"
    DEBASHER_PROGRAM_FIFOS["counter/counter_self"]="counter${sep}0"
    DEBASHER_FIFO_READERS["counter/counter_self"]="${DEBASHER_EXTERNAL_FIFO_END}"
    DEBASHER_FIFO_OWNER_OPTS["counter/counter_self"]="-outself"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="counter${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["counter"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-self${DEBASHER_ARG_SEP}${fifo}${DEBASHER_ARG_SEP}-outself${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_read_by_process "" "counter"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_READERS["counter/counter_self"]}" = "counter${sep}0" ]
    [ "${DEBASHER_FIFO_READER_OPTS["counter/counter_self"]}" = "-self" ]
}

@test "debasher::_register_fifos_read_by_process leaves outside the reader of a fifo that its owner defines through an input option" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_READER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname fanin fanin_ext)"
    DEBASHER_PROGRAM_FIFOS["fanin/fanin_ext"]="fanin${sep}0"
    DEBASHER_FIFO_READERS["fanin/fanin_ext"]="${DEBASHER_EXTERNAL_FIFO_END}"
    DEBASHER_FIFO_OWNER_OPTS["fanin/fanin_ext"]="-ext"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="fanin${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["fanin"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-ext${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_read_by_process "" "fanin"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_READERS["fanin/fanin_ext"]}" = "${DEBASHER_EXTERNAL_FIFO_END}" ]
    [ -z "${DEBASHER_FIFO_READER_OPTS["fanin/fanin_ext"]+x}" ]
}

# --- process dependencies -------------------------------------------------

@test "debasher::_merge_deptypes keeps the other type when one of them is none or after" {
    local merged
    debasher::_merge_deptypes "" "afterok" merged
    [ "${merged}" = "afterok" ]
    debasher::_merge_deptypes "none" "aftercorr" merged
    [ "${merged}" = "aftercorr" ]
    debasher::_merge_deptypes "aftercorr" "after" merged
    [ "${merged}" = "aftercorr" ]
    debasher::_merge_deptypes "after" "afterany" merged
    [ "${merged}" = "afterany" ]
    debasher::_merge_deptypes "after" "none" merged
    [ "${merged}" = "after" ]
}

@test "debasher::_merge_deptypes gives afterok for any two of afterok, afterany and aftercorr" {
    local merged
    debasher::_merge_deptypes "aftercorr" "afterany" merged
    [ "${merged}" = "afterok" ]
    debasher::_merge_deptypes "afterany" "afterok" merged
    [ "${merged}" = "afterok" ]
    debasher::_merge_deptypes "afterok" "aftercorr" merged
    [ "${merged}" = "afterok" ]
}

@test "debasher::_merge_deptypes gives afternotok for afternotok and afterany" {
    local merged
    debasher::_merge_deptypes "afterany" "afternotok" merged
    [ "${merged}" = "afternotok" ]
}

@test "debasher::_merge_deptypes fails for afternotok together with afterok or aftercorr" {
    local merged
    run debasher::_merge_deptypes "afterok" "afternotok" merged
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"cannot both be satisfied"* ]]
    run debasher::_merge_deptypes "afternotok" "aftercorr" merged
    [ "${status}" -ne 0 ]
}

@test "debasher::_merge_deptypes fails for an unknown type" {
    local merged
    run debasher::_merge_deptypes "afterok" "aftrok" merged
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"unknown process dependency type: aftrok"* ]]
}

# Holds the lock of the output directory $1 the way debasher_exec does, with
# its process id in the lock file, until it gets SIGTERM, which it ignores
# when $2 is "ignore"
hold_lock() {
    (
        exec 9>>"$1/lock"
        flock -x 9
        echo "${BASHPID}" > "$1/lock"
        if [ "${2:-}" = "ignore" ]; then
            trap '' TERM
        else
            trap 'exit 0' TERM
        fi
        while :; do sleep 0.1; done
    ) &
    local i
    for (( i = 0; i < 50; i++ )); do
        ! flock -n "$1/lock" true && [ -s "$1/lock" ] && return 0
        sleep 0.1
    done
    return 1
}

@test "debasher::_outdir_is_locked is true only while a debasher_exec holds the lock" {
    FLOCK="$(command -v flock)"; CAT="$(command -v cat)"
    local outd="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${outd}"
    ! debasher::_outdir_is_locked "${outd}" || false
    # The check creates no lock file
    [ ! -e "${outd}/lock" ]

    hold_lock "${outd}"
    local pid=$(cat "${outd}/lock")
    debasher::_outdir_is_locked "${outd}"

    kill -TERM "${pid}"
    flock -w 5 "${outd}/lock" true
    ! debasher::_outdir_is_locked "${outd}" || false
}

@test "debasher::_stop_run_scheduler does nothing when no debasher_exec holds the lock" {
    FLOCK="$(command -v flock)"; CAT="$(command -v cat)"
    local outd="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${outd}"
    debasher::_stop_run_scheduler "${outd}"
    : > "${outd}/lock"
    debasher::_stop_run_scheduler "${outd}"
}

@test "debasher::_stop_run_scheduler stops the holder of the lock with SIGTERM and waits until the lock is free" {
    FLOCK="$(command -v flock)"; CAT="$(command -v cat)"
    local outd="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${outd}"
    hold_lock "${outd}"
    local pid=$(cat "${outd}/lock")

    run debasher::_stop_run_scheduler "${outd}"
    [ "${status}" -eq 0 ]
    [[ "${output}" != *"Warning"* ]]
    flock -n "${outd}/lock" true
    ! kill -0 "${pid}" 2>/dev/null || false
}

@test "debasher::_stop_run_scheduler kills a holder of the lock that does not stop on SIGTERM" {
    FLOCK="$(command -v flock)"; CAT="$(command -v cat)"
    DEBASHER_EXEC_STOP_GRACE_SECS=1
    local outd="${BATS_TEST_TMPDIR}/outd"
    mkdir -p "${outd}"
    hold_lock "${outd}" ignore

    run debasher::_stop_run_scheduler "${outd}"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"did not stop within 1s"* ]]
    flock -n "${outd}/lock" true
}

@test "debasher::_throttle_lets_all_tasks_run accepts no throttle and a throttle not smaller than the number of tasks" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=(["arr"]=4)
    DEBASHER_ARRAY_TASK_NOTHROTTLE=0
    DEBASHER_DEFAULT_ARRAY_TASK_THROTTLE=${DEBASHER_ARRAY_TASK_NOTHROTTLE}
    local sep="${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP}"

    debasher::_throttle_lets_all_tasks_run "arr" "arr cpus=1 mem=32 time=00:01:00 ${sep} processdeps=none"
    debasher::_throttle_lets_all_tasks_run "arr" "arr cpus=1 mem=32 time=00:01:00 throttle=4 ${sep} processdeps=none"
    debasher::_throttle_lets_all_tasks_run "arr" "arr cpus=1 mem=32 time=00:01:00 throttle=8 ${sep} processdeps=none"
}

@test "debasher::_throttle_lets_all_tasks_run refuses a throttle, its own or the default one, smaller than the number of tasks" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=(["arr"]=4)
    DEBASHER_ARRAY_TASK_NOTHROTTLE=0
    local sep="${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP}"

    DEBASHER_DEFAULT_ARRAY_TASK_THROTTLE=${DEBASHER_ARRAY_TASK_NOTHROTTLE}
    ! debasher::_throttle_lets_all_tasks_run "arr" "arr cpus=1 mem=32 time=00:01:00 throttle=2 ${sep} processdeps=none" || false

    DEBASHER_DEFAULT_ARRAY_TASK_THROTTLE=3
    ! debasher::_throttle_lets_all_tasks_run "arr" "arr cpus=1 mem=32 time=00:01:00 ${sep} processdeps=none" || false
}

@test "debasher::_deps_without_ids_can_hold takes a dependency on a launched process, or on a finished one but afternotok" {
    declare -A ids=(["a"]="101")
    debasher::_get_process_status() { [ "$2" = "done" ] && echo "FINISHED" || echo "TO-DO"; }

    debasher::_deps_without_ids_can_hold "none" "/o" ids
    debasher::_deps_without_ids_can_hold "afternotok:a" "/o" ids
    debasher::_deps_without_ids_can_hold "afterok:done,after:done,afterany:done,aftercorr:done" "/o" ids
    ! debasher::_deps_without_ids_can_hold "afternotok:done" "/o" ids || false
    ! debasher::_deps_without_ids_can_hold "afterok:a,afterok:pending" "/o" ids || false
}

@test "debasher::_deps_without_ids_can_hold needs one dependency that can hold with ?" {
    declare -A ids=()
    debasher::_get_process_status() { [ "$2" = "done" ] && echo "FINISHED" || echo "TO-DO"; }

    debasher::_deps_without_ids_can_hold "afternotok:done?afterok:done" "/o" ids
    ! debasher::_deps_without_ids_can_hold "afternotok:done?afterok:pending" "/o" ids || false
}

@test "debasher::_check_explicit_processdeps accepts none and lists with one separator" {
    debasher::_check_explicit_processdeps "p" "none"
    debasher::_check_explicit_processdeps "p" "afterok:a"
    debasher::_check_explicit_processdeps "p" "afterok:a,after:ns.b"
    debasher::_check_explicit_processdeps "p" "afterok:a?afternotok:b"
}

@test "debasher::_check_explicit_processdeps refuses an unknown type" {
    run debasher::_check_explicit_processdeps "p" "afterok:a,afterbogus:b"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"unknown type: afterbogus"* ]]
}

@test "debasher::_check_explicit_processdeps refuses a dependency without a type or a process" {
    run debasher::_check_explicit_processdeps "p" "a"
    [ "${status}" -eq 1 ]
    run debasher::_check_explicit_processdeps "p" "afterok:"
    [ "${status}" -eq 1 ]
    run debasher::_check_explicit_processdeps "p" ":a"
    [ "${status}" -eq 1 ]
}

@test "debasher::_check_explicit_processdeps refuses both separators in one list" {
    run debasher::_check_explicit_processdeps "p" "afterok:a,afterok:b?afterok:c"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"use one of them"* ]]
}

@test "debasher::_get_procdeps_for_process adds no dependency on a file when the callback returns none" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/a.txt"]="writer${sep}0"
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/b.txt"]="other${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["reader"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-a${DEBASHER_ARG_SEP}/abs/a.txt${DEBASHER_ARG_SEP}-b${DEBASHER_ARG_SEP}/abs/b.txt"
    }
    reader_define_opt_deps() {
        [ "$2" = "writer" ] && echo "none"
        return 0
    }

    run debasher::_get_procdeps_for_process "" "reader"
    [ "${status}" -eq 0 ]
    [ "${output}" = "afterok:other" ]
}

@test "debasher::_get_procdeps_for_process merges the dependencies of every task of an array on several producers" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    # prod is an array whose task i writes /abs/p<i>; single writes /abs/s
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/p0"]="prod${sep}0"
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/p1"]="prod${sep}1"
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/s"]="single${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["prod"]=2
    DEBASHER_PROCESS_OPT_LIST_LEN["single"]=1
    DEBASHER_PROCESS_OPT_LIST_LEN["cons"]=2
    # Task i of cons reads /abs/p<i>, and task 0 also reads /abs/s, so the
    # two tasks list different dependencies
    debasher::_get_opts_for_process_and_task() {
        if [ "$3" -eq 0 ]; then
            echo "-p${DEBASHER_ARG_SEP}/abs/p0${DEBASHER_ARG_SEP}-s${DEBASHER_ARG_SEP}/abs/s"
        else
            echo "-p${DEBASHER_ARG_SEP}/abs/p1"
        fi
    }

    run debasher::_get_procdeps_for_process "" "cons"
    [ "${status}" -eq 0 ]
    local -a deps
    IFS=, read -r -a deps <<< "${output}"
    [ "${#deps[@]}" -eq 2 ]
    [[ " ${deps[*]} " == *" aftercorr:prod "* ]]
    # single is not an array, so task 0 of cons cannot pair with a task of
    # it
    [[ " ${deps[*]} " == *" afterok:single "* ]]
}

@test "debasher::_get_procdeps_for_process fails when the tasks of an array ask for contradictory types on one producer" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    DEBASHER_OUT_VALUE_TO_PROCESSES["/abs/s"]="single${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["cons"]=2
    debasher::_get_opts_for_process_and_task() {
        echo "-s${DEBASHER_ARG_SEP}/abs/s${DEBASHER_ARG_SEP}-i${DEBASHER_ARG_SEP}$3"
    }
    # Task 0 waits for single to succeed, task 1 for it to fail
    cons_define_opt_deps() {
        if [ "${DEBASHER_DESERIALIZED_ARGS[3]}" = "0" ]; then
            echo "afterok"
        else
            echo "afternotok"
        fi
    }

    run debasher::_get_procdeps_for_process "" "cons"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"cannot both be satisfied"* ]]
}

# --- options: names, values, flags ------------------------------------------

@test "debasher::_str_is_option takes a dash followed by a letter or an underscore for an option, and a negative number for a value" {
    local opt
    for opt in -a --out -_x --b1; do
        debasher::_str_is_option "${opt}" || { echo "not an option: ${opt}"; return 1; }
    done
    for opt in -5 -0.5 --1 - "" value; do
        ! debasher::_str_is_option "${opt}" || { echo "an option: ${opt}"; return 1; }
    done
}

@test "debasher::define_opt refuses an option name that does not start with a letter or an underscore" {
    local optlist=""
    run debasher::define_opt "-5" "x" optlist
    [ "${status}" -ne 0 ]
}

@test "debasher::read_opt_value_from_func_args reads a negative number and an empty value" {
    [ "$(debasher::read_opt_value_from_func_args -n -n -5 -e '' -f)" = "-5" ]
    [ "$(debasher::read_opt_value_from_func_args -e -n -5 -e '' -f)" = "" ]
    [ "$(debasher::read_opt_value_from_func_args -f -n -5 -e '' -f)" = "${DEBASHER_VOID_VALUE}" ]
}

@test "save_opt_list keeps a negative value, an empty value, and a flag given last" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    valproc_define_opts()
    {
        local optlist=""
        define_opt "-n" "-5" optlist || return 1
        define_opt "-e" "" optlist || return 1
        define_flag "-f" optlist || return 1
        save_opt_list optlist
    }
    set +e
    valproc_define_opts "" "" valproc "${BATS_TEST_TMPDIR}"
    set -e

    local -n list="$(debasher::_get_opt_list_name valproc 0)"
    [ "${list[-n]}" = "-5" ]
    [[ -v list[-e] ]]
    [ "${list[-e]}" = "" ]
    [ "${list[-f]}" = "${DEBASHER_VOID_VALUE}" ]

    # The options a task receives keep the empty value and the flag apart
    set +e
    debasher::_load_curr_opt_list_loop "" valproc
    set -e
    debasher::_deserialize_args "${DEBASHER_CURRENT_PROCESS_OPT_LIST[0]}"
    [ "$(debasher::read_opt_value_from_func_args -e "${DEBASHER_DESERIALIZED_ARGS[@]}")" = "" ]
    [ "$(debasher::read_opt_value_from_func_args -f "${DEBASHER_DESERIALIZED_ARGS[@]}")" = "${DEBASHER_VOID_VALUE}" ]
    [ "$(debasher::read_opt_value_from_func_args -n "${DEBASHER_DESERIALIZED_ARGS[@]}")" = "-5" ]
}

@test "debasher::_sep_serialized_to_qstr prints an empty value as an empty quoted word" {
    local sargs="-e${DEBASHER_ARG_SEP}${DEBASHER_ARG_SEP}-f"
    run debasher::_sep_serialized_to_qstr "${DEBASHER_ARG_SEP}" "${sargs}"
    [ "${output}" = "-e '' -f " ]
    run debasher::_sep_serialized_to_qstr "${DEBASHER_ARG_SEP}" ""
    [ "${output}" = "" ]
}

@test "debasher::_print_program_opts shows the type of each option" {
    declare -gA DEBASHER_PROGRAM_OPT_DESC=() DEBASHER_PROGRAM_OPT_TYPE=() DEBASHER_PROGRAM_OPT_CATEG=()
    declare -gA DEBASHER_PROGRAM_CATEG_MAP=() DEBASHER_PROGRAM_OPT_IS_CMDLINE=()
    typedproc_explain_opts()
    {
        explain_opt "-s" "<string>" "String to show"
    }
    typedproc_explain_opts

    run debasher::_print_program_opts 0
    [[ "${output}" == *"-s <string> String to show [typedproc]"* ]]
}

@test "debasher::_print_program_opts lists a task shaping option among the command-line options, marked as such" {
    declare -gA DEBASHER_PROGRAM_OPT_DESC=() DEBASHER_PROGRAM_OPT_TYPE=() DEBASHER_PROGRAM_OPT_CATEG=()
    declare -gA DEBASHER_PROGRAM_CATEG_MAP=() DEBASHER_PROGRAM_OPT_IS_CMDLINE=()
    declare -gA DEBASHER_PROGRAM_OPT_IS_TASK_SHAPING=()
    listshapeproc_explain_opts()
    {
        explain_opt "-id" "<int>" "task id"
    }
    listshapeproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "Number of workers"
    }
    listshapeproc_explain_opts
    listshapeproc_explain_task_shaping_opts

    run debasher::_print_program_cmdline_opts
    [[ "${output}" == *"-w <int> Number of workers [listshapeproc, task shaping]"* ]]
    [[ "${output}" != *"-id"* ]]
}

# --- process of the caller -------------------------------------------------

@test "debasher::_get_processname_from_caller prefers a registered process over a helper named like a method" {
    declare -gA DEBASHER_PROGRAM_PROCESSES=(["myproc"]=1)
    io_define_opts()
    {
        debasher::_get_processname_from_caller "_define_opts"
    }
    myproc_define_opts()
    {
        io_define_opts
    }

    run myproc_define_opts
    [ "${output}" = "myproc" ]
}

@test "debasher::_is_valid_processname names the method a process name collides with" {
    run debasher::_is_valid_processname "proc_define_opts"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"collides with method '_define_opts'"* ]]
}

# --- one owner and one reader per fifo --------------------------------------

@test "define_fifo_opt refuses two tasks of an array that define fifos with the same name" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_FIFO_MIRRORED=()
    declare -gA DEBASHER_FIFO_KINDS=() DEBASHER_FIFO_OWNER_OPTS=()
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    samefifo_define_opts()
    {
        local idx
        for (( idx = 0; idx < 2; idx++ )); do
            local optlist=""
            define_fifo_opt "-outf" "samename" optlist || return 1
            save_opt_list optlist
        done
    }

    run samefifo_define_opts "" "" samefifo "${BATS_TEST_TMPDIR}"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"fifo samename of process samefifo is defined by task 0 and by task 1"* ]]
}

@test "define_fifo_opt_generator may define the fifo of a task again, as a generator runs several times" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_FIFO_MIRRORED=()
    declare -gA DEBASHER_FIFO_KINDS=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    regen_generate_opts()
    {
        local optlist=""
        define_fifo_opt_generator "-outf" "regen_$5" "$5" optlist || return 1
    }

    regen_generate_opts "" "" regen "${BATS_TEST_TMPDIR}" 1
    run regen_generate_opts "" "" regen "${BATS_TEST_TMPDIR}" 1
    [ "${status}" -eq 0 ]
}

@test "define_fifo_opt refuses --mirror on an option that is not an output option" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_FIFO_MIRRORED=()
    declare -gA DEBASHER_FIFO_KINDS=() DEBASHER_FIFO_OWNER_OPTS=()
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    mirrin_define_opts()
    {
        local optlist=""
        define_fifo_opt "-inf" "watched" optlist --mirror || return 1
    }

    run mirrin_define_opts "" "" mirrin "${BATS_TEST_TMPDIR}"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"its option -inf is not an output option"* ]]
}

@test "debasher::_register_fifos_read_by_process refuses a second reader of a fifo" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_READERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_READER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname writer out)"
    DEBASHER_PROGRAM_FIFOS["writer/out"]="writer${sep}0"
    DEBASHER_FIFO_READERS["writer/out"]="${DEBASHER_EXTERNAL_FIFO_END}"
    DEBASHER_FIFO_OWNER_OPTS["writer/out"]="-outf"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="writer${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["reader1"]=1
    DEBASHER_PROCESS_OPT_LIST_LEN["reader2"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-inf${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_read_by_process "" "reader1"
    local status1=$?
    set -e
    [ "${status1}" -eq 0 ]
    # Registering the same reader again is not an error
    run debasher::_register_fifos_read_by_process "" "reader1"
    [ "${status}" -eq 0 ]
    run debasher::_register_fifos_read_by_process "" "reader2"
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"is read by reader1 task 0 (option -inf) and by reader2 task 0 (option -inf); a fifo has a single reader"* ]]
}

# --- debasher::_check_opt_names_vs_explain, command-line options ---------
#
# A command-line option takes its value from the command line and
# nowhere else. An optional one may be left out of its process's tasks,
# since it may be defined only if given; a mandatory one left out is
# warned about, since an option that only shapes the tasks (a task count
# only read to build them, as host1 does with -n in
# debasher_host_process.sh) is declared as a task shaping option.

@test "debasher::_check_opt_names_vs_explain accepts a command-line option defined from the command line" {
    cmdokproc_explain_opts()
    {
        explain_opt "-n" "<int>" "desc n"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdokproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-n"]=1
    declare -gA DEBASHER_OPT_LIST_cmdokproc_0=(["-n"]="3")
    DEBASHER_PROGRAM_PROCESSES["cmdokproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain accepts a command-line file option normalized to its absolute path" {
    # debasher::_get_absolute_path, which gives the value its absolute
    # form, relies on the tool path the built engine's preamble defines
    REALPATH="$(command -v realpath)"

    cmdfileproc_explain_opts()
    {
        explain_opt "-f" "<file>" "desc f"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdfileproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-f"]=1
    declare -gA DEBASHER_OPT_LIST_cmdfileproc_0=(["-f"]="$(pwd)/input.txt")
    DEBASHER_PROGRAM_PROCESSES["cmdfileproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-f" "input.txt")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain accepts a command-line flag given on the command line" {
    cmdflagproc_explain_opts()
    {
        explain_flag "-v" "desc v"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdflagproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-v"]=1
    declare -gA DEBASHER_OPT_LIST_cmdflagproc_0=(["-v"]="")
    DEBASHER_PROGRAM_PROCESSES["cmdflagproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-v")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain aborts when a command-line option is defined with a value of its own" {
    cmdownproc_explain_opts()
    {
        explain_opt "-f" "<string>" "desc f"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdownproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-f"]=1
    declare -gA DEBASHER_OPT_LIST_cmdownproc_0=(["-f"]="prefix_part1")
    DEBASHER_PROGRAM_PROCESSES["cmdownproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-f" "prefix_")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process cmdownproc defines command-line option -f with a value that does not come from the command line"* ]]
}

@test "debasher::_check_opt_names_vs_explain aborts when a command-line option not given on the command line is defined anyway" {
    cmdmissproc_explain_opts()
    {
        explain_opt "-t" "<int>" "desc t"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdmissproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-t"]=1
    declare -gA DEBASHER_OPT_LIST_cmdmissproc_0=(["-t"]="/some/fifo")
    DEBASHER_PROGRAM_PROCESSES["cmdmissproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process cmdmissproc defines command-line option -t with a value that does not come from the command line"* ]]
}

@test "debasher::_check_opt_names_vs_explain aborts when identify_cmdline_opts marks an option that explain_opts does not declare" {
    strayproc_explain_opts()
    {
        explain_opt "-n" "<int>" "desc n"
    }
    strayproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-n"
        opt_is_cmdline "-value"
    }
    declare -gA DEBASHER_OPT_LIST_strayproc_0=(["-n"]="3")
    DEBASHER_PROGRAM_PROCESSES["strayproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process strayproc marks option -value in its identify_cmdline_opts, but does not declare it in its explain_opts"* ]]
    [[ "${output}" != *"option -n"* ]]
}

@test "debasher::_check_opt_names_vs_explain does not warn about an optional command-line option left out of the tasks" {
    cmdoptproc_explain_opts()
    {
        explain_opt "-n" "<int>" "defined only if given"
        explain_opt "-id" "<int>" "task id"
    }
    cmdoptproc_identify_cmdline_opts()
    {
        opt_is_non_mandatory_cmdline "-n"
    }
    declare -gA DEBASHER_OPT_LIST_cmdoptproc_0=(["-id"]="0")
    DEBASHER_PROGRAM_PROCESSES["cmdoptproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain does not warn about a mandatory command-line flag left out of the tasks" {
    cmdflagoutproc_explain_opts()
    {
        explain_flag "-v" "defined only if given"
    }
    cmdflagoutproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-v"
    }
    declare -gA DEBASHER_OPT_LIST_cmdflagoutproc_0=()
    DEBASHER_PROGRAM_PROCESSES["cmdflagoutproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain warns about a mandatory command-line option left out of the tasks, and suggests a task shaping option" {
    cmdshapeproc_explain_opts()
    {
        explain_opt "-n" "<int>" "number of tasks"
        explain_opt "-id" "<int>" "task id"
    }
    cmdshapeproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-n"
    }
    declare -gA DEBASHER_OPT_LIST_cmdshapeproc_0=(["-id"]="0")
    DEBASHER_PROGRAM_PROCESSES["cmdshapeproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"Warning: process cmdshapeproc declares mandatory command-line option -n in explain_opts, but it was not found among the options generated for its first task"* ]]
    [[ "${output}" == *"is declared in cmdshapeproc_explain_task_shaping_opts instead"* ]]
}

# --- task shaping options -------------------------------------------------
#
# A task shaping option is read only by the methods that define the
# options of a process, to decide its tasks, and no task receives it. It
# is declared in explain_task_shaping_opts alone, and is always a
# mandatory command-line option.

@test "debasher::_get_task_shaping_opt_names collects the names that explain_task_shaping_opts declares" {
    shapenamesproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
        explain_task_shaping_opt "-pref" "<string>" "prefix of the files"
    }

    local -A shaping=()
    debasher::_get_task_shaping_opt_names "shapenamesproc" shaping
    [ "${#shaping[@]}" -eq 2 ]
    [[ -v shaping["-w"] ]]
    [[ -v shaping["-pref"] ]]
}

@test "debasher::_get_task_shaping_opt_names leaves the set empty for a process without explain_task_shaping_opts" {
    local -A shaping=()
    debasher::_get_task_shaping_opt_names "noshapeproc" shaping
    [ "${#shaping[@]}" -eq 0 ]
}

@test "debasher::_get_explained_opt_names leaves out the task shaping options" {
    mixedproc_explain_opts()
    {
        explain_opt "-id" "<int>" "task id"
    }
    mixedproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    mixedproc_explain_task_shaping_opts

    local -A explained=()
    debasher::_get_explained_opt_names "mixedproc" explained
    [ "${#explained[@]}" -eq 1 ]
    [[ -v explained["-id"] ]]
}

@test "debasher::_check_task_shaping_opts_given accepts a task shaping option given on the command line" {
    givenproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-w" "3")

    run debasher::_check_task_shaping_opts_given "${cmdline}" "givenproc"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_task_shaping_opts_given refuses a task shaping option missing from the command line" {
    missingproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-x" "3")

    run debasher::_check_task_shaping_opts_given "${cmdline}" "missingproc"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process missingproc needs the task shaping option -w, which was not given on the command line"* ]]
}

@test "debasher::_check_opt_names_vs_explain accepts a task shaping option that no task receives" {
    shapeokproc_explain_opts()
    {
        explain_opt "-id" "<int>" "task id"
    }
    shapeokproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    declare -gA DEBASHER_OPT_LIST_shapeokproc_0=(["-id"]="0")
    DEBASHER_PROGRAM_PROCESSES["shapeokproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-w" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain aborts when an option is declared both in explain_opts and as a task shaping option" {
    shapebothproc_explain_opts()
    {
        explain_opt "-w" "<int>" "number of workers"
    }
    shapebothproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    declare -gA DEBASHER_OPT_LIST_shapebothproc_0=()
    DEBASHER_PROGRAM_PROCESSES["shapebothproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-w" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process shapebothproc declares option -w both in its explain_opts and in its explain_task_shaping_opts"* ]]
}

@test "debasher::_check_opt_names_vs_explain aborts when a task shaping option is marked in identify_cmdline_opts" {
    shapemarkproc_explain_opts()
    {
        :
    }
    shapemarkproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    shapemarkproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-w"
    }
    declare -gA DEBASHER_OPT_LIST_shapemarkproc_0=()
    DEBASHER_PROGRAM_PROCESSES["shapemarkproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-w" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process shapemarkproc marks its task shaping option -w in its identify_cmdline_opts"* ]]
    [[ "${output}" != *"does not declare it in its explain_opts"* ]]
}

@test "debasher::_check_opt_names_vs_explain aborts when a task defines a task shaping option" {
    shapedefproc_explain_opts()
    {
        :
    }
    shapedefproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    declare -gA DEBASHER_OPT_LIST_shapedefproc_0=(["-w"]="3")
    DEBASHER_PROGRAM_PROCESSES["shapedefproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-w" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process shapedefproc defines its task shaping option -w for its first task"* ]]
    [[ "${output}" != *"not declared in its explain_opts"* ]]
}

@test "debasher::_show_proc_opts shows the task shaping options apart from the others" {
    showshapeproc_explain_opts()
    {
        explain_opt "-id" "<int>" "task id"
    }
    showshapeproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-w" "<int>" "number of workers"
    }
    showshapeproc_explain_opts
    showshapeproc_explain_task_shaping_opts

    run debasher::_show_proc_opts "showshapeproc"
    [[ "${output}" == *"-id"* ]]
    [[ "${output}" != *"-w"* ]]

    run debasher::_show_proc_opts "showshapeproc" 1
    [[ "${output}" == *'- `-w` <int> number of workers (command-line,mandatory)'* ]]
    [[ "${output}" != *"-id"* ]]
}

# --- the number of tasks of another process -------------------------------

# Empties the registries that defining the options of a program fills, and
# makes the processes given the processes of the program
init_num_tasks_program() {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    declare -gA DEBASHER_PROGRAM_PROCESSES=() DEBASHER_INITIAL_PROCESS_SPEC=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local processname
    for processname in "$@"; do
        DEBASHER_INITIAL_PROCESS_SPEC["${processname}"]="${processname} cpus=1 mem=32 time=00:01:00"
        DEBASHER_PROGRAM_PROCESSES["${processname}"]=1
    done
}

# Defines the option list of one task, with the given task index as -id,
# and records the process whose options are being defined
record_definition() {
    local processname=$1
    local task_idx=$2
    local optlist=""

    echo "${processname}" >> "${BATS_TEST_TMPDIR}/order"
    define_opt "-id" "${task_idx}" optlist || return 1
    save_opt_list optlist
}

@test "debasher::_define_opts_for_program_processes defines every process without an option generator before any with one" {
    # Names whose order in an associative array mixes the two kinds, so that
    # a single loop over the processes would define a generator first
    init_num_tasks_program "one_arr" "one_gen" "two_arr" "two_gen" "three_arr" "three_gen"
    local name
    for name in one_arr two_arr three_arr; do
        eval "${name}_define_opts() { record_definition ${name} 0; }"
    done
    for name in one_gen two_gen three_gen; do
        eval "${name}_generate_opts_size() { echo 1; }"
        eval "${name}_generate_opts() { record_definition ${name} \"\$5\"; }"
    done

    set +e
    debasher::_define_opts_for_program_processes ""
    local status=$?
    set -e
    [ "${status}" -eq 0 ]

    run cat "${BATS_TEST_TMPDIR}/order"
    [ "${#lines[@]}" -eq 6 ]
    local i
    for i in 0 1 2; do
        [[ "${lines[$i]}" == *_arr ]]
    done
    for i in 3 4 5; do
        [[ "${lines[$i]}" == *_gen ]]
    done
}

@test "debasher::get_process_num_tasks gives an option generator the number of tasks of a process without one" {
    init_num_tasks_program "countedarrproc" "askinggenproc"
    countedarrproc_define_opts()
    {
        local task_idx
        for task_idx in 0 1 2; do
            record_definition "countedarrproc" "${task_idx}" || return 1
        done
    }
    askinggenproc_generate_opts_size()
    {
        get_process_num_tasks "countedarrproc"
    }
    askinggenproc_generate_opts()
    {
        record_definition "askinggenproc" "$5"
    }

    set +e
    debasher::_define_opts_for_program_processes ""
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["askinggenproc"]}" -eq 3 ]
}

@test "debasher::get_process_num_tasks takes the number of tasks of an option generator not defined yet from its _generate_opts_size method" {
    init_num_tasks_program "sizedgenproc" "gatherproc"
    sizedgenproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-n" "<int>" "number of tasks"
    }
    sizedgenproc_generate_opts_size()
    {
        read_opt_value_from_line "$1" "-n"
    }
    sizedgenproc_generate_opts()
    {
        record_definition "sizedgenproc" "$5"
    }
    gatherproc_define_opts()
    {
        local n
        n=$(get_process_num_tasks "sizedgenproc") || return 1
        echo "${n}" > "${BATS_TEST_TMPDIR}/gathered"
        record_definition "gatherproc" 0
    }
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "4")

    set +e
    debasher::_define_opts_for_program_processes "${cmdline}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "$(cat "${BATS_TEST_TMPDIR}/gathered")" -eq 4 ]
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["sizedgenproc"]}" -eq 4 ]
}

@test "debasher::get_process_num_tasks needs the task shaping options of the option generator whose number of tasks it computes" {
    init_num_tasks_program "shapedgenproc" "gatherproc"
    shapedgenproc_explain_task_shaping_opts()
    {
        explain_task_shaping_opt "-n" "<int>" "number of tasks"
    }
    shapedgenproc_generate_opts_size()
    {
        touch "${BATS_TEST_TMPDIR}/size_called"
        echo 2
    }
    shapedgenproc_generate_opts()
    {
        record_definition "shapedgenproc" "$5"
    }
    gatherproc_define_opts()
    {
        local n
        n=$(get_process_num_tasks "shapedgenproc") || return 1
        record_definition "gatherproc" 0
    }

    run debasher::_define_opts_for_program_processes "$(debasher::_serialize_args "debasher_exec")"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process shapedgenproc needs the task shaping option -n"* ]]
    [ ! -e "${BATS_TEST_TMPDIR}/size_called" ]
}

@test "debasher::get_process_num_tasks refuses the number of tasks of a process without an option generator while those are defined, even when its options are" {
    init_num_tasks_program "definedarrproc"
    definedarrproc_define_opts()
    {
        record_definition "definedarrproc" 0
    }
    DEBASHER_PROCESS_OPT_LIST_LEN["definedarrproc"]=2
    local DEBASHER_DEFINING_NON_GENERATOR_OPTS=1

    run debasher::get_process_num_tasks "definedarrproc"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"process definedarrproc has no option generator"* ]]
}

@test "debasher::get_process_num_tasks reads the number of tasks of any process once the options of the program are defined" {
    init_num_tasks_program "readarrproc" "readgenproc"
    readarrproc_define_opts()
    {
        record_definition "readarrproc" 0
    }
    readgenproc_generate_opts_size()
    {
        echo 99
    }
    DEBASHER_PROCESS_OPT_LIST_LEN["readarrproc"]=2
    DEBASHER_PROCESS_OPT_LIST_LEN["readgenproc"]=5

    run debasher::get_process_num_tasks "readarrproc"
    [ "${status}" -eq 0 ]
    [ "${output}" = "2" ]

    run debasher::get_process_num_tasks "readgenproc"
    [ "${status}" -eq 0 ]
    [ "${output}" = "5" ]
}

@test "debasher::get_process_num_tasks fails for an option generator not defined yet once the run is no longer prepared" {
    init_num_tasks_program "latergenproc"
    latergenproc_generate_opts_size()
    {
        echo 3
    }

    run debasher::get_process_num_tasks "latergenproc"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"the number of tasks of process latergenproc is not known yet"* ]]
}

@test "debasher::get_process_num_tasks fails for a process that is not a process of the program" {
    init_num_tasks_program "knownproc"

    run debasher::get_process_num_tasks "unknownproc"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"unknownproc is not a process of the program"* ]]
}

@test "debasher::get_process_num_tasks stops a number of tasks that depends on itself" {
    init_num_tasks_program "cyclegena" "cyclegenb"
    cyclegena_generate_opts_size()
    {
        get_process_num_tasks "cyclegenb"
    }
    cyclegena_generate_opts()
    {
        record_definition "cyclegena" "$5"
    }
    cyclegenb_generate_opts_size()
    {
        get_process_num_tasks "cyclegena"
    }
    cyclegenb_generate_opts()
    {
        record_definition "cyclegenb" "$5"
    }

    run debasher::_define_opts_for_program_processes ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"depends on itself (cyclegena -> cyclegenb -> cyclegena)"* || "${output}" == *"depends on itself (cyclegenb -> cyclegena -> cyclegenb)"* ]]
}

@test "debasher::_define_opts_for_process stops when the _generate_opts_size method prints something else than a number" {
    init_num_tasks_program "wordgenproc"
    wordgenproc_generate_opts_size()
    {
        echo "three"
    }
    wordgenproc_generate_opts()
    {
        record_definition "wordgenproc" "$5"
    }

    run debasher::_define_opts_for_process "" "${DEBASHER_INITIAL_PROCESS_SPEC["wordgenproc"]}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *'printed "three" instead of a number of tasks'* ]]
}

@test "debasher::_define_opts_for_process stops when the _generate_opts_size method fails" {
    init_num_tasks_program "failgenproc"
    failgenproc_generate_opts_size()
    {
        echo 2
        return 1
    }
    failgenproc_generate_opts()
    {
        record_definition "failgenproc" "$5"
    }

    run debasher::_define_opts_for_process "" "${DEBASHER_INITIAL_PROCESS_SPEC["failgenproc"]}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"the _generate_opts_size method of process failgenproc failed"* ]]
    [ ! -e "${BATS_TEST_TMPDIR}/order" ]
}

# --- debasher::_show_proc_implem_heredoc ---------------------------------

@test "debasher::_show_proc_implem_heredoc shows the source of a heredoc function" {
    fnproc_heredoc_py()
    {
        cat <<'PYEOF'
import sys
print(sys.argv)
PYEOF
    }

    run debasher::_show_proc_implem_heredoc fnproc
    [ "${status}" -eq 0 ]
    [ "${output}" = $'```python\nimport sys\nprint(sys.argv)\n```' ]
}

@test "debasher::_show_proc_implem_heredoc shows the source of the heredoc function of a namespaced process" {
    mymodule.nsproc_heredoc_r()
    {
        cat <<'REOF'
print(commandArgs())
REOF
    }

    run debasher::_show_proc_implem_heredoc mymodule.nsproc
    [ "${status}" -eq 0 ]
    [ "${output}" = $'```r\nprint(commandArgs())\n```' ]
}

@test "debasher::_show_proc_implem_heredoc shows the source of a legacy heredoc variable" {
    varproc_py=$'import sys\nprint(sys.argv)'

    run debasher::_show_proc_implem_heredoc varproc
    [ "${status}" -eq 0 ]
    [ "${output}" = $'```python\nimport sys\nprint(sys.argv)\n```' ]
}

# --- sequential processes in the documentation ------------------------

@test "debasher::_collect_func_deps leaves out a sequential process that the function runs as a step" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF2'
seqstep()
{
    :
}

main_proc()
{
    seq_execute seqstep
}
EOF2
    declare -gA DEBASHER_SEQ_PROCESSES=([seqstep]="${DEBASHER_REGULAR_PROCESS_TYPE}")

    result=$(collect_deps "${scriptfile}" "main_proc")
    [ "${result}" = "" ]
}

@test "debasher::_show_seq_process_documentation shows the description, specifications and implementation of a sequential process" {
    declare -gA DEBASHER_SEQ_PROCESSES=([seqstep]="${DEBASHER_HEREDOC_PROCESS_TYPE}")
    declare -gA DEBASHER_SEQ_PROCESS_SPEC=([seqstep]="seqstep cpus=2;mem=64 ${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP} ")
    seqstep_document() { echo "Adds two."; }
    seqstep_heredoc_py() { echo 'print(1 + 1)'; }

    run debasher::_show_seq_process_documentation seqstep 1 1
    [ "${status}" -eq 0 ]
    [[ "${output}" == "## Sequential Process: seqstep"* ]]
    [[ "${output}" == *$'### Description\nAdds two.'* ]]
    [[ "${output}" == *'- `cpus`: 2'* ]]
    [[ "${output}" == *'- `mem`: 64'* ]]
    [[ "${output}" == *$'```python\nprint(1 + 1)\n```'* ]]
}

@test "debasher::_show_seq_process_documentation shows what a sequential process alias runs" {
    declare -gA DEBASHER_SEQ_PROCESSES=([seqalias]="${DEBASHER_ALIAS_PROCESS_TYPE}")
    declare -gA DEBASHER_SEQ_PROCESS_SPEC=([seqalias]="seqalias ${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP} alias=target")
    declare -gA DEBASHER_PROCESS_ALIAS_TARGETS=([seqalias]="target")
    target_heredoc_r() { echo 'print(2)'; }

    run debasher::_show_seq_process_documentation seqalias 1 1
    [ "${status}" -eq 0 ]
    [[ "${output}" == *'- `alias`: target'* ]]
    [[ "${output}" == *$'```r\nprint(2)\n```'* ]]
    [[ "${output}" != *"Warning"* ]]
}
