#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_sched_rerun.sh, the functions that
# decide which processes debasher_exec runs again, run against the
# artifacts generated by engine/Makefile.am's suffix rule (not the .sh
# sources), so they exercise what actually ships.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # debasher_lib.sh declares its arrays for a script's top level; inside
    # setup() a bare declare would be local to it, so force them global.
    declare -gA DEBASHER_RERUN_PROCESSES=()
    declare -gA DEBASHER_PROGRAM_PROCESSES=()
    declare -gA DEBASHER_FINAL_PROCESS_SPEC=()
    declare -ga DEBASHER_PROGRAM_MODULES=()
}

# --- rerun due to a code update --------------------------------------------

@test "debasher::_define_rerun_processes_due_to_code_update marks a finished process whose script is older than a module" {
    local outd="${BATS_TEST_TMPDIR}/out"
    local module="${BATS_TEST_TMPDIR}/mod.sh"
    DEBASHER_PROGRAM_PROCESSES["oldproc"]=1
    DEBASHER_PROGRAM_PROCESSES["newproc"]=1
    DEBASHER_PROGRAM_MODULES=("${module}")
    mkdir -p "${outd}/__exec__/oldproc" "${outd}/__exec__/newproc"
    touch -d "2020-01-01" "${outd}/__exec__/oldproc/oldproc"
    touch -d "2020-01-03" "${outd}/__exec__/newproc/newproc"
    touch -d "2020-01-02" "${module}"
    debasher::_get_process_status() {
        echo "${DEBASHER_FINISHED_PROCESS_STATUS}"
    }

    debasher::_define_rerun_processes_due_to_code_update "${outd}" 2> "${BATS_TEST_TMPDIR}/stderr"

    [ "${DEBASHER_RERUN_PROCESSES["oldproc"]}" = "${DEBASHER_OUTDATED_CODE_RERUN_REASON}" ]
    [ -z "${DEBASHER_RERUN_PROCESSES["newproc"]+x}" ]
    ! grep -q "command not found" "${BATS_TEST_TMPDIR}/stderr"
}

# --- forced rerun ---------------------------------------------------------

@test "debasher::_define_forced_rerun_processes marks only the processes with force=yes" {
    local sep="${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP}"
    DEBASHER_FINAL_PROCESS_SPEC["forced"]="forced cpus=1 mem=32 time=00:01:00 ${sep} force=yes"
    DEBASHER_FINAL_PROCESS_SPEC["plain"]="plain cpus=1 mem=32 time=00:01:00"

    debasher::_define_forced_rerun_processes

    [ "${DEBASHER_RERUN_PROCESSES["forced"]}" = "${DEBASHER_FORCED_RERUN_REASON}" ]
    [ -z "${DEBASHER_RERUN_PROCESSES["plain"]+x}" ]
}

@test "debasher::_define_forced_rerun_processes prints no error for an empty force attribute" {
    local sep="${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP}"
    DEBASHER_FINAL_PROCESS_SPEC["emptyforce"]="emptyforce cpus=1 mem=32 time=00:01:00 ${sep} force="

    run debasher::_define_forced_rerun_processes
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}
