#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_mirror.sh's fifo mirror tap, run
# against the artifact generated by engine/Makefile.am's suffix rule
# (not the .sh source), so they exercise what actually ships.
#
# debasher::_run_fifo_mirror_tap forwards a mirrored fifo's traffic
# using real fifos and a real background process, not mocks: these
# tests pin down that a single persistent open of the real fifo (no
# fork per line any more) still works correctly against both kinds of
# reader that exist in this codebase -- one that reopens the real fifo
# per line, and one that opens it once and reads a continuous stream --
# and survives the case where the reopening reader is fully detached
# (SIGPIPE) at the exact moment the tap tries to write.
#
# Each test's own writes into the shim fifo go through one independent
# background `printf > shim` job per line (helper below), matching how
# a real owning process writes to a mirrored option today: a fresh
# open() blocks until the tap's own repeated-open shim read attaches,
# it never risks the SIGPIPE-on-a-momentary-gap hazard a *persistent*
# writer would (that hazard is real, but only for a writer that stays
# open across messages -- exactly what was checked and fixed on the
# tap's real-fifo side above, not something to reintroduce here on the
# shim side just to make the tests themselves simpler).

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"

    # debasher::_run_fifo_mirror_tap's write-retry loop shells out to
    # "${SLEEP}", normally supplied by the tool-path preamble the
    # Makefile suffix rule prepends -- absent here since this sources
    # the plain .sh source directly (see lib_programs.bats for why).
    SLEEP="$(command -v sleep)"

    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    shimfifo="${BATS_TEST_TMPDIR}/shim"
    realfifo="${BATS_TEST_TMPDIR}/real"
    mirrorfile="${BATS_TEST_TMPDIR}/mirror.log"
    mkfifo "${shimfifo}" "${realfifo}"
    : > "${mirrorfile}"
}

teardown() {
    if [ -n "${tap_pid:-}" ] && kill -0 "${tap_pid}" 2>/dev/null; then
        kill -9 "${tap_pid}" 2>/dev/null
    fi
}

# Sends one line into the shim fifo from its own background job, a
# fresh open/write/close (see file header for why this matters).
write_to_shim() {
    { printf '%s\n' "$1" > "${shimfifo}"; } &
}

@test "debasher::_run_fifo_mirror_tap forwards multiple lines to a reader that reopens the real fifo per line" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "one"
    local got1 got2
    got1=$(IFS= read -r line < "${realfifo}" && printf '%s' "${line}")

    write_to_shim "two"
    got2=$(IFS= read -r line < "${realfifo}" && printf '%s' "${line}")

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]
    [ "${got1}" = "one" ]
    [ "${got2}" = "two" ]
}

@test "debasher::_run_fifo_mirror_tap keeps the real fifo open across multiple messages for a reader with a single persistent open" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    (
        exec 4<"${realfifo}"
        IFS= read -r l1 <&4
        IFS= read -r l2 <&4
        printf '%s\n%s\n' "${l1}" "${l2}" > "${readerout}"
    ) &
    local reader_pid=$!

    write_to_shim "alpha"
    write_to_shim "beta"
    wait "${reader_pid}"

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"

    run cat "${readerout}"
    [ "${lines[0]}" = "alpha" ]
    [ "${lines[1]}" = "beta" ]
}

@test "debasher::_run_fifo_mirror_tap writes every forwarded line to the mirror file, in order" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "first"
    IFS= read -r _ < "${realfifo}"
    write_to_shim "second"
    IFS= read -r _ < "${realfifo}"

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"

    run cat "${mirrorfile}"
    [ "${lines[0]}" = "first" ]
    [ "${lines[1]}" = "second" ]
}

@test "debasher::_run_fifo_mirror_tap survives a reader that fully detaches between messages instead of dying to SIGPIPE" {
    # A reader that reopens the real fifo per line (stream_echo/
    # echo_fifo's own idiom, and Talk-to-FIFOs' repeated-open polling)
    # is, by construction, fully detached during the gap between one
    # close and the next open. Forced here with no reader running at
    # all while the second message is sent, so the tap's write is
    # guaranteed to land in that gap.
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "one"
    IFS= read -r _ < "${realfifo}"

    # No reader at all right now: the tap's write of "two" must not
    # kill it.
    write_to_shim "two"
    "${SLEEP}" 0.3
    kill -0 "${tap_pid}"

    # A reader finally attaches: the retried write must still get
    # through, not be silently dropped.
    local got
    got=$(timeout 5 bash -c "IFS= read -r line < '${realfifo}' && printf '%s' \"\${line}\"")
    [ "${got}" = "two" ]

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]
}

@test "debasher::_run_fifo_mirror_tap closes the real fifo's write end on the stop token, so an already-attached reader sees a real EOF" {
    # Opening a fifo for reading blocks until a writer is present, and
    # only a reader already attached when the last writer closes ever
    # observes EOF (a fresh open afterwards just blocks again, waiting
    # for a new writer) -- so the reader here has to attach before the
    # tap is told to stop, matching how FBPProcess's own persistent
    # reader is already attached throughout a real run.
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    local readerstatus="${BATS_TEST_TMPDIR}/reader_status"
    (
        exec 4<"${realfifo}"
        cat <&4 > "${readerout}"
        echo "$?" > "${readerstatus}"
    ) &
    local reader_pid=$!

    write_to_shim "only"
    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]

    wait "${reader_pid}"

    run cat "${readerstatus}"
    [ "${output}" = "0" ]
    run cat "${readerout}"
    [ "${output}" = "only" ]
}
