#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_processes.sh's process-implementation
# recovery helpers, run against the artifact generated by engine/
# Makefile.am's suffix rule (not the .sh source), so they exercise what
# actually ships. These pin down the exact false-positive/false-negative
# shapes found while debugging the frontend's "import program" feature
# (see debasher::_collect_func_deps's own comments): a same-script helper
# a process's exec function really calls must be pulled in, while a mere
# identifier collision -- a local variable, or a word inside a string or
# an embedded other-language script -- must not.
#
# The explain_opts-vs-actual-opts helpers further down (see
# debasher::_check_opt_names_vs_explain's own comments) reach into
# explain_opt/define_opt/save_opt_list and friends from
# debasher_lib_opts.sh, so setup() sources the whole engine/
# dependency chain (still entirely from ENGINE_BUILDDIR, via
# debasher_lib.sh's own include section) rather than just
# debasher_lib_processes on its own.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"
    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    # bats runs setup() as a function body, and debasher_lib.sh's own
    # top-level "declare -A ..." lines are written assuming they run
    # at a real script's top level (as they do in production, where
    # debasher_exec.sh sources debasher_lib outside of any function):
    # a bare "declare" inside a function is local to that function, so
    # without this, DEBASHER_PROGRAM_OPT_TYPE & co would silently
    # vanish the moment setup() returns, before any @test body ran.
    # Force them global here instead.
    declare -gA DEBASHER_PROGRAM_OPT_DESC
    declare -gA DEBASHER_PROGRAM_OPT_TYPE
    declare -gA DEBASHER_PROGRAM_OPT_IS_CMDLINE
    declare -gA DEBASHER_PROGRAM_OPT_IS_MANDATORY
    declare -gA DEBASHER_MEMOIZED_OPTS
    declare -gA DEBASHER_PROGRAM_OPT_CATEG
    declare -gA DEBASHER_PROGRAM_CATEG_MAP
    declare -gA DEBASHER_INITIAL_PROCESS_SPEC
    declare -gA DEBASHER_PROGRAM_PROCESSES
    declare -g DEBASHER_PROGRAM_OUTDIR
}

# --- debasher::_blank_string_literals --------------------------------

@test "debasher::_blank_string_literals blanks a single-quoted span" {
    result=$(printf 'before %s after\n' "'count'" | debasher::_blank_string_literals)
    [ "${result}" = "before  after" ]
}

@test "debasher::_blank_string_literals blanks a single-quoted span spanning multiple lines" {
    result=$(printf 'before %s\nmiddle\n%s after\n' "'" "'" | debasher::_blank_string_literals)
    [ "${result}" = "before  after" ]
}

@test "debasher::_blank_string_literals blanks a double-quoted span with no dollar sign" {
    result=$(printf 'echo "no count here"\n' | debasher::_blank_string_literals)
    [ "${result}" = 'echo ' ]
}

@test "debasher::_blank_string_literals keeps a double-quoted span containing a dollar sign" {
    line='echo "value is $count here"'
    result=$(printf '%s\n' "${line}" | debasher::_blank_string_literals)
    [ "${result}" = "${line}" ]
}

# --- debasher::_declared_func_vars ------------------------------------

@test "debasher::_declared_func_vars lists local variable names, not their assigned values" {
    eval 'sample() { local numblocks=$(some_func "$1"); local i start_line count blockfile; count=$(( 1 + 2 )); }'

    run debasher::_declared_func_vars sample
    [ "${status}" -eq 0 ]
    [[ "${lines[*]}" == *"numblocks"* ]]
    [[ "${lines[*]}" == *"i"* ]]
    [[ "${lines[*]}" == *"count"* ]]
    [[ "${lines[*]}" == *"blockfile"* ]]
    # The call on the right-hand side of a declaration is a real
    # dependency, not a declared name -- it must not show up here.
    [[ "${lines[*]}" != *"some_func"* ]]
}

# --- debasher::_collect_func_deps -------------------------------------

# Sources $1 (a here-doc'd script written to a real file, since
# debasher::_collect_func_deps needs "declare -F" -- via extdebug -- to
# report a defining file on disk) and prints the space-joined set of
# dependencies debasher::_collect_func_deps collects for funcname $2,
# funcname itself excluded. Each fixture below has at most one real
# dependency, so this doesn't bother sorting the result.
collect_deps() {
    local scriptfile=$1
    local funcname=$2

    shopt -s extdebug
    source "${scriptfile}"
    local -A seen=()
    debasher::_collect_func_deps "${funcname}" "${scriptfile}" seen
    shopt -u extdebug

    local dep
    local -a deps=()
    for dep in "${!seen[@]}"; do
        [ "${dep}" = "${funcname}" ] && continue
        deps+=("${dep}")
    done
    echo "${deps[*]}"
}

@test "debasher::_collect_func_deps pulls in a helper the exec function actually calls" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
helper()
{
    :
}

main_proc()
{
    helper
}
EOF

    result=$(collect_deps "${scriptfile}" "main_proc")
    [ "${result}" = "helper" ]
}

@test "debasher::_collect_func_deps ignores a local variable that collides with a sibling process name" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
count()
{
    :
}

fragment()
{
    local i count
    count=$(( 1 + 1 ))
    echo "${count}"
}
EOF

    result=$(collect_deps "${scriptfile}" "fragment")
    [ -z "${result}" ]
}

@test "debasher::_collect_func_deps ignores a sibling process name that only appears in an embedded string/script" {
    local scriptfile="${BATS_TEST_TMPDIR}/script.sh"
    cat > "${scriptfile}" <<'EOF'
count()
{
    :
}

count_chars()
{
    awk '
        {
            count[$1]++
        }
        END {
            for (c in count) print c, count[c]
        }
    '
}

worker_task()
{
    count_chars "$1"
}
EOF

    result=$(collect_deps "${scriptfile}" "worker_task")
    [ "${result}" = "count_chars" ]
}

# --- debasher::_get_explained_opt_names --------------------------------

@test "debasher::_get_explained_opt_names collects names declared via explain_opt and explain_flag" {
    modernproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_flag "-f" "desc f"
    }

    local -A explained=()
    debasher::_get_explained_opt_names "modernproc" explained
    [ "${#explained[@]}" -eq 2 ]
    [[ -v explained["-a"] ]]
    [[ -v explained["-f"] ]]
}

@test "debasher::_get_explained_opt_names also collects names declared via the legacy explain_cmdline_opts" {
    legacyproc_explain_cmdline_opts()
    {
        explain_cmdline_opt "-x" "<string>" "desc x"
    }

    local -A explained=()
    debasher::_get_explained_opt_names "legacyproc" explained
    [ "${#explained[@]}" -eq 1 ]
    [[ -v explained["-x"] ]]
}

@test "debasher::_get_explained_opt_names keeps the command-line marks that identify_cmdline_opts set" {
    markedproc_explain_opts()
    {
        explain_opt "-n" "<int>" "desc n"
        explain_flag "-v" "desc v"
    }
    markedproc_identify_cmdline_opts()
    {
        opt_is_cmdline "-n"
        opt_is_non_mandatory_cmdline "-v"
    }
    markedproc_explain_opts
    markedproc_identify_cmdline_opts

    local -A explained=()
    debasher::_get_explained_opt_names "markedproc" explained
    [ "${DEBASHER_PROGRAM_OPT_IS_CMDLINE["markedproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-n"]}" = 1 ]
    [ "${DEBASHER_PROGRAM_OPT_IS_CMDLINE["markedproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-v"]}" = 1 ]
}

@test "debasher::_get_explained_opt_names returns 1 and leaves the set empty when the process declares no explain function" {
    local -A explained=()
    ! debasher::_get_explained_opt_names "noexplainproc" explained
    [ "${#explained[@]}" -eq 0 ]
}

# --- debasher::_get_actual_opt_names_for_first_task ---------------------

@test "debasher::_get_actual_opt_names_for_first_task reads the per-task array already populated for a non-generator process" {
    declare -gA DEBASHER_OPT_LIST_readerproc_0=(["-a"]="1" ["-f"]="")

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "readerproc" actual
    [ "${#actual[@]}" -eq 2 ]
    [[ -v actual["-a"] ]]
    [[ -v actual["-f"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task leaves the set empty when no task was ever recorded for a non-generator process" {
    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "notaskproc" actual
    [ "${#actual[@]}" -eq 0 ]
}

@test "debasher::_get_actual_opt_names_for_first_task calls generate_opts once for a generator process and extracts its option names" {
    genproc_generate_opts_size()
    {
        echo 1
    }

    genproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist
        define_flag "-verbose" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc"]="genproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc" actual
    [ "${#actual[@]}" -eq 2 ]
    [[ -v actual["-id"] ]]
    [[ -v actual["-verbose"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task keeps each option's value, and none for a flag, for a generator process" {
    genvalproc_generate_opts_size()
    {
        echo 1
    }

    genvalproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-f" "a file with spaces" optlist
        define_flag "-verbose" optlist
        define_opt "-id" "${task_idx}" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genvalproc"]="genvalproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genvalproc" actual
    [ "${#actual[@]}" -eq 3 ]
    [ "${actual["-f"]}" = "a file with spaces" ]
    [ -z "${actual["-verbose"]}" ]
    [ "${actual["-id"]}" = "0" ]
}

@test "debasher::_get_actual_opt_names_for_first_task fails when generate_opts fails for a generator process" {
    genfailproc_generate_opts_size()
    {
        echo 1
    }

    genfailproc_generate_opts()
    {
        return 1
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genfailproc"]="genfailproc"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    ! debasher::_get_actual_opt_names_for_first_task "" "genfailproc" actual
}

@test "debasher::_get_actual_opt_names_for_first_task keeps generator option names that echo would take as its own flags" {
    genproc3_generate_opts_size()
    {
        echo 1
    }

    genproc3_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-n" "4" optlist
        define_opt "-e" "x" optlist
        define_flag "-E" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc3"]="genproc3"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc3" actual
    [ "${#actual[@]}" -eq 3 ]
    [[ -v actual["-n"] ]]
    [[ -v actual["-e"] ]]
    [[ -v actual["-E"] ]]
}

@test "debasher::_get_actual_opt_names_for_first_task's extra generate_opts call leaves no DEBASHER_OPT_LIST_* array behind" {
    genproc2_generate_opts_size()
    {
        echo 1
    }

    genproc2_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist
        save_opt_list optlist
    }

    DEBASHER_INITIAL_PROCESS_SPEC["genproc2"]="genproc2"
    DEBASHER_PROGRAM_OUTDIR="/tmp/bats-debasher-outdir"

    local -A actual=()
    debasher::_get_actual_opt_names_for_first_task "" "genproc2" actual

    ! declare -p DEBASHER_OPT_LIST_genproc2_0 >/dev/null 2>&1
}

# --- debasher::_check_opt_names_vs_explain -------------------------------

@test "debasher::_check_opt_names_vs_explain succeeds silently when defined and declared option names match" {
    cleanproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_flag "-f" "desc f"
    }
    declare -gA DEBASHER_OPT_LIST_cleanproc_0=(["-a"]="1" ["-f"]="")
    DEBASHER_PROGRAM_PROCESSES["cleanproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain aborts when a process defines an option its explain_opts never declared" {
    badproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
    }
    declare -gA DEBASHER_OPT_LIST_badproc_0=(["-a"]="1" ["-x"]="")
    DEBASHER_PROGRAM_PROCESSES["badproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process badproc defines option -x, which is not declared in its explain_opts"* ]]
}

@test "debasher::_check_opt_names_vs_explain only warns, and still succeeds, when a declared option is missing from the first task" {
    warnproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
        explain_opt "-b" "<int>" "desc b, only given via define_cmdline_opt_if_given"
    }
    declare -gA DEBASHER_OPT_LIST_warnproc_0=(["-a"]="1")
    DEBASHER_PROGRAM_PROCESSES["warnproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"Warning: process warnproc declares option -b in explain_opts, but it was not found among the options generated for its first task"* ]]
}

# --- debasher::_check_opt_names_vs_explain, "ith" option families -------
#
# A process whose number of "-foo0", "-foo1", ... "-foo<N-1>" options
# depends on a run-time value (N, e.g. a worker count) cannot
# explain_opt each instance by its literal name, so by convention it
# documents the whole family once, as "-fooith" (see
# dispatch_define_opts/aggregate_define_opts in
# debasher_dynamic_fanout.sh for the real pattern this mirrors).

@test "debasher::_check_opt_names_vs_explain does not error on an actual option that is a concrete instance of a declared ith family" {
    ithproc_explain_opts()
    {
        explain_opt "-outfith" "<file>" "desc, one per worker"
    }
    declare -gA DEBASHER_OPT_LIST_ithproc_0=(["-outf0"]="a" ["-outf1"]="b")
    DEBASHER_PROGRAM_PROCESSES["ithproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain does not warn about a declared ith family that has a concrete instance" {
    ithwarnproc_explain_opts()
    {
        explain_opt "-outfith" "<file>" "desc, one per worker"
    }
    declare -gA DEBASHER_OPT_LIST_ithwarnproc_0=(["-outf0"]="a")
    DEBASHER_PROGRAM_PROCESSES["ithwarnproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain still errors on a numeric-suffixed option with no matching ith family declared" {
    notithproc_explain_opts()
    {
        explain_opt "-a" "<int>" "desc a"
    }
    declare -gA DEBASHER_OPT_LIST_notithproc_0=(["-a"]="1" ["-x1"]="")
    DEBASHER_PROGRAM_PROCESSES["notithproc"]=1

    run debasher::_check_opt_names_vs_explain ""
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process notithproc defines option -x1, which is not declared in its explain_opts"* ]]
}

# --- define_fifo_opt in an array defined in a loop ---------------------

@test "debasher::define_fifo_opt registers each fifo of an array defined in a loop as owned by its own task" {
    declare -gA DEBASHER_PROGRAM_FIFOS DEBASHER_FIFO_USERS DEBASHER_FIFO_MIRRORED
    declare -gA DEBASHER_FIFO_KINDS DEBASHER_FIFO_OWNER_OPTS
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN DEBASHER_OUT_VALUE_TO_PROCESSES
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    loopfifoproc_define_opts()
    {
        local idx
        for (( idx = 0; idx < 3; idx++ )); do
            local optlist=""
            define_fifo_opt "-outf" "loopfifoproc_out_${idx}" optlist || return 1
            save_opt_list optlist
        done
    }
    # save_opt_list relies on lookups that return 1 in the ordinary case (no
    # option generator), which bats's errexit would treat as a failure.
    set +e
    loopfifoproc_define_opts "" "" "loopfifoproc" "${BATS_TEST_TMPDIR}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]

    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_0"]}" = "loopfifoproc${sep}0" ]
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_1"]}" = "loopfifoproc${sep}1" ]
    [ "${DEBASHER_PROGRAM_FIFOS["loopfifoproc/loopfifoproc_out_2"]}" = "loopfifoproc${sep}2" ]
}

@test "debasher::_define_opts_for_process registers the fifos of a generator even when all process dependencies were given" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_USERS=() DEBASHER_FIFO_MIRRORED=()
    declare -gA DEBASHER_FIFO_KINDS=() DEBASHER_FIFO_OWNER_OPTS=()
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    genfifoproc_generate_opts_size()
    {
        echo 3
    }

    genfifoproc_generate_opts()
    {
        local cmdline=$1
        local process_spec=$2
        local process_name=$3
        local process_outdir=$4
        local task_idx=$5
        local optlist=""

        define_fifo_opt_generator "-outf" "genfifoproc_out_${task_idx}" "${task_idx}" optlist || return 1
        save_opt_list optlist
    }

    local spec="genfifoproc cpus=1 mem=32 time=00:01:00 ${DEBASHER_BEGIN_OF_ADDITIONAL_PROCSPECS_SEP} processdeps=none"
    DEBASHER_INITIAL_PROCESS_SPEC["genfifoproc"]="${spec}"
    DEBASHER_PROGRAM_PROCESSES["genfifoproc"]=1

    set +e
    debasher::_define_opts_for_process "" "${spec}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]

    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["genfifoproc"]}" -eq 3 ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_0"]}" = "genfifoproc${sep}0" ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_1"]}" = "genfifoproc${sep}1" ]
    [ "${DEBASHER_PROGRAM_FIFOS["genfifoproc/genfifoproc_out_2"]}" = "genfifoproc${sep}2" ]

    # The readers of each fifo are found through the output values of its
    # owner task, so those have to be recorded as well
    local fifo="$(debasher::_get_absolute_fifoname genfifoproc genfifoproc_out_1)"
    [ "${DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]}" = "genfifoproc${sep}1" ]
}

@test "debasher::_define_opts_for_process takes the process name from the given process spec, not from a variable of its caller" {
    declare -gA DEBASHER_PROCESS_OPT_LIST_LEN=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"

    genonlyproc_generate_opts_size()
    {
        echo 2
    }

    genonlyproc_generate_opts()
    {
        local task_idx=$5
        local optlist=""

        define_opt "-id" "${task_idx}" optlist || return 1
        save_opt_list optlist
    }

    local spec="genonlyproc cpus=1 mem=32 time=00:01:00"
    DEBASHER_INITIAL_PROCESS_SPEC["genonlyproc"]="${spec}"

    # A caller whose own processname variable names another process, one
    # without a generator
    local processname="loopproc"
    set +e
    debasher::_define_opts_for_process "" "${spec}"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_PROCESS_OPT_LIST_LEN["genonlyproc"]}" -eq 2 ]
    [ -z "${DEBASHER_PROCESS_OPT_LIST_LEN["loopproc"]+x}" ]
}

# --- users of the fifos --------------------------------------------------

@test "debasher::_deserialized_args_idx_is_dep_candidate writes the option index into the caller's variable j" {
    declare -gA DEBASHER_OUT_VALUE_TO_PROCESSES=(["/abs/fifo"]="fanin")
    DEBASHER_DESERIALIZED_ARGS=("-n" "3" "-from_fanin" "/abs/fifo")
    # The callers name their variable j, as here
    caller() {
        local j=""
        debasher::_deserialized_args_idx_is_dep_candidate 3 j || return 1
        echo "${j}"
    }

    run caller
    [ "${status}" -eq 0 ]
    [ "${output}" = "2" ]
}

@test "debasher::_register_fifos_used_by_process registers the reader of a fifo that its owner writes" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_USERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_USER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname fanin fanin_to_loop)"
    DEBASHER_PROGRAM_FIFOS["fanin/fanin_to_loop"]="fanin${sep}0"
    DEBASHER_FIFO_USERS["fanin/fanin_to_loop"]="${DEBASHER_EXTERNAL_FIFO_USER}"
    # fanin writes it through its output option (-outloop, say)
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="fanin${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["loop"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-n${DEBASHER_ARG_SEP}3${DEBASHER_ARG_SEP}-from_fanin${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_used_by_process "" "loop"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_USERS["fanin/fanin_to_loop"]}" = "loop${sep}0" ]
    [ "${DEBASHER_FIFO_USER_OPTS["fanin/fanin_to_loop"]}" = "-from_fanin" ]
}

@test "debasher::_register_fifos_used_by_process registers another task of the same array as a user" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_USERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_USER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname worker worker_out_0)"
    DEBASHER_PROGRAM_FIFOS["worker/worker_out_0"]="worker${sep}0"
    DEBASHER_FIFO_USERS["worker/worker_out_0"]="${DEBASHER_EXTERNAL_FIFO_USER}"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="worker${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["worker"]=2
    # Task 0 writes the fifo, task 1 reads it.
    debasher::_get_opts_for_process_and_task() {
        if [ "$3" -eq 0 ]; then
            echo "-outnext${DEBASHER_ARG_SEP}${fifo}"
        else
            echo "-n${DEBASHER_ARG_SEP}3${DEBASHER_ARG_SEP}-from_prev${DEBASHER_ARG_SEP}${fifo}"
        fi
    }

    set +e
    debasher::_register_fifos_used_by_process "" "worker"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_USERS["worker/worker_out_0"]}" = "worker${sep}1" ]
    [ "${DEBASHER_FIFO_USER_OPTS["worker/worker_out_0"]}" = "-from_prev" ]
}

@test "debasher::_register_fifos_used_by_process registers the owner that reads its own fifo through another option (a self-loop)" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_USERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_USER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname counter counter_self)"
    DEBASHER_PROGRAM_FIFOS["counter/counter_self"]="counter${sep}0"
    DEBASHER_FIFO_USERS["counter/counter_self"]="${DEBASHER_EXTERNAL_FIFO_USER}"
    DEBASHER_FIFO_OWNER_OPTS["counter/counter_self"]="-outself"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="counter${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["counter"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-self${DEBASHER_ARG_SEP}${fifo}${DEBASHER_ARG_SEP}-outself${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_used_by_process "" "counter"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_USERS["counter/counter_self"]}" = "counter${sep}0" ]
    [ "${DEBASHER_FIFO_USER_OPTS["counter/counter_self"]}" = "-self" ]
}

@test "debasher::_register_fifos_used_by_process leaves outside the user of a fifo that its owner defines through an input option" {
    declare -gA DEBASHER_PROGRAM_FIFOS=() DEBASHER_FIFO_USERS=() DEBASHER_PROCESS_OPT_LIST_LEN=()
    declare -gA DEBASHER_FIFO_USER_OPTS=() DEBASHER_OUT_VALUE_TO_PROCESSES=() DEBASHER_FIFO_OWNER_OPTS=()
    DEBASHER_PROGRAM_OUTDIR="${BATS_TEST_TMPDIR}"
    local sep="${DEBASHER_ASSOC_ARRAY_ELEM_SEP}"
    local fifo="$(debasher::_get_absolute_fifoname fanin fanin_ext)"
    DEBASHER_PROGRAM_FIFOS["fanin/fanin_ext"]="fanin${sep}0"
    DEBASHER_FIFO_USERS["fanin/fanin_ext"]="${DEBASHER_EXTERNAL_FIFO_USER}"
    DEBASHER_FIFO_OWNER_OPTS["fanin/fanin_ext"]="-ext"
    DEBASHER_OUT_VALUE_TO_PROCESSES["${fifo}"]="fanin${sep}0"
    DEBASHER_PROCESS_OPT_LIST_LEN["fanin"]=1
    debasher::_get_opts_for_process_and_task() {
        echo "-ext${DEBASHER_ARG_SEP}${fifo}"
    }

    set +e
    debasher::_register_fifos_used_by_process "" "fanin"
    local status=$?
    set -e
    [ "${status}" -eq 0 ]
    [ "${DEBASHER_FIFO_USERS["fanin/fanin_ext"]}" = "${DEBASHER_EXTERNAL_FIFO_USER}" ]
    [ -z "${DEBASHER_FIFO_USER_OPTS["fanin/fanin_ext"]+x}" ]
}

# --- debasher::_check_opt_names_vs_explain, command-line options ---------
#
# A command-line option takes its value from the command line and
# nowhere else, and may be left out of its process's tasks (e.g. a task
# count only read to build them, as host1 does with -n in
# debasher_host_process.sh).

@test "debasher::_check_opt_names_vs_explain accepts a command-line option defined from the command line" {
    cmdokproc_explain_opts()
    {
        explain_opt "-n" "<int>" "desc n"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdokproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-n"]=1
    declare -gA DEBASHER_OPT_LIST_cmdokproc_0=(["-n"]="3")
    DEBASHER_PROGRAM_PROCESSES["cmdokproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain accepts a command-line file option normalized to its absolute path" {
    # debasher::_get_absolute_path, which gives the value its absolute
    # form, relies on the tool path the built engine's preamble defines
    REALPATH="$(command -v realpath)"

    cmdfileproc_explain_opts()
    {
        explain_opt "-f" "<file>" "desc f"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdfileproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-f"]=1
    declare -gA DEBASHER_OPT_LIST_cmdfileproc_0=(["-f"]="$(pwd)/input.txt")
    DEBASHER_PROGRAM_PROCESSES["cmdfileproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-f" "input.txt")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain accepts a command-line flag given on the command line" {
    cmdflagproc_explain_opts()
    {
        explain_flag "-v" "desc v"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdflagproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-v"]=1
    declare -gA DEBASHER_OPT_LIST_cmdflagproc_0=(["-v"]="")
    DEBASHER_PROGRAM_PROCESSES["cmdflagproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-v")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_opt_names_vs_explain aborts when a command-line option is defined with a value of its own" {
    cmdownproc_explain_opts()
    {
        explain_opt "-f" "<string>" "desc f"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdownproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-f"]=1
    declare -gA DEBASHER_OPT_LIST_cmdownproc_0=(["-f"]="prefix_part1")
    DEBASHER_PROGRAM_PROCESSES["cmdownproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-f" "prefix_")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process cmdownproc defines command-line option -f with a value that does not come from the command line"* ]]
}

@test "debasher::_check_opt_names_vs_explain aborts when a command-line option not given on the command line is defined anyway" {
    cmdmissproc_explain_opts()
    {
        explain_opt "-t" "<int>" "desc t"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdmissproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-t"]=1
    declare -gA DEBASHER_OPT_LIST_cmdmissproc_0=(["-t"]="/some/fifo")
    DEBASHER_PROGRAM_PROCESSES["cmdmissproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: process cmdmissproc defines command-line option -t with a value that does not come from the command line"* ]]
}

@test "debasher::_check_opt_names_vs_explain does not warn about a command-line option left out of the tasks" {
    cmdshapeproc_explain_opts()
    {
        explain_opt "-n" "<int>" "number of tasks"
        explain_opt "-id" "<int>" "task id"
    }
    DEBASHER_PROGRAM_OPT_IS_CMDLINE["cmdshapeproc${DEBASHER_ASSOC_ARRAY_ELEM_SEP}-n"]=1
    declare -gA DEBASHER_OPT_LIST_cmdshapeproc_0=(["-id"]="0")
    DEBASHER_PROGRAM_PROCESSES["cmdshapeproc"]=1
    local cmdline=$(debasher::_serialize_args "debasher_exec" "-n" "3")

    run debasher::_check_opt_names_vs_explain "${cmdline}"
    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}
