#!/usr/bin/env bats
#
# Sample unit tests for engine/debasher_lib_utils.sh, run against the
# artifact generated by engine/Makefile.am's suffix rule (not the .sh
# source), so they exercise what actually ships.

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    source "${ENGINE_BUILDDIR}/debasher_lib_utils"
}

@test "debasher::_str_is_natural_number accepts a natural number" {
    run debasher::_str_is_natural_number "42"
    [ "$status" -eq 0 ]
}

@test "debasher::_str_is_natural_number rejects a non-numeric string" {
    run debasher::_str_is_natural_number "42abc"
    [ "$status" -eq 1 ]
}

@test "debasher::_is_absolute_path accepts an absolute path" {
    run debasher::_is_absolute_path "/tmp/foo"
    [ "$status" -eq 0 ]
}

@test "debasher::_is_absolute_path rejects a relative path" {
    run debasher::_is_absolute_path "foo/bar"
    [ "$status" -eq 1 ]
}
