#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_mirror.sh's fifo mirror tap, run
# against the artifact generated by engine/Makefile.am's suffix rule
# (not the .sh source), so they exercise what actually ships.
#
# debasher::_run_fifo_mirror_tap forwards a mirrored fifo's traffic
# using real fifos and a real background process, not mocks: these
# tests pin down that a single persistent open of the real fifo (no
# fork per line any more) still works correctly against both kinds of
# reader that exist in this codebase -- one that reopens the real fifo
# per line, and one that opens it once and reads a continuous stream --
# and survives the case where the reopening reader is fully detached
# (SIGPIPE) at the exact moment the tap tries to write.
#
# A mirrored fifo has a single writer, its owning process, so the
# tests write into the shim fifo from one background job at a time
# (helpers below): two jobs started together would race, and the order
# in which their lines reach the tap would be left to chance. A job
# sends one line, or several in a single open, the way a process that
# prints several lines at once does.

# A test that hangs fails instead of hanging the whole suite: a tap that
# never stops is exactly what some of these tests guard against.
BATS_TEST_TIMEOUT=30

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
    debasher_pkglibdir="${ENGINE_BUILDDIR}"

    # debasher::_run_fifo_mirror_tap's write-retry loop shells out to
    # "${SLEEP}", normally supplied by the tool-path preamble the
    # Makefile suffix rule prepends -- absent here since this sources
    # the plain .sh source directly (see lib_programs.bats for why).
    SLEEP="$(command -v sleep)"

    source "${ENGINE_BUILDDIR}/debasher_lib.sh"

    shimfifo="${BATS_TEST_TMPDIR}/shim"
    realfifo="${BATS_TEST_TMPDIR}/real"
    mirrorfile="${BATS_TEST_TMPDIR}/mirror.log"
    mkfifo "${shimfifo}" "${realfifo}"
    : > "${mirrorfile}"
}

teardown() {
    if [ -n "${tap_pid:-}" ] && kill -0 "${tap_pid}" 2>/dev/null; then
        kill -9 "${tap_pid}" 2>/dev/null
    fi
}

# Sends one line into the shim fifo from its own background job, a
# fresh open/write/close (see file header for why this matters).
write_to_shim() {
    { printf '%s\n' "$1" > "${shimfifo}"; } &
}

# Sends every argument, one per line, from one background job in a
# single open/write/close.
write_lines_to_shim() {
    { printf '%s\n' "$@" > "${shimfifo}"; } &
}

@test "debasher::_run_fifo_mirror_tap forwards multiple lines to a reader that reopens the real fifo per line" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "one"
    local got1 got2
    got1=$(IFS= read -r line < "${realfifo}" && printf '%s' "${line}")

    write_to_shim "two"
    got2=$(IFS= read -r line < "${realfifo}" && printf '%s' "${line}")

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]
    [ "${got1}" = "one" ]
    [ "${got2}" = "two" ]
}

@test "debasher::_run_fifo_mirror_tap keeps the real fifo open across multiple messages for a reader with a single persistent open" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    (
        exec 4<"${realfifo}"
        IFS= read -r l1 <&4
        IFS= read -r l2 <&4
        printf '%s\n%s\n' "${l1}" "${l2}" > "${readerout}"
    ) &
    local reader_pid=$!

    write_lines_to_shim "alpha" "beta"
    wait "${reader_pid}"

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"

    run cat "${readerout}"
    [ "${lines[0]}" = "alpha" ]
    [ "${lines[1]}" = "beta" ]
}

@test "debasher::_run_fifo_mirror_tap forwards every line that a writer sends in a single open" {
    # The writer closes before the tap has read past the first line, and
    # the lines still waiting in the shim fifo must not be discarded with
    # it.
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    timeout 5 cat "${realfifo}" > "${readerout}" &
    local reader_pid=$!

    { printf 'a\nb\nc\n' > "${shimfifo}"; }
    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]
    wait "${reader_pid}"

    run cat "${readerout}"
    [ "${output}" = $'a\nb\nc' ]
    run cat "${mirrorfile}"
    [ "${output}" = $'a\nb\nc' ]
}

@test "debasher::_run_fifo_mirror_tap writes every forwarded line to the mirror file, in order" {
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "first"
    IFS= read -r _ < "${realfifo}"
    write_to_shim "second"
    IFS= read -r _ < "${realfifo}"

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"

    run cat "${mirrorfile}"
    [ "${lines[0]}" = "first" ]
    [ "${lines[1]}" = "second" ]
}

@test "debasher::_run_fifo_mirror_tap survives a reader that fully detaches between messages instead of dying to SIGPIPE" {
    # A reader that reopens the real fifo per line (stream_echo/
    # echo_fifo's own idiom, and Talk-to-FIFOs' repeated-open polling)
    # is, by construction, fully detached during the gap between one
    # close and the next open. Forced here with no reader running at
    # all while the second message is sent, so the tap's write is
    # guaranteed to land in that gap.
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    write_to_shim "one"
    IFS= read -r _ < "${realfifo}"

    # No reader at all right now: the tap's write of "two" must not
    # kill it.
    write_to_shim "two"
    "${SLEEP}" 0.3
    kill -0 "${tap_pid}"

    # A reader finally attaches: the retried write must still get
    # through, not be silently dropped.
    local got
    got=$(timeout 5 bash -c "IFS= read -r line < '${realfifo}' && printf '%s' \"\${line}\"")
    [ "${got}" = "two" ]

    write_to_shim "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]
}

@test "debasher::_run_fifo_mirror_tap closes the real fifo's write end on the stop token, so an already-attached reader sees a real EOF" {
    # Opening a fifo for reading blocks until a writer is present, and
    # only a reader already attached when the last writer closes ever
    # observes EOF (a fresh open afterwards just blocks again, waiting
    # for a new writer) -- so the reader here has to attach before the
    # tap is told to stop, matching how FBPProcess's own persistent
    # reader is already attached throughout a real run.
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!

    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    local readerstatus="${BATS_TEST_TMPDIR}/reader_status"
    (
        exec 4<"${realfifo}"
        cat <&4 > "${readerout}"
        echo "$?" > "${readerstatus}"
    ) &
    local reader_pid=$!

    write_lines_to_shim "only" "${DEBASHER_FIFO_MIRROR_STOP_TOKEN}"
    wait "${tap_pid}"
    [ "$?" -eq 0 ]

    wait "${reader_pid}"

    run cat "${readerstatus}"
    [ "${output}" = "0" ]
    run cat "${readerout}"
    [ "${output}" = "only" ]
}

# --- stopping the taps of a process ---------------------------------------

# Starts a tap the way debasher::_start_fifo_mirror_taps_for_process does,
# registering it for debasher::_stop_fifo_mirror_taps, from a shell that
# ignores SIGTERM like the wrapper of a real process, so that the tap
# inherits that.
start_registered_tap() {
    DEBASHER_FIFO_MIRROR_TAP_PIDS=()
    DEBASHER_FIFO_MIRROR_TAP_SHIMS=()
    trap '' TERM
    debasher::_run_fifo_mirror_tap "${shimfifo}" "${realfifo}" "${mirrorfile}" &
    tap_pid=$!
    trap - TERM
    DEBASHER_FIFO_MIRROR_TAP_PIDS+=("${tap_pid}")
    DEBASHER_FIFO_MIRROR_TAP_SHIMS+=("${shimfifo}")
}

# Waits until the mirror file holds $1 lines, which the tap writes before
# it forwards each line to the real fifo.
wait_for_mirror_lines() {
    local i
    for (( i = 0; i < 100; i++ )); do
        [ "$(wc -l < "${mirrorfile}")" -ge "$1" ] && return 0
        "${SLEEP}" 0.05
    done
    return 1
}

now_ms() {
    date +%s%3N
}

@test "debasher::_stop_fifo_mirror_taps stops a tap on its token at once, with no warning" {
    start_registered_tap
    local readerout="${BATS_TEST_TMPDIR}/reader_out"
    cat "${realfifo}" > "${readerout}" 3>&- &
    local reader_pid=$!
    write_to_shim "one"
    wait_for_mirror_lines 1

    local start=$(now_ms)
    debasher::_stop_fifo_mirror_taps 2> "${BATS_TEST_TMPDIR}/stderr"
    local status=$?
    local elapsed=$(( $(now_ms) - start ))

    [ "${status}" -eq 0 ]
    [ "${elapsed}" -lt 1000 ]
    [ ! -s "${BATS_TEST_TMPDIR}/stderr" ]
    ! kill -0 "${tap_pid}" 2>/dev/null
    wait "${reader_pid}"
    [ "$(cat "${readerout}")" = "one" ]
}

@test "debasher::_stop_fifo_mirror_taps ends a tap whose reader is gone, with a warning, and does not fail" {
    # The reader of the real fifo reads one line and leaves; the owning
    # process then writes another, which the tap can never forward, so it
    # never gets to the token.
    DEBASHER_FIFO_MIRROR_TAP_STOP_GRACE_SECS=1
    start_registered_tap
    write_lines_to_shim "one" "two"
    IFS= read -r _ < "${realfifo}"
    wait_for_mirror_lines 2

    local start=$(now_ms)
    debasher::_stop_fifo_mirror_taps 2> "${BATS_TEST_TMPDIR}/stderr"
    [ "$?" -eq 0 ]
    # SIGTERM ends it: the SIGKILL fallback would take a second grace period.
    [ $(( $(now_ms) - start )) -lt 2000 ]

    ! kill -0 "${tap_pid}" 2>/dev/null
    grep -q "Warning: fifo mirror tap for ${shimfifo} did not stop within 1s" "${BATS_TEST_TMPDIR}/stderr"
    run cat "${mirrorfile}"
    [ "${output}" = $'one\ntwo' ]
}

@test "debasher::_stop_fifo_mirror_taps ends a tap whose real fifo never got a reader" {
    # The tap is blocked opening the real fifo, which waits for a reader.
    DEBASHER_FIFO_MIRROR_TAP_STOP_GRACE_SECS=1
    start_registered_tap
    "${SLEEP}" 0.2

    local start=$(now_ms)
    debasher::_stop_fifo_mirror_taps 2> "${BATS_TEST_TMPDIR}/stderr"
    [ "$?" -eq 0 ]
    [ $(( $(now_ms) - start )) -lt 2000 ]

    ! kill -0 "${tap_pid}" 2>/dev/null
    grep -q "did not stop within 1s" "${BATS_TEST_TMPDIR}/stderr"
}

@test "debasher::_stop_fifo_mirror_taps ends a stuck tap even when its shim fifo is full" {
    # The token cannot even be written: the owning process filled the shim
    # behind a tap stuck on a reader that left. The stop must not block on
    # that write either.
    DEBASHER_FIFO_MIRROR_TAP_STOP_GRACE_SECS=1
    start_registered_tap
    write_to_shim "one"
    IFS= read -r _ < "${realfifo}"
    write_to_shim "two"
    wait_for_mirror_lines 2
    local filler
    filler=$(head -c 4000 /dev/zero | tr '\0' x)
    local k
    for (( k = 0; k < 20; k++ )); do
        { printf '%s\n' "${filler}" > "${shimfifo}"; } 3>&- &
    done
    "${SLEEP}" 0.3

    debasher::_stop_fifo_mirror_taps 2> "${BATS_TEST_TMPDIR}/stderr"
    [ "$?" -eq 0 ]

    ! kill -0 "${tap_pid}" 2>/dev/null
    grep -q "did not stop within 1s" "${BATS_TEST_TMPDIR}/stderr"
}

@test "debasher::_stop_fifo_mirror_taps still reports a tap that exited abnormally" {
    start_registered_tap
    kill -9 "${tap_pid}"
    "${SLEEP}" 0.1

    run debasher::_stop_fifo_mirror_taps
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"Error: fifo mirror tap for ${shimfifo} exited abnormally"* ]]
}

# --- resident programs refuse --mirror -------------------------------------
#
# The check happens as soon as the flag is seen, before define_fifo_opt
# needs any of the process-definition state a real module call provides,
# so these tests can exercise it directly.

@test "debasher::_check_fifo_mirror_allowed accepts --mirror in a general program" {
    DEBASHER_PROGRAM_TYPE="${DEBASHER_PROGRAM_TYPE_GENERAL}"

    run debasher::_check_fifo_mirror_allowed "define_fifo_opt"

    [ "${status}" -eq 0 ]
    [ -z "${output}" ]
}

@test "debasher::_check_fifo_mirror_allowed rejects --mirror in a resident program and names the caller" {
    DEBASHER_PROGRAM_TYPE="${DEBASHER_PROGRAM_TYPE_RESIDENT}"

    run debasher::_check_fifo_mirror_allowed "define_fifo_opt"

    [ "${status}" -eq 1 ]
    [[ "${output}" == *"define_fifo_opt: Error, --mirror cannot be used in a 'resident' program"* ]]
}

@test "debasher::define_fifo_opt aborts on --mirror in a resident program" {
    DEBASHER_PROGRAM_TYPE="${DEBASHER_PROGRAM_TYPE_RESIDENT}"

    run debasher::define_fifo_opt "-outf" "somefifo" optlist --mirror

    [ "${status}" -eq 1 ]
    [[ "${output}" == *"define_fifo_opt: Error, --mirror cannot be used in a 'resident' program"* ]]
}

@test "debasher::define_fifo_opt_generator aborts on --mirror in a resident program" {
    DEBASHER_PROGRAM_TYPE="${DEBASHER_PROGRAM_TYPE_RESIDENT}"

    run debasher::define_fifo_opt_generator "-outf" "somefifo" 0 optlist --mirror

    [ "${status}" -eq 1 ]
    [[ "${output}" == *"define_fifo_opt_generator: Error, --mirror cannot be used in a 'resident' program"* ]]
}
