#!/usr/bin/env bats
#
# Unit tests for engine/debasher_lib_sched.sh, run against the artifacts
# generated by engine/Makefile.am's suffix rule (not the .sh sources).

setup() {
    : "${ENGINE_BUILDDIR:?ENGINE_BUILDDIR must point at the built engine/ dir}"
}

# Writes the context from a bash that has loaded the engine and a small
# module, with an environment of its own, into ${BATS_TEST_TMPDIR}/ctx.sh.
# Every bash here is the one that runs the tests, ${BASH}, not the first
# one of a bare PATH, which may be older than the engine needs (that of
# macOS is); in it, BASH names that bash, as the preamble of a built
# script names the one that configure found
write_context() {
    local module="${BATS_TEST_TMPDIR}/mod.sh"
    cat > "${module}" <<'EOM'
MODULE_VALUE="from the module"
declare -A MODULE_MAP=([a key]="a value")
declare -A MODULE_EMPTY_MAP
declare MODULE_EMPTY_SCALAR
module_func() { echo "module function"; }
EOM
    env -i PATH="/usr/bin:/bin" HOME=/tmp FOREIGN_VAR=foreign DEBASHER_EXPORTED=kept \
        ENGINE_BUILDDIR="${ENGINE_BUILDDIR}" MODULE="${module}" CTX="${BATS_TEST_TMPDIR}/ctx.sh" \
        "${BASH}" -c '
            debasher_pkglibdir="${ENGINE_BUILDDIR}"
            CAT="$(command -v cat)"
            source "${ENGINE_BUILDDIR}/debasher_lib.sh"
            source "${MODULE}"
            exported_func() { :; }
            export -f exported_func
            declare -gA DEBASHER_OPT_LIST_proc_0=([-x]=1)
            debasher::_write_exec_context "${CTX}"
        '
}

@test "_write_exec_context writes the variables and functions of the module and the engine" {
    write_context

    grep -q '^declare -- MODULE_VALUE="from the module"$' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^module_func ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^debasher::_write_exec_context ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -x PATH=' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -x DEBASHER_EXPORTED="kept"$' "${BATS_TEST_TMPDIR}/ctx.sh"
}

@test "_write_exec_context leaves out bash's own, read-only and exported variables, and the options of each task" {
    write_context

    ! grep -q ' FOREIGN_VAR=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' HOME=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' UID=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' BASH_VERSINFO=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q ' RANDOM=' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q 'DEBASHER_OPT_LIST_proc_0' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q '^exported_func ()' "${BATS_TEST_TMPDIR}/ctx.sh"
    ! grep -q '^declare -[-a-zA-Z]* _ctx_' "${BATS_TEST_TMPDIR}/ctx.sh"
}

@test "_write_exec_context writes a context that a clean bash loads without errors" {
    write_context

    run env -i "${BASH}" -c "source '${BATS_TEST_TMPDIR}/ctx.sh' && echo \"\${MODULE_MAP[a key]}\" && module_func"
    [ "${status}" -eq 0 ]
    [ "${output}" = "$(printf 'a value\nmodule function')" ]
}

@test "_write_exec_context declares the variables that have no value yet, keeping the type of an associative array" {
    write_context

    grep -q '^declare -A MODULE_EMPTY_MAP$' "${BATS_TEST_TMPDIR}/ctx.sh"
    grep -q '^declare -- MODULE_EMPTY_SCALAR$' "${BATS_TEST_TMPDIR}/ctx.sh"
    # A key with a dot, as the name of a namespaced process has, reads as
    # an associative key, not as arithmetic
    run env -i "${BASH}" -c "source '${BATS_TEST_TMPDIR}/ctx.sh' && echo \"[\${MODULE_EMPTY_MAP[ns.proc]:-}]\""
    [ "${status}" -eq 0 ]
    [ "${output}" = "[]" ]
}

# Runs seq_execute_slurm from a bash that has loaded the engine, with an
# srun that records the script it is given and runs it here, so that no
# Slurm is needed. $1 is the text that the step writes, or "fail" for a
# step that fails. Leaves the path of the script in srun_arg and prints
# the exit code of seq_execute_slurm.
run_seq_execute_slurm() {
    local outd="${BATS_TEST_TMPDIR}/out"
    mkdir -p "${outd}/__exec__"
    cat > "${BATS_TEST_TMPDIR}/srun" <<EOS
#!${BASH}
echo "\$1" > "${BATS_TEST_TMPDIR}/srun_arg"
exec "\$@"
EOS
    chmod +x "${BATS_TEST_TMPDIR}/srun"
    env -i PATH="/usr/bin:/bin" HOME=/tmp ENGINE_BUILDDIR="${ENGINE_BUILDDIR}" \
        OUTD="${outd}" SRUN_STUB="${BATS_TEST_TMPDIR}/srun" STEP_ARG="$1" \
        "${BASH}" -c '
            debasher_pkglibdir="${ENGINE_BUILDDIR}"
            CAT="$(command -v cat)"
            MKTEMP="$(command -v mktemp)"
            RM="$(command -v rm)"
            SRUN="${SRUN_STUB}"
            source "${ENGINE_BUILDDIR}/debasher_lib.sh"
            step() { [ "$1" = fail ] && return 1; echo "step $1" > "$2"; }
            DEBASHER_PROGRAM_OUTDIR="${OUTD}"
            debasher::_write_exec_context "$(debasher::_get_exec_context_fname "${OUTD}")"
            seq_execute_slurm step "${STEP_ARG}" "${OUTD}/result.txt"
            echo "rc=$?"
        '
}

@test "seq_execute_slurm runs a function of the program through srun, from the output directory" {
    run run_seq_execute_slurm hello
    [ "$status" -eq 0 ]
    [ "$output" = "rc=0" ]
    [ "$(cat "${BATS_TEST_TMPDIR}/out/result.txt")" = "step hello" ]
    # The script was in the output directory of the program, which the
    # nodes of a cluster share, and is removed
    local script
    script=$(cat "${BATS_TEST_TMPDIR}/srun_arg")
    [[ "${script}" == "${BATS_TEST_TMPDIR}/out/__exec__/"* ]]
    [ ! -e "${script}" ]
}

@test "seq_execute_slurm fails when the step fails, and removes its script" {
    run run_seq_execute_slurm fail
    [ "$status" -eq 0 ]
    [ "$output" = "rc=1" ]
    [ ! -e "$(cat "${BATS_TEST_TMPDIR}/srun_arg")" ]
}

# Runs a command from a bash that has loaded the engine
run_with_engine() {
    env -i PATH="/usr/bin:/bin" HOME=/tmp ENGINE_BUILDDIR="${ENGINE_BUILDDIR}" \
        DIR="${BATS_TEST_TMPDIR}" CMD="$1" \
        "${BASH}" -c '
            debasher_pkglibdir="${ENGINE_BUILDDIR}"
            source "${ENGINE_BUILDDIR}/debasher_lib.sh"
            eval "${CMD}"
        '
}

@test "is_step_done tells a step marked with mark_step_done from one that is not" {
    run run_with_engine 'mark_step_done "${DIR}" 0_a.txt && is_step_done "${DIR}" 0_a.txt && ! is_step_done "${DIR}" 0_b.txt'
    [ "$status" -eq 0 ]
    [ -f "${BATS_TEST_TMPDIR}/DEBASHER_STEP_DONE_0_a.txt" ]
}

@test "mark_step_done fails when the step is already marked" {
    run run_with_engine 'mark_step_done "${DIR}" s && mark_step_done "${DIR}" s'
    [ "$status" -eq 1 ]
}
