"""
Script generation of a resident program (see "Script generation and import
of a resident program" in doc/design_doc_webui.md).

A resident program is generated by the same code as a general one, from a
copy of it that this module prepares (resident_program_for_generation):

- every node gets the Python heredoc assembled from the parts of its code,
  and the Supervisor its fixed class (see resident_node_code.py);
- the Supervisor wiring, which the program model never holds, is derived
  from whether the program has a Supervisor, from its nodes and from which
  of them are initiators, and added as options and connections, so that the
  options of the wiring are written by the same rules as those of the user
  (see resident_supervisor_wiring.py);
- what a resident program does not offer (the manual mode, value
  descriptors, shared directories, FIFO mirrors, additional specifications
  and methods) is refused, or left out.
"""

from .models import AdditionalMethods, AdditionalSpecs, Program, ProgramProcess
from .resident_node_code import node_heredoc, supervisor_heredoc
from .resident_supervisor_wiring import RESERVED_NODE_LABELS, SupervisorWiring


def _check_program(program: Program) -> None:
    """Refuses what a resident program does not offer."""
    supervisors = [p for p in program.processes if p.nodeKind == "Supervisor"]
    if len(supervisors) > 1:
        names = ", ".join(p.name for p in supervisors)
        raise ValueError(f"A resident program has at most one Supervisor, and this one has {names}.")
    for process in program.processes:
        if process.nodeKind is None:
            raise ValueError(
                f'Process "{process.name}" of a resident program has no node kind.'
            )
        if process.nodeKind == "Supervisor":
            if process.options:
                raise ValueError(
                    f'The Supervisor "{process.name}" takes no options of its own: script '
                    "generation writes all of them."
                )
            if process.optionsHandler.mode != "standard":
                raise ValueError(f'The Supervisor "{process.name}" cannot be an array or a generator.')
            continue
        if process.optionsHandler.mode == "manual":
            raise ValueError(
                f'Process "{process.name}" uses the manual mode of the options handler, which '
                "a resident program does not offer: the Supervisor wiring has to be added to "
                "the option definitions of every node."
            )
        for option in process.options:
            if option.label in RESERVED_NODE_LABELS:
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" has a label of the '
                    "Supervisor wiring, which script generation writes: rename it."
                )
            if option.channel in ("value_desc", "shared_dir"):
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" uses the option '
                    f'channel "{option.channel}", which a resident program does not offer: '
                    "a connection that is not a FIFO makes the reader wait for the writer "
                    "to finish."
                )
            if option.mirror:
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" is mirrored, and '
                    "the engine refuses --mirror in a resident program."
                )
            if option.fifoTag == "control":
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" has the fifo tag '
                    '"control", which only the Supervisor wiring takes.'
                )


def _write_code(process: ProgramProcess) -> None:
    """Writes a process as a Python heredoc, with none of the additional
    specifications, methods or group that a resident program leaves out."""
    process.language = "python"
    process.code = supervisor_heredoc(process) if process.nodeKind == "Supervisor" else node_heredoc(process)
    process.additionalSpecs = AdditionalSpecs(force=False)
    process.additionalMethods = AdditionalMethods()
    process.groupSource = None


def resident_program_for_generation(program: Program) -> Program:
    """
    A copy of the resident `program` ready for the script generation of a
    general one: every process written as a Python heredoc, with no
    additional specifications or methods, and the Supervisor wiring added as
    options and connections. Raises ValueError for what a resident program
    does not offer.
    """
    _check_program(program)
    program = program.model_copy(deep=True)
    for process in program.processes:
        _write_code(process)
    wiring = SupervisorWiring(program)
    for node in wiring.nodes:
        wiring.add_heartbeat(node)
        if node.initiator:
            wiring.add_control_port(node)
    wiring.finish()
    return program
