"""
Script generation of a resident program (see "Script generation and import
of a resident program" in doc/design_doc_webui.md).

A resident program is generated by the same code as a general one, from a
copy of it that this module prepares (resident_program_for_generation):

- every node gets the Python heredoc assembled from the parts of its code
  (node_heredoc), and the Supervisor its fixed class (supervisor_heredoc);
- the Supervisor wiring, which the program model never holds, is derived
  from whether the program has a Supervisor, from its nodes and from which
  of them are initiators, and added as options and connections, so that the
  options of the wiring are written by the same rules as those of the user;
- what a resident program does not offer (the manual mode, value
  descriptors, shared directories, FIFO mirrors, additional specifications
  and methods) is refused, or left out.
"""

import textwrap
import uuid

from .models import (
    AdditionalMethods,
    AdditionalSpecs,
    NodeCode,
    Program,
    ProgramEdge,
    ProgramOption,
    ProgramProcess,
)

INDENT = " " * 4

# The hooks of a node, in the order script generation writes them: the field
# of NodeCode that holds the body, the name of the method and its fixed
# parameters.
NODE_HOOKS = (
    ("processData", "process_data", "(self, port_name, packet)"),
    ("captureNodeState", "capture_node_state", "(self)"),
    ("restoreNodeState", "restore_node_state", "(self, node_state)"),
    ("initializeRuntime", "initialize_runtime", "(self)"),
    ("observe", "observe", "(self)"),
)

# The labels of the Supervisor wiring on a node, which no option of the user
# may take.
HEARTBEAT_LABEL = "-outhb"
TRIGGER_LABEL = "-trigger"
RESERVED_NODE_LABELS = (HEARTBEAT_LABEL, TRIGGER_LABEL)

# The labels of the Supervisor wiring on the Supervisor that do not depend
# on a node.
MANUAL_LABEL = "-manual"
NO_HOLD_FIFOS_LABEL = "-no_hold_fifos"

_TASK_INDEXED_MODES = {"array", "generator"}


def node_class_name(process_name: str) -> str:
    """
    The name of the class of a node, after its process, in CamelCase, as the
    engine requires: every part of the process name between dots and
    underscores, with its first letter in upper case ("counter" gives
    "Counter", "org.ns.count_words" gives "OrgNsCountWords").
    """
    parts = process_name.replace(".", "_").split("_")
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


def normalized_part(text: str) -> str:
    """
    A part of the code of a node as script generation writes it: without
    the indentation that all its lines share, and without blank lines at
    its start or its end.
    """
    lines = textwrap.dedent(text).splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def _indented(text: str, indent: str) -> str:
    return "\n".join(indent + line if line.strip() else "" for line in text.splitlines())


def node_heredoc(process: ProgramProcess) -> str:
    """
    The Python heredoc of a node: the import of its node kind, the node
    preamble, the class declaration, the class body, each hook that has a
    body with its fixed signature, and the line that runs the node.
    """
    kind = process.nodeKind
    name = node_class_name(process.name)
    code = process.nodeCode or NodeCode()

    lines = [f"from debasher_runtime_lib import {kind}"]
    preamble = normalized_part(code.preamble)
    if preamble:
        lines += ["", preamble]
    lines += ["", "", f"class {name}({kind}):"]

    blocks = []
    class_body = normalized_part(code.classBody)
    if class_body:
        blocks.append(_indented(class_body, INDENT))
    for field, hook, params in NODE_HOOKS:
        body = normalized_part(getattr(code, field))
        if body:
            blocks.append(f"{INDENT}def {hook}{params}:\n{_indented(body, INDENT * 2)}")
    lines.append("\n\n".join(blocks) if blocks else f"{INDENT}pass")

    lines += ["", "", f"{name}().run()"]
    return "\n".join(lines)


def supervisor_heredoc(process: ProgramProcess) -> str:
    """The Python heredoc of the Supervisor, which has no code of its own."""
    name = node_class_name(process.name)
    return "\n".join(
        [
            "from debasher_runtime_lib import Supervisor",
            "",
            "",
            f"class {name}(Supervisor):",
            f"{INDENT}pass",
            "",
            "",
            f"{name}().run()",
        ]
    )


def heartbeat_label(process_name: str) -> str:
    """The input of the Supervisor that reads the heartbeat channel of a node.
    The name of the process comes first, never last: "-hb_smith" would end
    in "ith" and be taken for a fanout family."""
    return f"-{process_name}_hb"


def trigger_label(process_name: str) -> str:
    """The output of the Supervisor that is the trigger port to an initiator."""
    return f"-out{process_name}_trig"


def _task_suffix(mode: str) -> str:
    """What a fifo name of a task adds, so that each task has its own."""
    if mode == "array":
        return "_${idx}"
    if mode == "generator":
        return "_${task_idx}"
    return ""


def _option(label, direction, description, **fields) -> ProgramOption:
    return ProgramOption(
        id=str(uuid.uuid4()),
        label=label,
        direction=direction,
        dataType=fields.pop("dataType", "string"),
        description=description,
        value=fields.pop("value", ""),
        commandLine=fields.pop("commandLine", False),
        **fields,
    )


def _connect(edges, source_process, source_option, target_process, target_option) -> None:
    """Connects two options of the copy of the program, as the frontend would:
    an edge, and the value of the target that names its source."""
    target_option.value = f"[{source_process.name};{source_option.label}]"
    edges.append(
        ProgramEdge(
            id=str(uuid.uuid4()),
            sourceProcessId=source_process.id,
            sourceOptionId=source_option.id,
            targetProcessId=target_process.id,
            targetOptionId=target_option.id,
        )
    )


def _is_fanout_label(label: str) -> bool:
    return label.endswith("ith") and label[: -len("ith")].lstrip("-") != ""


def _count_source(program: Program, node: ProgramProcess) -> ProgramOption:
    """
    The command line option that counts the tasks of an array or generator
    node: the one that counts the fanout family that the node is connected
    to, directly or through the tasks of another array. Raises ValueError
    when the node reaches no such family, since the Supervisor could not
    count its heartbeat channels.
    """
    processes_by_id = {process.id: process for process in program.processes}
    seen = {node.id}
    pending = [node]
    while pending:
        current = pending.pop()
        for edge in program.edges:
            if current.id not in (edge.sourceProcessId, edge.targetProcessId):
                continue
            if edge.sourceProcessId == current.id:
                other = processes_by_id.get(edge.targetProcessId)
                other_option_id = edge.targetOptionId
            else:
                other = processes_by_id.get(edge.sourceProcessId)
                other_option_id = edge.sourceOptionId
            if other is None or other.id in seen:
                continue
            if other.optionsHandler.mode in _TASK_INDEXED_MODES:
                seen.add(other.id)
                pending.append(other)
                continue
            other_option = next((o for o in other.options if o.id == other_option_id), None)
            if other_option is None or not _is_fanout_label(other_option.label):
                continue
            count = next((o for o in other.options if o.id == other_option.countSourceOptionId), None)
            if count is not None and count.commandLine:
                return count
    raise ValueError(
        f'Process "{node.name}" is an {node.optionsHandler.mode} node of a resident program '
        "with a Supervisor, but it reaches no fanout family counted by a command line "
        "option, directly or through the tasks of another array: the Supervisor could "
        "not tell how many heartbeat channels to read. Connect it to a fanout family "
        "whose count source is a command line option."
    )


def _check_program(program: Program) -> None:
    """Refuses what a resident program does not offer."""
    supervisors = [p for p in program.processes if p.nodeKind == "Supervisor"]
    if len(supervisors) > 1:
        names = ", ".join(p.name for p in supervisors)
        raise ValueError(f"A resident program has at most one Supervisor, and this one has {names}.")
    for process in program.processes:
        if process.nodeKind is None:
            raise ValueError(
                f'Process "{process.name}" of a resident program has no node kind.'
            )
        if process.nodeKind == "Supervisor":
            if process.options:
                raise ValueError(
                    f'The Supervisor "{process.name}" takes no options of its own: script '
                    "generation writes all of them."
                )
            if process.optionsHandler.mode != "standard":
                raise ValueError(f'The Supervisor "{process.name}" cannot be an array or a generator.')
            continue
        if process.optionsHandler.mode == "manual":
            raise ValueError(
                f'Process "{process.name}" uses the manual mode of the options handler, which '
                "a resident program does not offer: the Supervisor wiring has to be added to "
                "the option definitions of every node."
            )
        for option in process.options:
            if option.label in RESERVED_NODE_LABELS:
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" has a label of the '
                    "Supervisor wiring, which script generation writes: rename it."
                )
            if option.channel in ("value_desc", "shared_dir"):
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" uses the option '
                    f'channel "{option.channel}", which a resident program does not offer: '
                    "a connection that is not a FIFO makes the reader wait for the writer "
                    "to finish."
                )
            if option.mirror:
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" is mirrored, and '
                    "the engine refuses --mirror in a resident program."
                )
            if option.fifoTag == "control":
                raise ValueError(
                    f'Option "{option.label}" of process "{process.name}" has the fifo tag '
                    '"control", which only the Supervisor wiring takes.'
                )


def resident_program_for_generation(program: Program) -> Program:
    """
    A copy of the resident `program` ready for the script generation of a
    general one: every process written as a Python heredoc, with no
    additional specifications or methods, and the Supervisor wiring added as
    options and connections. Raises ValueError for what a resident program
    does not offer.
    """
    _check_program(program)
    program = program.model_copy(deep=True)

    for process in program.processes:
        process.language = "python"
        process.code = supervisor_heredoc(process) if process.nodeKind == "Supervisor" else node_heredoc(process)
        process.additionalSpecs = AdditionalSpecs(force=False)
        process.additionalMethods = AdditionalMethods()
        process.groupSource = None

    supervisor = next((p for p in program.processes if p.nodeKind == "Supervisor"), None)
    nodes = [p for p in program.processes if p.nodeKind != "Supervisor"]
    edges = list(program.edges)
    supervisor_options: list[ProgramOption] = []
    count_options: dict[str, ProgramOption] = {}

    def supervisor_count_option(node) -> ProgramOption:
        count = _count_source(program, node)
        if count.label not in count_options:
            count_options[count.label] = _option(
                count.label,
                "input",
                count.description,
                dataType=count.dataType,
                commandLine=True,
                mandatory=count.mandatory,
            )
        return count_options[count.label]

    for node in nodes:
        mode = node.optionsHandler.mode
        suffix = _task_suffix(mode)
        is_array = mode in _TASK_INDEXED_MODES

        heartbeat = _option(
            HEARTBEAT_LABEL,
            "output",
            "heartbeat channel to the Supervisor",
            channel="fifo",
            value=f"{node.name}_hb{suffix}",
        )
        node.options.append(heartbeat)

        if supervisor is not None:
            if is_array:
                reader = _option(
                    heartbeat_label(node.name) + "ith",
                    "input",
                    f"heartbeat channel of the i'th task of {node.name}",
                    countSourceOptionId=supervisor_count_option(node).id,
                )
            else:
                reader = _option(heartbeat_label(node.name), "input", f"heartbeat channel of {node.name}")
            supervisor_options.append(reader)
            _connect(edges, node, heartbeat, supervisor, reader)

        if not node.initiator:
            continue

        if supervisor is None:
            node.options.append(
                _option(
                    TRIGGER_LABEL,
                    "input",
                    "control port of this initiator, written from outside the program",
                    channel="fifo",
                    fifoTag="control",
                    value=f"{node.name}_trigger{suffix}",
                )
            )
            continue

        control = _option(TRIGGER_LABEL, "input", "control port of this initiator")
        node.options.append(control)
        if is_array:
            trigger = _option(
                trigger_label(node.name) + "ith",
                "output",
                f"trigger port to the i'th task of {node.name}",
                channel="fifo",
                fifoTag="control",
                value=f"{supervisor.name}_{node.name}_trig_${{i}}",
                countSourceOptionId=supervisor_count_option(node).id,
            )
        else:
            trigger = _option(
                trigger_label(node.name),
                "output",
                f"trigger port to {node.name}",
                channel="fifo",
                fifoTag="control",
                value=f"{supervisor.name}_{node.name}_trig",
            )
        supervisor_options.append(trigger)
        _connect(edges, supervisor, trigger, node, control)

    if supervisor is not None:
        supervisor_options.append(
            _option(
                MANUAL_LABEL,
                "input",
                "manual trigger port, written from outside the program",
                channel="fifo",
                fifoTag="control",
                value=f"{supervisor.name}_manual",
            )
        )
        supervisor_options.append(
            _option(
                NO_HOLD_FIFOS_LABEL,
                "input",
                "do not hold the FIFOs of the business channels",
                dataType="None",
                commandLine=True,
            )
        )
        supervisor_options.extend(count_options.values())
        supervisor.options = supervisor_options

    program.edges = edges
    return program
